(()=>{'use strict';
const q=s=>document.querySelector(s),api='task_api.php',csrf=q('meta[name="csrf-token"]')?.content||'';let selected=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,...options.headers}});const data=await r.json();if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
async function load(){q('#tasks').textContent='Cargando…';try{const status=q('#status').value;const data=await request(`${api}?action=list&limit=100${status?`&status=${encodeURIComponent(status)}`:''}`);q('#tasks').textContent='';for(const task of data.tasks){const node=q('#task-template').content.firstElementChild.cloneNode(true);node.dataset.id=task.public_id;node.classList.toggle('active',task.public_id===selected);node.querySelector('.task-title').textContent=task.title;node.querySelector('.task-status').textContent=task.status;node.querySelector('time').textContent=task.updated_at||'';node.querySelector('i span').style.width=`${task.progress_percent||0}%`;node.onclick=()=>detail(task.public_id);q('#tasks').append(node)}if(!data.tasks.length)q('#tasks').textContent='No hay Tasks para este filtro.'}catch(e){q('#tasks').innerHTML=`<p class="error">${esc(e.message)}</p>`}}
async function detail(id){selected=id;await load();q('#detail').innerHTML='<div class="empty">Cargando…</div>';try{render(await request(`${api}?action=detail&task=${encodeURIComponent(id)}`))}catch(e){q('#detail').innerHTML=`<p class="error">${esc(e.message)}</p>`}}
function render(d){const t=d.task,waiting=t.status==='waiting_user';const steps=d.steps.map(s=>{const a=s.approval,resume=s.step_type==='model'&&s.step_key==='respond';return `<div class="step"><b>${esc(s.title||s.step_key)}</b> <span class="${esc(s.status)}">${esc(s.status)}</span><div>${esc(s.description||s.output_summary||s.error_message||'')}</div>${a?`<div class="approval"><strong>${esc(a.safe_summary||'Aprobación de herramienta')}</strong><p>Destino: ${esc(a.safe_target||'—')} · Efecto: ${esc(a.effect||'—')}</p><code>${esc(a.fingerprint)}</code>${a.status==='pending'?`<div class="actions"><button class="approve" data-action="approve_tool" data-resume="${resume?'1':''}" data-session="${t.session_id}" data-step="${esc(s.step_key)}" data-lock="${s.lock_version}" data-fingerprint="${esc(a.fingerprint)}">Aprobar</button><button class="reject" data-action="reject_tool" data-step="${esc(s.step_key)}" data-lock="${s.lock_version}" data-fingerprint="${esc(a.fingerprint)}">Rechazar</button></div>`:''}</div>`:''}</div>`}).join('');
const traces=d.executions.filter(e=>e.trace_id).map(e=>`<li><a href="chat_activity_viewer.php?session_id=${t.session_id}&trace_id=${encodeURIComponent(e.trace_id)}" target="_blank" rel="noopener">${esc(e.trace_id)}</a> · ${esc(e.model_id||'modelo')} · ${esc(e.status)}</li>`).join('');
const current=d.steps.find(s=>s.status==='waiting_user');let decision='';if(waiting&&current&&!current.approval){const generic=current.step_type==='approval';decision=`<button data-action="${generic?'approve_step':'approve'}" data-resume="${!generic&&current.step_key==='respond'?'1':''}" data-session="${t.session_id}" data-step="${generic?esc(current.step_key):''}" data-lock="${generic?current.lock_version:t.lock_version}">Aprobar</button><button class="reject" data-action="${generic?'reject_step':'reject'}" data-step="${generic?esc(current.step_key):''}" data-lock="${generic?current.lock_version:t.lock_version}">Rechazar</button>`}
q('#detail').innerHTML=`<article class="hero"><div class="hero-head"><div><h2>${esc(t.title)}</h2><p>${esc(t.objective)}</p></div><span class="badge ${esc(t.status)}">${esc(t.status)}</span></div><div class="actions">${decision}${t.status==='failed'?`<button data-action="retry" data-lock="${t.lock_version}">Reintentar</button>`:''}${!['completed','cancelled'].includes(t.status)?`<button class="cancel" data-action="cancel" data-lock="${t.lock_version}">Cancelar</button>`:''}</div></article><div class="grid"><article class="card"><h3>Steps (${d.plan.steps_count})</h3>${steps||'Sin Steps'}</article><article class="card"><h3>Observabilidad</h3><ul>${traces||'<li>Sin traces todavía.</li>'}</ul><h3>Artifacts</h3>${d.artifacts.map(a=>`<div>${esc(a.relation)} · ${esc(a.resource?.filename||a.resource_type)}</div>`).join('')||'Sin artifacts'}</article></div><article class="card"><h3>Eventos</h3>${d.events.map(e=>`<div class="event"><b>${esc(e.event_key)}</b> ${esc(e.summary||'')}<br><small>${esc(e.created_at)}</small></div>`).join('')||'Sin eventos'}</article>`;q('#detail').querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b,t.public_id))}
async function act(b,id){b.disabled=true;const body={action:b.dataset.action,public_id:id,lock_version:Number(b.dataset.lock)};if(b.dataset.step)body.step_key=b.dataset.step;if(b.dataset.fingerprint)body.fingerprint=b.dataset.fingerprint;try{await request(api,{method:'POST',body:JSON.stringify(body)});if(b.dataset.resume==='1'){const form=new FormData();form.append('action','execute_approved_task');form.append('task_public_id',id);form.append('session_id',b.dataset.session);const r=await fetch('bedrock_chat2.php',{method:'POST',credentials:'same-origin',body:form});const result=await r.json();if(!r.ok||result.ok===false)throw new Error(result.error||'task_resume_failed')}await detail(id)}catch(e){alert(e.message);b.disabled=false}}
q('#refresh').onclick=load;q('#status').onchange=load;load();
})();
