(()=>{'use strict';
const q=s=>document.querySelector(s),api='task_api.php',csrf=q('meta[name="csrf-token"]')?.content||'',pageSize=25,op=window.TaskOperationalContext;
const controls={form:q('#filters'),search:q('#search'),status:q('#status'),priority:q('#priority'),project:q('#project'),session:q('#session'),previous:q('#previous'),next:q('#next'),page:q('#page'),summary:q('#result-summary'),board:q('#board'),tasks:q('#tasks'),workspace:q('#workspace'),viewList:q('#view-list'),viewBoard:q('#view-board')};
let selected=null,offset=0,total=0,projects=[],sessions=[],searchTimer=null,view='list',pageTasks=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byId=(rows,id)=>rows.find(row=>Number(row.id)===Number(id));
const projectName=id=>id?byId(projects,id)?.name||`Proyecto #${id}`:'Sin proyecto';
const sessionName=id=>id?byId(sessions,id)?.title||`Sesión #${id}`:'Sin sesión';
const formatDate=value=>{const date=op.parseUtc(value);return date?new Intl.DateTimeFormat('es-ES',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(date)+' UTC':'Sin fecha'};
const stepLabel=step=>step?`${step.title||step.step_key} · ${step.step_type} · ${step.status}`:'Sin Step actual';
const dateLabel=task=>{const dates=op.dateContext(task);if(dates.overdue)return`Vencida · ${formatDate(task.due_at)}`;if(dates.scheduledFuture)return`Programada · ${formatDate(task.scheduled_at)}`;if(task.due_at)return`Vence · ${formatDate(task.due_at)}`;if(task.scheduled_at)return`Programada · ${formatDate(task.scheduled_at)}`;return'Sin fechas operativas'};
async function request(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,...options.headers}});const data=await r.json();if(!r.ok||data.ok===false)throw new Error(data.error||`HTTP ${r.status}`);return data}
function filters(){return{q:controls.search.value.trim(),status:controls.status.value,priority:controls.priority.value,project_id:controls.project.value,session_id:controls.session.value}}
function queryString(includePage=true){const params=new URLSearchParams({action:'list',limit:String(pageSize),offset:String(includePage?offset:0)});for(const[key,value]of Object.entries(filters()))if(value)params.set(key,value);return params}
function syncUrl(){const params=queryString();params.delete('action');params.delete('limit');if(offset===0)params.delete('offset');if(view==='board')params.set('view','board');history.replaceState(null,'',`${location.pathname}${params.toString()?`?${params}`:''}`)}
function restoreUrl(){const params=new URLSearchParams(location.search);for(const key of['q','status','priority','project_id','session_id']){const input=controls.form.elements[key];if(input)input.value=params.get(key)||''}const raw=Number(params.get('offset')||0);offset=Number.isInteger(raw)&&raw>=0?raw:0;view=params.get('view')==='board'?'board':'list'}
function option(value,label){const node=document.createElement('option');node.value=String(value);node.textContent=label;return node}
async function loadCatalogs(){const [projectData,sessionData]=await Promise.all([request('projects.php?action=list'),request('chat2_sessions.php')]);projects=Array.isArray(projectData.projects)?projectData.projects:[];sessions=Array.isArray(sessionData.sessions)?sessionData.sessions:[];for(const project of projects)controls.project.append(option(project.id,project.name||`Proyecto #${project.id}`));renderSessionOptions()}
function renderSessionOptions(){const current=controls.session.value,projectId=Number(controls.project.value||0);controls.session.replaceChildren(option('','Todas'));for(const session of sessions.filter(item=>!projectId||Number(item.project_id)===projectId))controls.session.append(option(session.id,session.title||`Sesión #${session.id}`));controls.session.value=[...controls.session.options].some(item=>item.value===current)?current:''}
function updateSummary(){const first=total?offset+1:0,last=Math.min(offset+pageSize,total);controls.summary.textContent=view==='board'?`Tablero de la página actual: ${first}–${last} de ${total} Tasks filtradas`:`${first}–${last} de ${total} Tasks`}
function applyView(){const board=view==='board';controls.tasks.hidden=board;controls.board.hidden=!board;controls.workspace.classList.toggle('board-view',board);controls.viewList.setAttribute('aria-pressed',String(!board));controls.viewBoard.setAttribute('aria-pressed',String(board));syncUrl()}
function renderBoard(tasks){const grouped=op.groupBoard(tasks);controls.board.textContent='';for(const column of op.boardColumns){const section=document.createElement('section');section.className=`board-column board-${column.key}`;const heading=document.createElement('h2');heading.innerHTML=`${esc(column.label)} <span title="Tasks visibles en esta página">${grouped[column.key].length} visibles</span>`;section.append(heading);const cards=document.createElement('div');cards.className='board-cards';for(const task of grouped[column.key]){const node=q('#board-card-template').content.firstElementChild.cloneNode(true),situation=op.situation(task),dates=op.dateContext(task);node.dataset.id=task.public_id;node.classList.toggle('active',task.public_id===selected);node.classList.toggle('overdue',dates.overdue);node.querySelector('.board-title').textContent=task.title;node.querySelector('.board-context').textContent=`${projectName(task.project_id)} · ${sessionName(task.session_id)}`;node.querySelector('.board-status').textContent=task.status;node.querySelector('.board-priority').textContent=task.priority;node.querySelector('.board-situation').textContent=situation.label;node.querySelector('.board-situation').className=`board-situation ${situation.key}`;node.querySelector('.board-step').textContent=stepLabel(task.current_step);node.querySelector('.board-date').textContent=dateLabel(task);node.querySelector('i span').style.width=`${task.progress_percent||0}%`;node.onclick=()=>detail(task.public_id);cards.append(node)}if(!grouped[column.key].length){const empty=document.createElement('p');empty.className='board-empty';empty.textContent='Sin Tasks visibles';cards.append(empty)}section.append(cards);controls.board.append(section)}applyView()}
async function load(){q('#tasks').textContent='Cargando…';syncUrl();try{const data=await request(`${api}?${queryString()}`);total=Number(data.total||0);pageTasks=Array.isArray(data.tasks)?data.tasks:[];renderBoard(pageTasks);if(offset>0&&offset>=total){offset=Math.max(0,Math.floor(Math.max(0,total-1)/pageSize)*pageSize);return load()}q('#tasks').textContent='';for(const task of data.tasks){const node=q('#task-template').content.firstElementChild.cloneNode(true);node.dataset.id=task.public_id;node.classList.toggle('active',task.public_id===selected);node.querySelector('.task-title').textContent=task.title;node.querySelector('.task-context').textContent=`${projectName(task.project_id)} · ${sessionName(task.session_id)}`;const situation=op.situation(task);node.querySelector('.task-situation').textContent=situation.label;node.querySelector('.task-situation').className=`task-situation ${situation.key}`;node.querySelector('.task-step').textContent=stepLabel(task.current_step);node.querySelector('.task-dates').textContent=dateLabel(task);node.classList.toggle('overdue',op.dateContext(task).overdue);node.querySelector('.task-status').textContent=task.status;node.querySelector('.task-priority').textContent=task.priority;node.querySelector('time').textContent=task.updated_at||'';node.querySelector('i span').style.width=`${task.progress_percent||0}%`;node.onclick=()=>detail(task.public_id);q('#tasks').append(node)}if(!data.tasks.length)q('#tasks').textContent='No hay Tasks para estos filtros.';updateSummary();controls.page.textContent=total?`Página ${Math.floor(offset/pageSize)+1} de ${Math.max(1,Math.ceil(total/pageSize))}`:'Sin resultados';controls.previous.disabled=offset===0;controls.next.disabled=offset+pageSize>=total}catch(e){q('#tasks').innerHTML=`<p class="error">${esc(e.message)}</p>`;controls.summary.textContent='No se pudo cargar el listado.';controls.previous.disabled=controls.next.disabled=true}}
async function detail(id){selected=id;await load();q('#detail').innerHTML='<div class="empty">Cargando…</div>';try{render(await request(`${api}?action=detail&task=${encodeURIComponent(id)}`))}catch(e){q('#detail').innerHTML=`<p class="error">${esc(e.message)}</p>`}}
function render(d){const t=d.task,waiting=t.status==='waiting_user';const steps=d.steps.map(s=>{const a=s.approval,resume=s.step_type==='model'&&s.step_key==='respond';return `<div class="step"><b>${esc(s.title||s.step_key)}</b> <span class="${esc(s.status)}">${esc(s.status)}</span><div>${esc(s.description||s.output_summary||s.error_message||'')}</div>${a?`<div class="approval"><strong>${esc(a.safe_summary||'Aprobación de herramienta')}</strong><p>Destino: ${esc(a.safe_target||'—')} · Efecto: ${esc(a.effect||'—')}</p><code>${esc(a.fingerprint)}</code>${a.status==='pending'?`<div class="actions"><button class="approve" data-action="approve_tool" data-resume="${resume?'1':''}" data-session="${t.session_id}" data-step="${esc(s.step_key)}" data-lock="${s.lock_version}" data-fingerprint="${esc(a.fingerprint)}">Aprobar</button><button class="reject" data-action="reject_tool" data-step="${esc(s.step_key)}" data-lock="${s.lock_version}" data-fingerprint="${esc(a.fingerprint)}">Rechazar</button></div>`:a.can_resume?`<div class="actions"><button class="approve" data-action="resume_tool" data-resume="1" data-session="${t.session_id}">Reanudar</button></div>`:''}</div>`:''}</div>`}).join('');
const traces=d.executions.filter(e=>e.trace_id).map(e=>`<li><a href="chat_activity_viewer.php?session_id=${t.session_id}&trace_id=${encodeURIComponent(e.trace_id)}" target="_blank" rel="noopener">${esc(e.trace_id)}</a> · ${esc(e.model_id||'modelo')} · ${esc(e.status)}</li>`).join('');
const current=d.steps.find(s=>s.status==='waiting_user');let decision='';if(waiting&&current&&!current.approval){const generic=current.step_type==='approval';decision=`<button data-action="${generic?'approve_step':'approve'}" data-resume="${!generic&&current.step_key==='respond'?'1':''}" data-session="${t.session_id}" data-step="${generic?esc(current.step_key):''}" data-lock="${generic?current.lock_version:t.lock_version}">Aprobar</button><button class="reject" data-action="${generic?'reject_step':'reject'}" data-step="${generic?esc(current.step_key):''}" data-lock="${generic?current.lock_version:t.lock_version}">Rechazar</button>`}
const currentStep=d.steps.find(s=>s.step_key===t.current_step?.step_key)||null,dates=op.dateContext(t),situation=op.situation(t,d.dependencies);const dependencies=d.dependencies.map(dep=>`<li class="dependency ${op.dependencySatisfied(dep)?'satisfied':'blocking'}"><div><b>${esc(dep.depends_on_title)}</b><small>${esc(dep.condition)} · ${esc(dep.depends_on_status)}${op.dependencySatisfied(dep)?' · satisfecha':' · bloquea'}</small></div><button type="button" data-dependency-remove="${esc(dep.depends_on_public_id)}">Quitar</button></li>`).join('');const waitInfo=currentStep?.step_type==='wait'&&currentStep.wait_until?`<p class="notice wait">Espera persistente hasta ${esc(formatDate(currentStep.wait_until))}.</p>`:'';const humanInfo=t.status==='waiting_user'?'<p class="notice human">Esta Task requiere una decisión o reanudación humana.</p>':'';
q('#detail').innerHTML=`<article class="hero ${dates.overdue?'overdue':''}"><div class="hero-head"><div><h2>${esc(t.title)}</h2><p>${esc(t.objective)}</p><div class="context-links"><span>${esc(projectName(t.project_id))}</span><a href="chat.php?session_id=${t.session_id}">${esc(sessionName(t.session_id))} ↗</a><span>Prioridad: ${esc(t.priority)}</span><span>Progreso: ${t.progress_percent}%</span></div></div><span class="badge ${esc(t.status)}">${esc(t.status)}</span></div><section class="operational-summary"><strong class="${situation.key}">${esc(situation.label)}</strong><span>Programada: ${esc(formatDate(t.scheduled_at))}</span><span class="${dates.overdue?'overdue-text':''}">Vence: ${esc(formatDate(t.due_at))}${dates.overdue?' · vencida':''}</span><span>Step: ${esc(stepLabel(currentStep))}</span>${currentStep?.agent_key?`<span>Agente: ${esc(currentStep.agent_key)}</span>`:''}${currentStep?.model_id?`<span>Modelo: ${esc(currentStep.model_id)}</span>`:''}</section>${waitInfo}${humanInfo}<div class="actions">${decision}${t.status==='failed'?`<button data-action="retry" data-lock="${t.lock_version}">Reintentar</button>`:''}${!['completed','cancelled'].includes(t.status)?`<button class="cancel" data-action="cancel" data-lock="${t.lock_version}">Cancelar</button>`:''}</div></article><div class="grid"><article class="card"><h3>Steps (${d.plan.steps_count})</h3>${steps||'Sin Steps'}</article><article class="card dependencies"><h3>Dependencias (${d.dependencies.length})</h3><ul>${dependencies||'<li>Sin dependencias.</li>'}</ul><form id="dependency-add" class="dependency-add"><label>Task requerida (public_id)<input name="depends_on_public_id" required pattern="[a-fA-F0-9-]{36}"></label><label>Condición<select name="condition"><option value="completed">completed</option><option value="terminal_success">terminal_success</option><option value="terminal_any">terminal_any</option></select></label><button type="submit">Agregar dependencia</button></form></article><article class="card"><h3>Observabilidad</h3><ul>${traces||'<li>Sin traces todavía.</li>'}</ul><h3>Artifacts</h3>${d.artifacts.map(a=>`<div>${esc(a.relation)} · ${esc(a.resource?.filename||a.resource_type)}</div>`).join('')||'Sin artifacts'}</article></div><article class="card"><h3>Eventos</h3>${d.events.map(e=>`<div class="event"><b>${esc(e.event_key)}</b> ${esc(e.summary||'')}<br><small>${esc(e.created_at)}</small></div>`).join('')||'Sin eventos'}</article>`;q('#detail').querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b,t.public_id));q('#detail').querySelectorAll('[data-dependency-remove]').forEach(b=>b.onclick=()=>dependencyAction('remove_dependency',t.public_id,b.dataset.dependencyRemove));q('#dependency-add').onsubmit=e=>{e.preventDefault();const form=new FormData(e.currentTarget);dependencyAction('add_dependency',t.public_id,String(form.get('depends_on_public_id')||'').trim(),String(form.get('condition')||'completed'))}}
async function dependencyAction(action,publicId,dependsOnPublicId,condition='completed'){try{await request(api,{method:'POST',body:JSON.stringify({action,public_id:publicId,depends_on_public_id:dependsOnPublicId,condition})});await detail(publicId)}catch(e){alert(e.message)}}
async function act(b,id){b.disabled=true;const body={action:b.dataset.action,public_id:id,lock_version:Number(b.dataset.lock)};if(b.dataset.step)body.step_key=b.dataset.step;if(b.dataset.fingerprint)body.fingerprint=b.dataset.fingerprint;try{if(b.dataset.action!=='resume_tool')await request(api,{method:'POST',body:JSON.stringify(body)});if(b.dataset.resume==='1'){const form=new FormData();form.append('action','execute_approved_task');form.append('task_public_id',id);form.append('session_id',b.dataset.session);const r=await fetch('bedrock_chat2.php',{method:'POST',credentials:'same-origin',body:form});const result=await r.json();if(!r.ok||result.ok===false)throw new Error(result.error||'task_resume_failed')}await detail(id)}catch(e){alert(e.message);b.disabled=false}}
function changed(){offset=0;renderSessionOptions();load()}
controls.viewList.onclick=()=>{view='list';applyView();updateSummary()};controls.viewBoard.onclick=()=>{view='board';applyView();updateSummary()};q('#refresh').onclick=load;q('#clear').onclick=()=>{controls.form.reset();changed()};controls.status.onchange=changed;controls.priority.onchange=changed;controls.project.onchange=changed;controls.session.onchange=changed;controls.search.oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(changed,250)};controls.form.onsubmit=e=>{e.preventDefault();changed()};controls.previous.onclick=()=>{offset=Math.max(0,offset-pageSize);load()};controls.next.onclick=()=>{if(offset+pageSize<total){offset+=pageSize;load()}};
(async()=>{restoreUrl();try{await loadCatalogs();restoreUrl();renderSessionOptions()}catch(e){controls.summary.textContent=`Contextos no disponibles: ${e.message}`}await load()})();
})();
