<?php
declare(strict_types=1);
final class AutonomyBudgetService{
 public function __construct(private AutonomyPolicyService$policies,private AutonomyBudgetStoreInterface$store){}
 public function startCycle(int$userId,int$projectId):array{$policy=$this->policies->getOrCreate($userId,$projectId);if($policy->mode==='disabled')throw new TaskTransitionException('autonomy_disabled');if($policy->status!=='active')throw new TaskTransitionException('autonomy_'.$policy->status);return$this->cycleDto($this->store->startCycle($userId,$projectId,TaskPublicId::generate()),$policy);}
 public function inspect(int$userId,int$projectId):array{$policy=$this->policies->getOrCreate($userId,$projectId);$cycle=$this->store->findActiveCycle($userId,$projectId);return['policy'=>$policy->toArray(),'cycle'=>$cycle===null?null:$this->cycleDto($cycle,$policy)];}
 public function reserve(int$userId,int$projectId,string$cyclePublicId,string$idempotencyKey,AutonomyBudgetRequest$request):AutonomyBudgetReservation{$policy=$this->policies->getOrCreate($userId,$projectId);if($policy->mode==='disabled')return new AutonomyBudgetReservation(false,'autonomy_disabled',null,false,[],[]);if($policy->status!=='active')return new AutonomyBudgetReservation(false,'autonomy_'.$policy->status,null,false,[],[]);return$this->store->reserve($userId,$projectId,$cyclePublicId,$idempotencyKey,$request,$policy);}
 public function consume(int$u,int$p,string$r):array{return$this->store->consume($u,$p,$r);}
 public function release(int$u,int$p,string$r):array{return$this->store->release($u,$p,$r);}
 private function cycleDto(array$row,AutonomyPolicy$policy):array{$map=['decisions'=>'decisions_consumed','tasks'=>'tasks_consumed','replans'=>'replans_consumed','input_tokens'=>'input_tokens_consumed','output_tokens'=>'output_tokens_consumed','tool_calls'=>'tool_calls_consumed','write_tool_calls'=>'write_tool_calls_consumed','runtime_seconds'=>'runtime_seconds_consumed'];$limits=['decisions'=>'max_decisions_per_cycle','tasks'=>'max_tasks_per_cycle','replans'=>'max_replans_per_cycle','input_tokens'=>'max_input_tokens','output_tokens'=>'max_output_tokens','tool_calls'=>'max_tool_calls','write_tool_calls'=>'max_write_tool_calls','runtime_seconds'=>'max_runtime_seconds'];$usage=[];$remaining=[];foreach($map as$key=>$column){$usage[$key]=(int)$row[$column];$remaining[$key]=max(0,$policy->limits[$limits[$key]]-$usage[$key]);}return['public_id'=>(string)$row['public_id'],'status'=>(string)$row['status'],'usage'=>$usage,'remaining'=>$remaining,'limits'=>$policy->limits];}
}
