<?php
declare(strict_types=1);
final class AutonomyPolicyRepository implements AutonomyPolicyStoreInterface{
 public function __construct(private mysqli$db){}
 public function findOwned(int$userId,int$projectId):?array{$s=$this->p('SELECT a.* FROM ProjectAutonomyPolicies a JOIN Projects p ON p.id_=a.project_id_ AND p.user_id_=a.user_id_ WHERE a.user_id_=? AND a.project_id_=? AND p.status<>\'deleted\' LIMIT 1');$s->bind_param('ii',$userId,$projectId);return$this->one($s);}
 public function createDefault(int$userId,int$projectId,string$publicId):array{$s=$this->p("INSERT INTO ProjectAutonomyPolicies(public_id,user_id_,project_id_,mode,status) SELECT ?,p.user_id_,p.id_,'disabled','active' FROM Projects p WHERE p.id_=? AND p.user_id_=? AND p.status<>'deleted' ON DUPLICATE KEY UPDATE id_=LAST_INSERT_ID(id_)");$s->bind_param('sii',$publicId,$projectId,$userId);$this->x($s);$s->close();return$this->findOwned($userId,$projectId)??throw new TaskNotFoundException('project_not_found');}
 public function updateOwned(int$userId,int$projectId,int$lockVersion,array$c):array{$sql='UPDATE ProjectAutonomyPolicies SET mode=?,status=?,stop_reason=?,max_tasks_per_cycle=?,max_decisions_per_cycle=?,max_descendant_depth=?,max_replans_per_cycle=?,max_runtime_seconds=?,max_input_tokens=?,max_output_tokens=?,max_tool_calls=?,max_write_tool_calls=?,lock_version=lock_version+1 WHERE user_id_=? AND project_id_=? AND lock_version=?';$s=$this->p($sql);$s->bind_param('sssiiiiiiiiiiii',$c['mode'],$c['status'],$c['stop_reason'],$c['max_tasks_per_cycle'],$c['max_decisions_per_cycle'],$c['max_descendant_depth'],$c['max_replans_per_cycle'],$c['max_runtime_seconds'],$c['max_input_tokens'],$c['max_output_tokens'],$c['max_tool_calls'],$c['max_write_tool_calls'],$userId,$projectId,$lockVersion);$this->x($s);$n=$s->affected_rows;$s->close();if($n!==1)throw new TaskConcurrencyException('autonomy_policy_conflict');return$this->findOwned($userId,$projectId)??throw new TaskNotFoundException('not_found');}
 private function one(mysqli_stmt$s):?array{$this->x($s);$row=$s->get_result()->fetch_assoc();$s->close();return$row?:null;}private function p(string$q):mysqli_stmt{$s=$this->db->prepare($q);if(!$s)throw new RuntimeException('database_error');return$s;}private function x(mysqli_stmt$s):void{if(!$s->execute())throw new RuntimeException('database_error');}
}
