<?php
declare(strict_types=1);
/** Read-only, owned and bounded snapshot source. */
final class NextWorkSnapshotRepository implements NextWorkSnapshotSourceInterface{
 public function __construct(private mysqli$db){}
 public function load(int$userId,int$projectId,string$publicId):array{$project=$this->one('SELECT id_,user_id_,name,description,status FROM Projects WHERE id_=? AND user_id_=? AND status<>\'deleted\'','ii',[$projectId,$userId]);if(!$project)return['project'=>null,'task'=>null];$task=$this->one('SELECT t.id_,t.public_id,t.user_id_,t.project_id_,t.session_id_,t.title,t.objective,t.status,t.result_summary,t.error_message FROM Tasks t JOIN ChatSessions s ON s.id_=t.session_id_ AND s.user_id_=t.user_id_ WHERE t.public_id=? AND t.user_id_=? AND t.project_id_=?','sii',[$publicId,$userId,$projectId]);if(!$task)return['project'=>$project,'task'=>null];$taskId=(int)$task['id_'];return['project'=>$project,'task'=>$task,'project_context'=>$this->rows('SELECT type,title,content FROM ProjectContext WHERE project_id_=? ORDER BY updated_at DESC,id_ DESC LIMIT 20','i',[$projectId]),'steps'=>$this->rows('SELECT step_key,title,step_type,status,output_summary,agent_key FROM TaskSteps WHERE task_id_=? ORDER BY position,id_ LIMIT 20','i',[$taskId]),'executions'=>$this->rows('SELECT e.attempt_number,e.status,e.model_id,e.error_message,s.step_key FROM TaskExecutions e LEFT JOIN TaskSteps s ON s.id_=e.step_id_ AND s.task_id_=e.task_id_ WHERE e.task_id_=? ORDER BY e.id_ DESC LIMIT 10','i',[$taskId]),'events'=>$this->rows('SELECT event_key,from_status,to_status,summary FROM TaskEvents WHERE task_id_=? ORDER BY id_ DESC LIMIT 20','i',[$taskId]),'artifacts'=>$this->rows("SELECT a.relation,a.resource_type,CONCAT(a.resource_type,':',a.relation) public_metadata FROM TaskArtifacts a JOIN TaskExecutions e ON e.id_=a.execution_id_ WHERE e.task_id_=? ORDER BY a.id_ DESC LIMIT 15",'i',[$taskId]),'recent_tasks'=>$this->rows('SELECT public_id,title,status,result_summary FROM Tasks WHERE user_id_=? AND project_id_=? AND id_<>? ORDER BY updated_at DESC,id_ DESC LIMIT 10','iii',[$userId,$projectId,$taskId])];}
 private function one(string$sql,string$types,array$values):?array{$rows=$this->rows($sql.' LIMIT 1',$types,$values);return$rows[0]??null;}
 private function rows(string$sql,string$types,array$values):array{$stmt=$this->db->prepare($sql);if(!$stmt)throw new RuntimeException('database_error');$stmt->bind_param($types,...$values);if(!$stmt->execute())throw new RuntimeException('database_error');$rows=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);$stmt->close();return$rows;}
}
