<?php
declare(strict_types=1);
final class NextWorkProposalRepository implements NextWorkProposalStoreInterface{
 public function __construct(private mysqli$db){}
 public function resolveScope(int$u,int$p,string$taskPublic,string$cyclePublic):array{$s=$this->p("SELECT t.id_ source_task_id,t.public_id source_task_public_id,t.session_id_,t.status source_status,t.cancelled_at source_cancelled_at,t.parent_task_id_,c.id_ cycle_id,c.public_id cycle_public_id,c.status cycle_status,ap.id_ policy_id,ap.mode policy_mode,ap.status policy_status FROM Tasks t JOIN Projects pr ON pr.id_=t.project_id_ AND pr.user_id_=? JOIN ProjectAutonomyCycles c ON c.project_id_=pr.id_ AND c.user_id_=? AND c.public_id=? JOIN ProjectAutonomyPolicies ap ON ap.id_=c.policy_id_ AND ap.project_id_=pr.id_ AND ap.user_id_=? WHERE t.public_id=? AND t.user_id_=? AND t.project_id_=? LIMIT 1");$s->bind_param('iisisii',$u,$u,$cyclePublic,$u,$taskPublic,$u,$p);$this->x($s);$r=$s->get_result()->fetch_assoc();$s->close();if(!$r||!in_array((string)$r['source_status'],['completed','failed','cancelled'],true)||(string)$r['cycle_status']!=='active')throw new TaskValidationException('next_work_proposal_scope_invalid');$r['descendant_depth']=$this->depth((int)$r['source_task_id']);return$r;}
 public function createOrGet(array$scope,string$public,string$key,string$hash,NextWorkDecision$d,string$status,string$reason,bool$decisionAccounted=false):array{$e=json_encode($d->evidence,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$title=$d->proposedTitle;$objective=(string)$d->proposedObjective;$s=$this->p('INSERT INTO NextWorkProposals(public_id,user_id_,project_id_,source_task_id_,autonomy_cycle_id_,status,dedupe_key,payload_hash,public_reason,proposed_title,proposed_objective,evidence_json,authorization_reason,decision_accounted) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$u=(int)$scope['user_id'];$p=(int)$scope['project_id'];$source=(int)$scope['source_task_id'];$cycle=(int)$scope['cycle_id'];try{$s->bind_param('siiiissssssssi',$public,$u,$p,$source,$cycle,$status,$key,$hash,$d->publicReason,$title,$objective,$e,$reason,$decisionAccounted);$this->x($s);$s->close();return$this->findOwned($u,$public)??throw new RuntimeException('proposal_create_failed');}catch(mysqli_sql_exception$ex){$s->close();$existing=$this->byDedupe($cycle,$key);if(!$existing||!hash_equals((string)$existing['payload_hash'],$hash))throw new TaskConcurrencyException('proposal_dedupe_conflict');return$existing;}}
 public function listApproved(int$limit):array{$limit=max(1,min(20,$limit));$s=$this->p("SELECT p.public_id,p.user_id_,p.project_id_ FROM NextWorkProposals p JOIN ProjectAutonomyCycles c ON c.id_=p.autonomy_cycle_id_ AND c.status='active' JOIN ProjectAutonomyPolicies a ON a.id_=c.policy_id_ AND a.status='active' AND a.mode<>'disabled' WHERE p.status='authorized' AND p.approved_at IS NOT NULL ORDER BY p.approved_at,p.id_ LIMIT ?");$s->bind_param('i',$limit);$this->x($s);$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return$rows;}
 public function findOwned(int$u,string$public,bool$lock=false):?array{$sql="SELECT p.*,r.public_id reservation_public_id,t.public_id spawned_task_public_id,src.public_id source_task_public_id,c.public_id cycle_public_id FROM NextWorkProposals p JOIN Tasks src ON src.id_=p.source_task_id_ JOIN ProjectAutonomyCycles c ON c.id_=p.autonomy_cycle_id_ LEFT JOIN ProjectAutonomyReservations r ON r.id_=p.reservation_id_ LEFT JOIN Tasks t ON t.id_=p.spawned_task_id_ WHERE p.user_id_=? AND p.public_id=? LIMIT 1".($lock?' FOR UPDATE':'');$s=$this->p($sql);$s->bind_param('is',$u,$public);$this->x($s);$r=$s->get_result()->fetch_assoc();$s->close();return$r?:null;}
 public function transition(int$u,string$public,int$lock,array$from,string$to,array$f=[]):array{$sets=['status=?','lock_version=lock_version+1'];$types='s';$args=[$to];$map=['authorization_reason'=>'s','reservation_id_'=>'i','spawned_task_id_'=>'i','approved_at'=>'s','rejected_at'=>'s','spawned_at'=>'s'];foreach($map as$k=>$type)if(array_key_exists($k,$f)){$sets[]="$k=?";$types.=$type;$args[]=$f[$k];}$marks=implode(',',array_fill(0,count($from),'?'));$types.='isi'.str_repeat('s',count($from));$args[]=$u;$args[]=$public;$args[]=$lock;array_push($args,...$from);$s=$this->p('UPDATE NextWorkProposals SET '.implode(',',$sets)." WHERE user_id_=? AND public_id=? AND lock_version=? AND status IN ($marks)");$s->bind_param($types,...$args);$this->x($s);if($s->affected_rows!==1){$s->close();throw new TaskConcurrencyException('proposal_transition_conflict');}$s->close();return$this->findOwned($u,$public)??throw new TaskNotFoundException('proposal_not_found');}
 public function reservationId(int$u,int$p,string$public):int{$s=$this->p('SELECT id_ FROM ProjectAutonomyReservations WHERE user_id_=? AND project_id_=? AND public_id=? LIMIT 1');$s->bind_param('iis',$u,$p,$public);$this->x($s);$r=$s->get_result()->fetch_assoc();$s->close();return (int)($r['id_']??throw new TaskValidationException('reservation_scope_invalid'));}
 public function taskId(int$u,int$p,string$public):int{$s=$this->p('SELECT id_ FROM Tasks WHERE user_id_=? AND project_id_=? AND public_id=? LIMIT 1');$s->bind_param('iis',$u,$p,$public);$this->x($s);$r=$s->get_result()->fetch_assoc();$s->close();return (int)($r['id_']??throw new TaskValidationException('spawned_task_scope_invalid'));}
 private function byDedupe(int$cycle,string$key):?array{$s=$this->p('SELECT * FROM NextWorkProposals WHERE autonomy_cycle_id_=? AND dedupe_key=? LIMIT 1');$s->bind_param('is',$cycle,$key);$this->x($s);$r=$s->get_result()->fetch_assoc();$s->close();return$r?:null;}
 private function depth(int$id):int{$depth=0;$seen=[];while($id>0&&$depth<=10){if(isset($seen[$id]))throw new TaskValidationException('task_lineage_cycle');$seen[$id]=true;$s=$this->p('SELECT parent_task_id_ FROM Tasks WHERE id_=? LIMIT 1');$s->bind_param('i',$id);$this->x($s);$r=$s->get_result()->fetch_assoc();$s->close();$id=(int)($r['parent_task_id_']??0);if($id>0)$depth++;}return$depth+1;}
 private function p(string$q):mysqli_stmt{$s=$this->db->prepare($q);if(!$s)throw new RuntimeException('proposal_prepare_failed');return$s;}private function x(mysqli_stmt$s):void{if(!$s->execute())throw new RuntimeException('proposal_query_failed');}
}
