<?php
declare(strict_types=1);
final class NextWorkDecisionValidator{
 public const MAX_PAYLOAD_BYTES=12000,MAX_EVIDENCE=8,MAX_REASON=600,MAX_QUESTION=800,MAX_TITLE=255,MAX_OBJECTIVE=3000,MAX_EVIDENCE_SUMMARY=500;
 /** @param list<string> $allowedReferences */
 public function validateJson(string$json,array$allowedReferences):NextWorkDecision{if(strlen($json)>self::MAX_PAYLOAD_BYTES)throw new TaskValidationException('next_work_payload_too_large');try{$data=json_decode($json,true,24,JSON_THROW_ON_ERROR);}catch(JsonException){throw new TaskValidationException('next_work_json_invalid');}if(!is_array($data)||array_is_list($data))throw new TaskValidationException('next_work_payload_invalid');return$this->validate($data,$allowedReferences);}
 public function validate(array$data,array$allowedReferences):NextWorkDecision{$decision=$this->string($data,'decision',32);if(!in_array($decision,[NextWorkDecision::STOP,NextWorkDecision::ASK_USER,NextWorkDecision::PROPOSE_TASK],true))throw new TaskValidationException('next_work_decision_invalid');$allowed=['decision','public_reason','evidence'];if($decision===NextWorkDecision::ASK_USER)$allowed[]='question';if($decision===NextWorkDecision::PROPOSE_TASK){$allowed[]='proposed_title';$allowed[]='proposed_objective';}if(array_diff(array_keys($data),$allowed)!==[])throw new TaskValidationException('next_work_fields_invalid');$reason=$this->string($data,'public_reason',self::MAX_REASON);$raw=$data['evidence']??null;if(!is_array($raw)||count($raw)>self::MAX_EVIDENCE)throw new TaskValidationException('next_work_evidence_invalid');$evidence=[];$refs=array_fill_keys($allowedReferences,true);foreach($raw as$item){if(!is_array($item)||array_is_list($item)||array_diff(array_keys($item),['source','reference','summary'])!==[]||count($item)!==3)throw new TaskValidationException('next_work_evidence_invalid');$source=$this->string($item,'source',40);$reference=$this->string($item,'reference',100);$summary=$this->string($item,'summary',self::MAX_EVIDENCE_SUMMARY);if(!in_array($source,['project','project_context','task','step','execution','event','artifact','recent_task'],true)||!isset($refs[$reference])||preg_match('/^(?:id_|[0-9]+)$/',$reference))throw new TaskValidationException('next_work_evidence_scope_invalid');$evidence[]=['source'=>$source,'reference'=>$reference,'summary'=>$summary];}$question=$decision===NextWorkDecision::ASK_USER?$this->string($data,'question',self::MAX_QUESTION):null;$title=$decision===NextWorkDecision::PROPOSE_TASK&&array_key_exists('proposed_title',$data)?$this->string($data,'proposed_title',self::MAX_TITLE):null;$objective=$decision===NextWorkDecision::PROPOSE_TASK?$this->string($data,'proposed_objective',self::MAX_OBJECTIVE):null;return new NextWorkDecision($decision,$reason,$evidence,$question,$title,$objective);}
 private function string(array$data,string$key,int$max):string{$value=$data[$key]??null;if(!is_string($value)||trim($value)===''||mb_strlen($value)>$max)throw new TaskValidationException('next_work_'.$key.'_invalid');$clean=trim(preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/u','',$value)??'');if($clean==='')throw new TaskValidationException('next_work_'.$key.'_invalid');return$clean;}
}
