<?php
declare(strict_types=1);
final class NextWorkProposalService{
 public function __construct(private NextWorkProposalStoreInterface$proposals,private AutonomyPolicyService$policies,private AutonomyBudgetService$budgets,private NextWorkAuthorizationService$authorization,private TaskAutonomyTaskCreator$tasks){}
 public function propose(int$u,int$p,string$sourceTask,string$cycle,NextWorkDecision$d,bool$decisionAccounted=false):?NextWorkProposal{if($d->decision!==NextWorkDecision::PROPOSE_TASK)return null;if(count($d->evidence)>NextWorkDecisionValidator::MAX_EVIDENCE||strlen($this->payload($d))>NextWorkDecisionValidator::MAX_PAYLOAD_BYTES)throw new TaskValidationException('proposal_payload_invalid');if($d->proposedObjective===null||trim($d->proposedObjective)===''||mb_strlen($d->proposedObjective)>NextWorkDecisionValidator::MAX_OBJECTIVE)throw new TaskValidationException('proposal_objective_required');$scope=$this->scope($u,$p,$sourceTask,$cycle);$policy=$this->policies->getOrCreate($u,$p);$payload=$this->payload($d);$key=hash('sha256',$u.'|'.$p.'|'.$scope['cycle_id'].'|'.$scope['source_task_id'].'|'.$payload);$status=($policy->mode==='supervised'||$scope['source_status']==='cancelled')&&$policy->status==='active'?NextWorkProposal::PENDING:NextWorkProposal::AUTHORIZED;$reason=$status===NextWorkProposal::PENDING?'approval_required':'authorization_pending';$row=$this->proposals->createOrGet($scope,TaskPublicId::generate(),$key,hash('sha256',$payload),$d,$status,$reason,$decisionAccounted);$proposal=NextWorkProposal::fromRow($row);if($proposal->status===NextWorkProposal::SPAWNED||$proposal->status===NextWorkProposal::PENDING||$proposal->status===NextWorkProposal::REJECTED)return$proposal;return$this->authorizeAndSpawn($u,$p,$scope,$proposal,false);}
 public function approve(int$u,int$p,string$public,int$lock):NextWorkProposal{$row=$this->proposals->findOwned($u,$public)??throw new TaskNotFoundException('proposal_not_found');if((int)$row['project_id_']!==$p)throw new TaskNotFoundException('proposal_not_found');if($row['status']===NextWorkProposal::SPAWNED)return NextWorkProposal::fromRow($row);if($row['status']!==NextWorkProposal::PENDING)throw new TaskTransitionException('proposal_not_pending');if((int)$row['lock_version']!==$lock)throw new TaskConcurrencyException('proposal_lock_conflict');$scope=$this->scope($u,$p,(string)$row['source_task_public_id'],(string)$row['cycle_public_id']);$policy=$this->policies->getOrCreate($u,$p);if($policy->mode==='disabled'||$policy->status!=='active')throw new TaskTransitionException($policy->mode==='disabled'?'autonomy_disabled':'autonomy_'.$policy->status);$row=$this->proposals->transition($u,$public,$lock,[NextWorkProposal::PENDING],NextWorkProposal::AUTHORIZED,['approved_at'=>gmdate('Y-m-d H:i:s.u'),'authorization_reason'=>'approval_granted']);return$this->authorizeAndSpawn($u,$p,$scope,NextWorkProposal::fromRow($row),true);}
 public function reject(int$u,int$p,string$public,int$lock):NextWorkProposal{$row=$this->proposals->findOwned($u,$public)??throw new TaskNotFoundException('proposal_not_found');if((int)$row['project_id_']!==$p)throw new TaskNotFoundException('proposal_not_found');if($row['status']===NextWorkProposal::REJECTED)return NextWorkProposal::fromRow($row);if($row['status']!==NextWorkProposal::PENDING)throw new TaskTransitionException('proposal_not_pending');return NextWorkProposal::fromRow($this->proposals->transition($u,$public,$lock,[NextWorkProposal::PENDING],NextWorkProposal::REJECTED,['rejected_at'=>gmdate('Y-m-d H:i:s.u'),'authorization_reason'=>'user_rejected']));}
 public function reconcile(int$u,int$p,string$public):NextWorkProposal{$row=$this->proposals->findOwned($u,$public)??throw new TaskNotFoundException('proposal_not_found');if((int)$row['project_id_']!==$p)throw new TaskNotFoundException('proposal_not_found');$proposal=NextWorkProposal::fromRow($row);if($proposal->status===NextWorkProposal::SPAWNED)return$proposal;$scope=$this->scope($u,$p,(string)$row['source_task_public_id'],(string)$row['cycle_public_id']);return$this->authorizeAndSpawn($u,$p,$scope,$proposal,$row['approved_at']!==null);}
 private function authorizeAndSpawn(int$u,int$p,array$scope,NextWorkProposal$proposal,bool$approved):NextWorkProposal{$reservationKey='proposal:'.$proposal->publicId;$policy=$this->policies->getOrCreate($u,$p);if($policy->mode==='supervised'&&!$approved)throw new TaskTransitionException('proposal_approval_required');if($policy->mode==='disabled'||$policy->status!=='active')return$this->deny($u,$proposal,$policy->mode==='disabled'?'autonomy_disabled':'autonomy_'.$policy->status);$existing=$this->findTask($u,$p,$scope,$proposal);$reservation=($approved||$proposal->decisionAccounted)? $this->budgets->reserve($u,$p,(string)$scope['cycle_public_id'],$reservationKey,new AutonomyBudgetRequest(decisions:$proposal->decisionAccounted?0:1,tasks:1,descendantDepth:(int)$scope['descendant_depth'])) : $this->fromAuthorization($this->authorization->authorize(new NextWorkDecision(NextWorkDecision::PROPOSE_TASK,$proposal->publicReason,$proposal->evidence,null,$proposal->proposedTitle,$proposal->proposedObjective),$u,$p,(string)$scope['cycle_public_id'],$reservationKey,(int)$scope['descendant_depth'],(string)$scope['source_status']));if(!$reservation->allowed&&$existing===null)return$this->deny($u,$proposal,$reservation->reasonCode);if($proposal->reservationPublicId===null&&$reservation->reservationPublicId!==null)$proposal=NextWorkProposal::fromRow($this->proposals->transition($u,$proposal->publicId,$proposal->lockVersion,[NextWorkProposal::AUTHORIZED,NextWorkProposal::FAILED],NextWorkProposal::SPAWNING,['reservation_id_'=>$this->proposals->reservationId($u,$p,$reservation->reservationPublicId),'authorization_reason'=>'budget_reserved']));try{$result=$existing===null?$this->tasks->createAutonomyTask($u,['title'=>$this->title($proposal),'objective'=>$proposal->proposedObjective,'session_id'=>(int)$scope['session_id_'],'project_id'=>$p,'parent_task_id'=>(int)$scope['source_task_id'],'mode'=>$policy->mode==='automatic'?'automatic':'supervised','idempotency_key'=>$this->taskKey($proposal)]):['task'=>$existing];$task=$result['task'];if($reservation->reservationPublicId!==null)$this->budgets->consume($u,$p,$reservation->reservationPublicId);$current=$this->proposals->findOwned($u,$proposal->publicId)??throw new RuntimeException('proposal_missing');if($current['status']===NextWorkProposal::SPAWNED)return NextWorkProposal::fromRow($current);return NextWorkProposal::fromRow($this->proposals->transition($u,$proposal->publicId,(int)$current['lock_version'],[NextWorkProposal::SPAWNING,NextWorkProposal::AUTHORIZED,NextWorkProposal::FAILED],NextWorkProposal::SPAWNED,['spawned_task_id_'=>$this->proposals->taskId($u,$p,(string)$task['public_id']),'spawned_at'=>gmdate('Y-m-d H:i:s.u'),'authorization_reason'=>'spawned']));}catch(Throwable$e){if($this->findTask($u,$p,$scope,$proposal)===null&&$reservation->reservationPublicId!==null)$this->budgets->release($u,$p,$reservation->reservationPublicId);throw$e;}}
 private function findTask(int$u,int$p,array$scope,NextWorkProposal$proposal):?array{return$this->tasks->findAutonomyTask($u,$this->taskKey($proposal),$p,(int)$scope['source_task_id'],$proposal->proposedObjective);}
 private function fromAuthorization(AutonomyAuthorizationDecision$a):AutonomyBudgetReservation{return new AutonomyBudgetReservation($a->status===AutonomyAuthorizationDecision::ALLOWED,$a->reasonCode,$a->reservationPublicId,false,[],$a->remaining);}
 private function deny(int$u,NextWorkProposal$p,string$reason):NextWorkProposal{return NextWorkProposal::fromRow($this->proposals->transition($u,$p->publicId,$p->lockVersion,[NextWorkProposal::AUTHORIZED,NextWorkProposal::SPAWNING,NextWorkProposal::FAILED],NextWorkProposal::FAILED,['authorization_reason'=>$reason]));}
 private function scope(int$u,int$p,string$t,string$c):array{$s=$this->proposals->resolveScope($u,$p,$t,$c);$s['user_id']=$u;$s['project_id']=$p;return$s;}
 private function payload(NextWorkDecision$d):string{return json_encode($d->toArray(),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
 private function taskKey(NextWorkProposal$p):string{return'autonomy:'.$p->publicId;}
 private function title(NextWorkProposal$p):string{$t=trim((string)$p->proposedTitle);if($t==='')$t='Continuar: '.mb_substr($p->proposedObjective,0,220);return mb_substr($t,0,255);}
}
