<?php
declare(strict_types=1);
final class PostTaskContinuationService{
 public const MAX_ATTEMPTS=3;
 public function __construct(private PostTaskContinuationStoreInterface$store,private AutonomyPolicyService$policies,private AutonomyBudgetService$budgets,private NextWorkEvaluator$evaluator,private NextWorkProposalService$proposals,private int$maxPerTick=3){if($maxPerTick<1||$maxPerTick>20)throw new InvalidArgumentException('continuation_batch_invalid');}
 public function enrollRoot(int$u,int$p,string$task,string$cycle):array{return$this->store->enrollRoot($u,$p,$task,$cycle);}
 public function processTick(string$worker,int$lease):int{$this->store->discover($this->maxPerTick);$done=0;for($i=0;$i<$this->maxPerTick;$i++){$claim=$this->store->claim($worker,$lease,self::MAX_ATTEMPTS);if(!$claim)break;$this->process($claim);$done++;}return$done;}
 private function process(array$c):void{$decisionReservation=null;$modelCalled=false;try{$this->store->event($c,'continuation_started','Evaluación post-Task iniciada.');$policy=$this->policies->getOrCreate((int)$c['user_id_'],(int)$c['project_id_']);if($policy->mode==='disabled'||$policy->status!=='active'){$reason=$policy->mode==='disabled'?'autonomy_disabled':'autonomy_'.$policy->status;$this->terminal($c,'failed','ask_user',$reason,'La autonomía no permite continuar.');if($policy->status==='stopped')$this->store->closeCycle((int)$c['user_id_'],(int)$c['project_id_'],(string)$c['cycle_public_id'],'stopped');return;}if((int)$c['depth']>=$policy->limits['max_descendant_depth']){$this->terminal($c,'failed','stop','depth_limit_reached','Se alcanzó la profundidad máxima del ciclo.');$this->store->closeCycle((int)$c['user_id_'],(int)$c['project_id_'],(string)$c['cycle_public_id'],'exhausted');return;}
  $decisionReservation=$this->budgets->reserve((int)$c['user_id_'],(int)$c['project_id_'],(string)$c['cycle_public_id'],'continuation-decision:'.$c['public_id'],new AutonomyBudgetRequest(decisions:1,descendantDepth:(int)$c['depth']));if(!$decisionReservation->allowed){$this->terminal($c,'failed','stop',$decisionReservation->reasonCode,'El presupuesto no permite otra evaluación.');if(str_ends_with($decisionReservation->reasonCode,'limit_reached'))$this->store->closeCycle((int)$c['user_id_'],(int)$c['project_id_'],(string)$c['cycle_public_id'],'exhausted');return;}
  $evaluation=$this->storedEvaluation($c)??$this->evaluator->evaluateWithUsage((int)$c['user_id_'],(int)$c['project_id_'],(string)$c['source_task_public_id']);$modelCalled=$evaluation->modelCalled;if($modelCalled)$this->budgets->consume((int)$c['user_id_'],(int)$c['project_id_'],(string)$decisionReservation->reservationPublicId);else$this->budgets->release((int)$c['user_id_'],(int)$c['project_id_'],(string)$decisionReservation->reservationPublicId);if($evaluation->failureCode!==null){if($modelCalled)throw new RuntimeException($evaluation->failureCode);$this->store->finish($c,'waiting_user','ask_user',$evaluation->failureCode,$evaluation->decision->publicReason,$evaluation->decision->question);return;}if($c['decision_json']===null)$this->store->recordEvaluation($c,$evaluation);
  if($evaluation->inputTokens()+$evaluation->outputTokens()>0){$usage=$this->budgets->reserve((int)$c['user_id_'],(int)$c['project_id_'],(string)$c['cycle_public_id'],'continuation-usage:'.$c['public_id'],new AutonomyBudgetRequest(inputTokens:$evaluation->inputTokens(),outputTokens:$evaluation->outputTokens(),descendantDepth:(int)$c['depth']));if(!$usage->allowed){$this->terminal($c,'failed',$evaluation->decision->decision,$usage->reasonCode,'El uso del modelo agotó el presupuesto del ciclo.');$this->store->closeCycle((int)$c['user_id_'],(int)$c['project_id_'],(string)$c['cycle_public_id'],'exhausted');return;}$this->budgets->consume((int)$c['user_id_'],(int)$c['project_id_'],(string)$usage->reservationPublicId);}
  $d=$evaluation->decision;if($d->decision===NextWorkDecision::STOP){$this->terminal($c,'completed','stop','model_stop',$d->publicReason);$this->store->closeCycle((int)$c['user_id_'],(int)$c['project_id_'],(string)$c['cycle_public_id'],'closed');return;}if($d->decision===NextWorkDecision::ASK_USER){$this->store->finish($c,'waiting_user','ask_user','user_input_required',$d->publicReason,$d->question);$this->store->event($c,'continuation_waiting_user','Continuidad esperando una decisión del usuario.');return;}$proposal=$this->proposals->propose((int)$c['user_id_'],(int)$c['project_id_'],(string)$c['source_task_public_id'],(string)$c['cycle_public_id'],$d,true);if(!$proposal)throw new RuntimeException('continuation_proposal_missing');$status=$proposal->status===NextWorkProposal::PENDING?'waiting_approval':($proposal->status===NextWorkProposal::SPAWNED?'completed':'failed');$reason=$proposal->status===NextWorkProposal::PENDING?'approval_required':$proposal->authorizationReason;$this->store->finish($c,$status,'propose_task',$reason,$d->publicReason,null,$proposal->publicId,$proposal->spawnedTaskPublicId);$this->store->event($c,$status==='waiting_approval'?'continuation_waiting_approval':($status==='completed'?'continuation_task_spawned':'continuation_failed'),$status==='completed'?'La siguiente Task fue creada.':'La propuesta quedó detenida.');
 }catch(TaskValidationException|TaskNotFoundException|TaskTransitionException$e){$this->terminal($c,'failed','ask_user','invalid_scope','La continuidad dejó de ser válida.');}catch(Throwable$e){if($decisionReservation?->reservationPublicId!==null&&!$modelCalled)try{$this->budgets->release((int)$c['user_id_'],(int)$c['project_id_'],$decisionReservation->reservationPublicId);}catch(Throwable){}$this->store->retry($c,'continuation_transient_failure',self::MAX_ATTEMPTS);if((int)$c['attempt_count']>=self::MAX_ATTEMPTS)$this->store->closeCycle((int)$c['user_id_'],(int)$c['project_id_'],(string)$c['cycle_public_id'],'stopped');$this->store->event($c,(int)$c['attempt_count']>=self::MAX_ATTEMPTS?'continuation_failed':'continuation_retried','La continuidad falló de forma controlada.');}}
 private function terminal(array$c,string$status,string$decision,string$reason,string$public):void{$this->store->finish($c,$status,$decision,$reason,mb_substr($public,0,800));$this->store->event($c,$status==='completed'?'continuation_stopped':'continuation_failed',$public);}
 private function storedEvaluation(array$c):?NextWorkEvaluationResult{if(empty($c['decision_json']))return null;$d=json_decode((string)$c['decision_json'],true);$u=json_decode((string)($c['usage_json']??'[]'),true);if(!is_array($d))return null;return new NextWorkEvaluationResult(new NextWorkDecision((string)$d['decision'],(string)$d['public_reason'],is_array($d['evidence']??null)?$d['evidence']:[],$d['question']??null,$d['proposed_title']??null,$d['proposed_objective']??null),is_array($u)?$u:[],true);}
}
