<?php
declare(strict_types=1);
final class TaskDependencyRepository{
 public function __construct(private mysqli$db){}
 public function add(int$task,int$required,string$condition):void{$s=$this->p('INSERT INTO TaskDependencies(task_id_,depends_on_task_id_,`condition`) VALUES(?,?,?)');$s->bind_param('iis',$task,$required,$condition);if(!$s->execute()){if($s->errno===1062)throw new TaskValidationException('dependency_duplicate');throw new RuntimeException('database_error');}$s->close();}
 public function remove(int$task,int$required):bool{$s=$this->p('DELETE FROM TaskDependencies WHERE task_id_=? AND depends_on_task_id_=?');$s->bind_param('ii',$task,$required);$this->x($s);$ok=$s->affected_rows===1;$s->close();return$ok;}
 public function exists(int$task,int$required):bool{return$this->one('SELECT 1 FROM TaskDependencies WHERE task_id_=? AND depends_on_task_id_=?','ii',[$task,$required])!==null;}
 public function pathExists(int$from,int$target):bool{$s=$this->p('WITH RECURSIVE graph(id_) AS (SELECT depends_on_task_id_ FROM TaskDependencies WHERE task_id_=? UNION DISTINCT SELECT d.depends_on_task_id_ FROM TaskDependencies d JOIN graph g ON d.task_id_=g.id_) SELECT 1 FROM graph WHERE id_=? LIMIT 1');$s->bind_param('ii',$from,$target);$this->x($s);$found=(bool)$s->get_result()->fetch_assoc();$s->close();return$found;}
 public function listForEvaluation(int$task):array{$s=$this->p('SELECT d.condition,required.status FROM TaskDependencies d JOIN Tasks required ON required.id_=d.depends_on_task_id_ WHERE d.task_id_=?');$s->bind_param('i',$task);$this->x($s);$o=[];$r=$s->get_result();while($x=$r->fetch_assoc())$o[]=$x;$s->close();return$o;}
 public function listDependents(int$required):array{$s=$this->p('SELECT task_id_ FROM TaskDependencies WHERE depends_on_task_id_=?');$s->bind_param('i',$required);$this->x($s);$o=[];$r=$s->get_result();while($x=$r->fetch_assoc())$o[]=(int)$x['task_id_'];$s->close();return$o;}
 public function listOwned(int$task,int$u):array{$s=$this->p('SELECT d.condition,required.public_id depends_on_public_id,required.title depends_on_title,required.status depends_on_status FROM TaskDependencies d JOIN Tasks owner ON owner.id_=d.task_id_ JOIN Tasks required ON required.id_=d.depends_on_task_id_ WHERE d.task_id_=? AND owner.user_id_=? AND required.user_id_=? ORDER BY d.id_');$s->bind_param('iii',$task,$u,$u);$this->x($s);$o=[];$r=$s->get_result();while($x=$r->fetch_assoc())$o[]=$x;$s->close();return$o;}
 private function one(string$q,string$t,array$v):?array{$s=$this->p($q);$s->bind_param($t,...$v);$this->x($s);$r=$s->get_result()->fetch_assoc();$s->close();return$r?:null;}private function p(string$q):mysqli_stmt{$s=$this->db->prepare($q);if(!$s)throw new RuntimeException('database_error');return$s;}private function x(mysqli_stmt$s):void{if(!$s->execute())throw new RuntimeException('database_error');}
}
