<?php
declare(strict_types=1);

final class TaskReplanService
{
    public const MAX_ATTEMPTS=3;
    public function __construct(private TaskReplanRepository$repo,private TaskPlanningService$planning,private AutonomyPolicyService$policies,private AutonomyBudgetService$budgets,private int$maxPerTick=2){if($maxPerTick<1||$maxPerTick>10)throw new InvalidArgumentException('replan_batch_invalid');}
    public function processTick(string$worker,int$lease):int{$done=0;for($i=0;$i<$this->maxPerTick;$i++){$claim=$this->repo->claim($worker,$lease,self::MAX_ATTEMPTS);if(!$claim)break;$this->process($claim);$done++;}return$done;}
    public function approveReplan(int$u,string$public,int$lock):TaskPlanRevision{return TaskPlanRevision::fromRow($this->repo->approve($u,$public,$lock));}
    public function rejectReplan(int$u,string$public,int$lock):array{return$this->repo->reject($u,$public,$lock);}
    private function process(array$c):void{$reservation=null;try{if((string)$c['status']==='approved'){$this->repo->apply((int)$c['user_id_'],(string)$c['public_id']);return;}$policy=$this->policies->getOrCreate((int)$c['user_id_'],(int)$c['project_id_']);if($policy->mode==='disabled'||$policy->status!=='active')throw new TaskTransitionException('autonomy_not_active');$reservation=$this->budgets->reserve((int)$c['user_id_'],(int)$c['project_id_'],(string)$c['cycle_public_id'],'replan:'.(string)$c['public_id'],new AutonomyBudgetRequest(replans:1));if(!$reservation->allowed){$this->repo->failClaim($c,$reservation->reasonCode,false,self::MAX_ATTEMPTS);return;}$reservationId=$this->repo->reservationId((int)$c['user_id_'],(int)$c['project_id_'],(string)$reservation->reservationPublicId);$this->repo->attachReservation($c,$reservationId);$this->budgets->consume((int)$c['user_id_'],(int)$c['project_id_'],(string)$reservation->reservationPublicId);$snapshot=$this->repo->snapshot($c);$result=$this->planning->planRemaining($c,$snapshot);if($result->inputTokens()+$result->outputTokens()>0){$usage=$this->budgets->reserve((int)$c['user_id_'],(int)$c['project_id_'],(string)$c['cycle_public_id'],'replan-usage:'.(string)$c['public_id'],new AutonomyBudgetRequest(inputTokens:$result->inputTokens(),outputTokens:$result->outputTokens()));if(!$usage->allowed){$this->repo->failClaim($c,$usage->reasonCode,false,self::MAX_ATTEMPTS);return;}$this->budgets->consume((int)$c['user_id_'],(int)$c['project_id_'],(string)$usage->reservationPublicId);}$revision=$this->repo->propose($c,$result);if((string)$c['autonomy_mode']==='automatic'&&(string)$c['task_mode']==='automatic')$this->repo->apply((int)$c['user_id_'],(string)$c['public_id']);}catch(TaskValidationException|TaskNotFoundException|TaskTransitionException|TaskConcurrencyException$e){$this->repo->failClaim($c,$e->getMessage()?:'replan_permanent_failure',false,self::MAX_ATTEMPTS);}catch(Throwable$e){$this->repo->failClaim($c,'replan_transient_failure',true,self::MAX_ATTEMPTS);}}
}
