<?php
declare(strict_types=1);
final class TaskDependencyService{
 private const CONDITIONS=['completed','terminal_success','terminal_any'];
 public function __construct(private TaskRepository$tasks,private TaskDependencyRepository$dependencies,private TaskOrchestrator$orchestrator){}
 public function add(int$user,string$taskPublic,string$requiredPublic,string$condition='completed'):void{$task=$this->owned($taskPublic,$user);$required=$this->owned($requiredPublic,$user);if((int)$task['id_']===(int)$required['id_'])throw new TaskValidationException('dependency_self');if(!in_array($condition,self::CONDITIONS,true))throw new TaskValidationException('dependency_condition_invalid');if(($task['project_id_']??null)!==($required['project_id_']??null))throw new TaskValidationException('dependency_scope_invalid');if($this->dependencies->exists((int)$task['id_'],(int)$required['id_']))throw new TaskValidationException('dependency_duplicate');if($this->dependencies->pathExists((int)$required['id_'],(int)$task['id_']))throw new TaskValidationException('dependency_cycle');$this->dependencies->add((int)$task['id_'],(int)$required['id_'],$condition);}
 public function remove(int$user,string$taskPublic,string$requiredPublic):void{$task=$this->owned($taskPublic,$user);$required=$this->owned($requiredPublic,$user);if(!$this->dependencies->remove((int)$task['id_'],(int)$required['id_']))throw new TaskNotFoundException('not_found');}
 public function gateAuthorized(array$task,int$user):array{if(in_array($task['status'],['completed','failed','cancelled'],true))return$task;$satisfied=$this->satisfied((int)$task['id_']);if(!$satisfied&&$task['status']==='ready')return$this->orchestrator->transitionTask((int)$task['id_'],$user,'waiting_dependency',(int)$task['lock_version'],'system',['event_summary'=>'Dependencias pendientes.']);if($satisfied&&$task['status']==='waiting_dependency')return$this->orchestrator->transitionTask((int)$task['id_'],$user,'ready',(int)$task['lock_version'],'system',['event_summary'=>'Dependencias satisfechas.']);return$task;}
 public function satisfied(int$taskId):bool{foreach($this->dependencies->listForEvaluation($taskId)as$d){$status=$d['status'];$ok=$d['condition']==='terminal_any'?in_array($status,['completed','failed','cancelled'],true):$status==='completed';if(!$ok)return false;}return true;}
 private function owned(string$public,int$user):array{return$this->tasks->findOwnedByPublicId($public,$user)??throw new TaskNotFoundException('not_found');}
}
