<?php
declare(strict_types=1);
/** All queue, lease and recovery SQL is deliberately isolated here. */
final class TaskQueueRepository{
 private TaskClaimAttemptBudget$attemptBudget;
 public function __construct(private mysqli$db,?TaskClaimAttemptBudget$attemptBudget=null){$this->attemptBudget=$attemptBudget??new TaskClaimAttemptBudget();} public function begin():void{$this->db->begin_transaction();}public function commit():void{$this->db->commit();}public function rollback():void{$this->db->rollback();}
 public function lockNextAsyncRespond():?array{$sql="SELECT t.*,s.id_ step_id,s.step_key,s.status step_status,s.step_type,s.agent_key,s.lock_version step_lock,s.input_json,s.checkpoint_json,s.model_id step_model FROM Tasks t JOIN TaskSteps s ON s.task_id_=t.id_ WHERE t.status IN ('ready','running') AND s.status='ready' AND (t.current_step_id_=s.id_ OR (t.current_step_id_ IS NULL AND s.position=(SELECT MIN(s2.position) FROM TaskSteps s2 WHERE s2.task_id_=t.id_ AND s2.status='ready'))) AND COALESCE(t.scheduled_at,UTC_TIMESTAMP(6))<=UTC_TIMESTAMP(6) AND JSON_UNQUOTE(JSON_EXTRACT(s.input_json,'$.execution_mode'))='async' AND NOT EXISTS(SELECT 1 FROM TaskExecutions e WHERE e.task_id_=t.id_ AND e.status IN ('queued','running','waiting')) ORDER BY CASE t.priority WHEN 'urgent' THEN 1 WHEN 'high' THEN 2 WHEN 'normal' THEN 3 ELSE 4 END,COALESCE(t.scheduled_at,t.created_at),t.created_at,t.id_ LIMIT 1 FOR UPDATE SKIP LOCKED";$r=$this->db->query($sql);if(!$r)throw new RuntimeException('queue_select_failed');return$r->fetch_assoc()?:null;}
 public function dependenciesSatisfied(int$id):bool{$s=$this->p("SELECT COUNT(*) c FROM TaskDependencies d JOIN Tasks r ON r.id_=d.depends_on_task_id_ WHERE d.task_id_=? AND NOT(CASE d.condition WHEN 'terminal_any' THEN r.status IN ('completed','failed','cancelled') ELSE r.status='completed' END)");$s->bind_param('i',$id);$this->x($s);$ok=(int)$s->get_result()->fetch_assoc()['c']===0;$s->close();return$ok;}
 public function createClaim(array$t,string$worker,string$token,int$lease,string$trace):array{$step=(int)$t['step_id'];$task=(int)$t['id_'];$s=$this->p('SELECT id_,task_id_,step_id_,status,attempt_number FROM TaskExecutions WHERE step_id_=? ORDER BY attempt_number,id_');$s->bind_param('i',$step);$this->x($s);$history=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();$attempt=$this->attemptBudget->nextAttemptNumber($task,$step,(int)$t['max_attempts'],$history,$t['checkpoint_json']===null?null:(string)$t['checkpoint_json']);$input=json_decode((string)$t['input_json'],true)?:[];$model=(string)($input['model_id']??$t['step_model']??'');$s=$this->p("INSERT INTO TaskExecutions(task_id_,step_id_,trace_id,attempt_number,agent_key,model_id,status,worker_id,lease_token,lease_expires_at,started_at,heartbeat_at) VALUES(?,?,?,?,?,?,'running',?,?,DATE_ADD(NOW(6),INTERVAL ? SECOND),NOW(6),NOW(6))");$agent=(string)$t['agent_key'];$s->bind_param('iisissssi',$task,$step,$trace,$attempt,$agent,$model,$worker,$token,$lease);$this->x($s);$execution=(int)$this->db->insert_id;$s->close();$s=$this->p("UPDATE Tasks SET status='running',started_at=COALESCE(started_at,NOW(6)),last_heartbeat_at=NOW(6),current_step_id_=?,attempt_count=?,lock_version=lock_version+1 WHERE id_=? AND status IN ('ready','running')");$s->bind_param('iii',$step,$attempt,$task);$this->x($s);if($s->affected_rows!==1)throw new TaskConcurrencyException('claim_lost');$s->close();$s=$this->p("UPDATE TaskSteps SET status='running',started_at=COALESCE(started_at,NOW(6)),attempt_count=?,lock_version=lock_version+1 WHERE id_=? AND status='ready'");$s->bind_param('ii',$attempt,$step);$this->x($s);if($s->affected_rows!==1)throw new TaskConcurrencyException('claim_lost');$s->close();$this->event($task,$step,$execution,'execution_started','ready','running','Worker reclamó la ejecución.');return['execution_id'=>$execution,'task_id'=>$task,'step_id'=>$step,'step_type'=>(string)$t['step_type'],'agent_key'=>(string)$t['agent_key'],'user_id'=>(int)$t['user_id_'],'session_id'=>(int)$t['session_id_'],'project_id'=>isset($t['project_id_'])?(int)$t['project_id_']:null,'origin_message_id'=>(int)$t['origin_message_id_'],'objective'=>(string)$t['objective'],'origin_type'=>(string)$t['origin_type'],'step_key'=>(string)$t['step_key'],'persist_final_response'=>$this->shouldPersistFinalResponse($t),'trace_id'=>$trace,'attempt_number'=>$attempt,'worker_id'=>$worker,'lease_token'=>$token,'input'=>$input];}
 public function heartbeat(int$e,string$w,string$t,int$l):bool{$s=$this->p("UPDATE TaskExecutions e JOIN Tasks t ON t.id_=e.task_id_ SET e.heartbeat_at=NOW(6),e.lease_expires_at=DATE_ADD(NOW(6),INTERVAL ? SECOND),t.last_heartbeat_at=NOW(6) WHERE e.id_=? AND e.worker_id=? AND e.lease_token=? AND e.status='running'");$s->bind_param('iiss',$l,$e,$w,$t);$this->x($s);$affected=$s->affected_rows;$s->close();if($affected>0)return true;return $this->ownedRunning($e,$w,$t)!==null;}
 public function ownedRunning(int$e,string$w,string$token):?array{$s=$this->p("SELECT e.*,t.status task_status,t.cancel_requested_at FROM TaskExecutions e JOIN Tasks t ON t.id_=e.task_id_ WHERE e.id_=? AND e.worker_id=? AND e.lease_token=? AND e.status='running' AND e.lease_expires_at>=NOW(6)");$s->bind_param('iss',$e,$w,$token);$this->x($s);$r=$s->get_result()->fetch_assoc();$s->close();return$r?:null;}
 public function finish(array$c,string$status,?int$message,?string$summary,?string$error,?array$checkpoint=null,?TaskFailureDisposition$disposition=null,?string$effectiveModelId=null):bool{
  $atomic=$status==='failed'&&$disposition?->isReplanCandidate();if($atomic)$this->begin();try{
  $o=$this->ownedRunning($c['execution_id'],$c['worker_id'],$c['lease_token']);if(!$o){if($atomic)$this->rollback();return false;}
  $executionStatus=in_array($status,['completed','failed','cancelled'],true)?$status:(str_starts_with($status,'waiting_')?'waiting':'failed');
  $s=$this->p("UPDATE TaskExecutions SET status=?,finished_at=IF(?='waiting',NULL,NOW(6)),error_message=?,model_id=COALESCE(NULLIF(?,''),model_id),lease_expires_at=NULL WHERE id_=? AND worker_id=? AND lease_token=? AND status='running'");$s->bind_param('ssssiss',$executionStatus,$executionStatus,$error,$effectiveModelId,$c['execution_id'],$c['worker_id'],$c['lease_token']);$this->x($s);if($s->affected_rows!==1){$s->close();if($atomic)$this->rollback();return false;}$s->close();
  $stepStatus=$executionStatus==='waiting'?($status==='waiting_dependency'?'waiting_dependency':'waiting_user'):$executionStatus;
  $checkpointJson=$checkpoint===null?null:json_encode($checkpoint,JSON_UNESCAPED_SLASHES);$s=$this->p("UPDATE TaskSteps SET status=?,completed_at=IF(?='completed',NOW(6),completed_at),progress_percent=IF(?='completed',100,progress_percent),output_summary=COALESCE(?,output_summary),checkpoint_json=COALESCE(?,checkpoint_json),error_message=?,lock_version=lock_version+1 WHERE id_=? AND status='running'");$s->bind_param('ssssssi',$stepStatus,$stepStatus,$stepStatus,$summary,$checkpointJson,$error,$c['step_id']);$this->x($s);$s->close();
  if($executionStatus==='completed'){
   $s=$this->p("SELECT id_ FROM TaskSteps WHERE task_id_=? AND status IN ('pending','ready') ORDER BY position,id_ LIMIT 1");$s->bind_param('i',$c['task_id']);$this->x($s);$next=$s->get_result()->fetch_assoc();$s->close();
   $s=$this->p("SELECT COUNT(*) total,SUM(status IN ('completed','skipped')) done FROM TaskSteps WHERE task_id_=?");$s->bind_param('i',$c['task_id']);$this->x($s);$counts=$s->get_result()->fetch_assoc();$s->close();$progress=(int)floor(100*((int)$counts['done']/max(1,(int)$counts['total'])));
   if($next){$nextId=(int)$next['id_'];$s=$this->p("UPDATE TaskSteps SET status='ready',lock_version=lock_version+1 WHERE id_=? AND status='pending'");$s->bind_param('i',$nextId);$this->x($s);$s->close();$s=$this->p("UPDATE Tasks SET status='running',current_step_id_=?,progress_percent=?,result_message_id_=COALESCE(?,result_message_id_),result_summary=COALESCE(?,result_summary),lock_version=lock_version+1 WHERE id_=? AND status='running'");$s->bind_param('iiisi',$nextId,$progress,$message,$summary,$c['task_id']);}
   else{$s=$this->p("UPDATE Tasks SET status='completed',current_step_id_=NULL,progress_percent=100,result_message_id_=COALESCE(?,result_message_id_),result_summary=COALESCE(?,result_summary),completed_at=NOW(6),lock_version=lock_version+1 WHERE id_=? AND status='running'");$s->bind_param('isi',$message,$summary,$c['task_id']);}
  }else{$taskStatus=$stepStatus;$s=$this->p("UPDATE Tasks SET status=?,error_code=IF(?='failed','chat_pipeline_failed',error_code),error_message=?,current_step_id_=?,lock_version=lock_version+1 WHERE id_=? AND status='running'");$s->bind_param('sssii',$taskStatus,$taskStatus,$error,$c['step_id'],$c['task_id']);}
  $this->x($s);$ok=$s->affected_rows===1;$s->close();if(!$ok){if($atomic)$this->rollback();return false;}$this->event($c['task_id'],$c['step_id'],$c['execution_id'],'execution_'.$executionStatus,'running',$stepStatus,'Ejecución '.$executionStatus.'.');if($atomic)$this->createReplanCheckpoint($c,$disposition);if($atomic)$this->commit();return$ok;}catch(Throwable$e){if($atomic)$this->rollback();throw$e;}
 } public function reactivateDueWaits(int $limit):int{
  $this->begin();try{$s=$this->p("SELECT s.id_,s.task_id_ FROM TaskSteps s JOIN Tasks t ON t.id_=s.task_id_ WHERE s.step_type='wait' AND s.status='waiting_dependency' AND t.status='waiting_dependency' AND JSON_UNQUOTE(JSON_EXTRACT(s.checkpoint_json,'$.wait_until'))<=DATE_FORMAT(UTC_TIMESTAMP(6),'%Y-%m-%d %H:%i:%s.%f') ORDER BY s.updated_at,s.id_ LIMIT ? FOR UPDATE SKIP LOCKED");$s->bind_param('i',$limit);$this->x($s);$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();$count=0;foreach($rows as$row){$step=(int)$row['id_'];$task=(int)$row['task_id_'];$s=$this->p("UPDATE TaskExecutions SET status='completed',finished_at=NOW(6) WHERE step_id_=? AND status='waiting'");$s->bind_param('i',$step);$this->x($s);$s->close();$s=$this->p("UPDATE TaskSteps SET status='completed',progress_percent=100,completed_at=NOW(6),output_summary='Wait condition reached.',lock_version=lock_version+1 WHERE id_=? AND status='waiting_dependency'");$s->bind_param('i',$step);$this->x($s);$won=$s->affected_rows===1;$s->close();if(!$won)continue;$s=$this->p("SELECT id_ FROM TaskSteps WHERE task_id_=? AND status IN ('pending','ready') ORDER BY position,id_ LIMIT 1");$s->bind_param('i',$task);$this->x($s);$next=$s->get_result()->fetch_assoc();$s->close();$s=$this->p("SELECT COUNT(*) total,SUM(status IN ('completed','skipped')) done FROM TaskSteps WHERE task_id_=?");$s->bind_param('i',$task);$this->x($s);$counts=$s->get_result()->fetch_assoc();$s->close();$progress=(int)floor(100*((int)$counts['done']/max(1,(int)$counts['total'])));if($next){$nextId=(int)$next['id_'];$s=$this->p("UPDATE TaskSteps SET status='ready',lock_version=lock_version+1 WHERE id_=? AND status='pending'");$s->bind_param('i',$nextId);$this->x($s);$s->close();$s=$this->p("UPDATE Tasks SET status='ready',current_step_id_=?,progress_percent=?,lock_version=lock_version+1 WHERE id_=? AND status='waiting_dependency'");$s->bind_param('iii',$nextId,$progress,$task);}else{$s=$this->p("UPDATE Tasks SET status='completed',current_step_id_=NULL,progress_percent=100,completed_at=NOW(6),lock_version=lock_version+1 WHERE id_=? AND status='waiting_dependency'");$s->bind_param('i',$task);}$this->x($s);$won=$s->affected_rows===1;$s->close();if($won)$count++;}$this->commit();return$count;}catch(Throwable$e){$this->rollback();throw$e;}
 }
 public function expired(int$limit):array{$s=$this->p("SELECT e.id_,e.task_id_,e.step_id_,e.trace_id FROM TaskExecutions e JOIN TaskSteps s ON s.id_=e.step_id_ JOIN Tasks t ON t.id_=e.task_id_ WHERE e.status='running' AND e.lease_expires_at<NOW(6) AND (COALESCE(e.worker_id,'')<>'http-sync' OR JSON_UNQUOTE(JSON_EXTRACT(s.checkpoint_json,'$.tool_approval.decision.consumed'))='true' OR t.status='cancelled') ORDER BY e.lease_expires_at LIMIT ? FOR UPDATE SKIP LOCKED");$s->bind_param('i',$limit);$this->x($s);$r=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return$r;}
 public function abandon(array$e):void{$s=$this->p("UPDATE TaskExecutions SET status='abandoned',finished_at=NOW(6),error_message='Worker lease expired' WHERE id_=? AND status='running' AND lease_expires_at<NOW(6)");$s->bind_param('i',$e['id_']);$this->x($s);$won=$s->affected_rows===1;$s->close();if(!$won)return;$s=$this->p("UPDATE TaskSteps SET status='failed',error_message='Worker lease expired',lock_version=lock_version+1 WHERE id_=? AND status='running'");$s->bind_param('i',$e['step_id_']);$this->x($s);$s->close();$s=$this->p("UPDATE Tasks SET status='failed',error_code='execution_abandoned',error_message='Worker lease expired',lock_version=lock_version+1 WHERE id_=? AND status='running'");$s->bind_param('i',$e['task_id_']);$this->x($s);$s->close();$this->event((int)$e['task_id_'],(int)$e['step_id_'],(int)$e['id_'],'execution_abandoned','running','abandoned','Lease expirado; se requiere retry manual.');}
 private function shouldPersistFinalResponse(array$t):bool{
  $origin=(string)($t['origin_type']??'');if(!in_array($origin,['chat','manual'],true)||(string)($t['step_type']??'')!=='model')return false;
  $taskId=(int)($t['id_']??0);$stepId=(int)($t['step_id']??0);if($taskId<1||$stepId<1)return false;
  $s=$this->p("SELECT 1 FROM TaskSteps later JOIN TaskSteps current ON current.id_=? AND current.task_id_=? WHERE later.task_id_=? AND later.position>current.position AND later.step_type='model' AND later.status NOT IN ('cancelled','skipped') LIMIT 1");$s->bind_param('iii',$stepId,$taskId,$taskId);$this->x($s);$hasLater=(bool)$s->get_result()->fetch_assoc();$s->close();
  return!$hasLater;
 }
 private function createReplanCheckpoint(array$c,TaskFailureDisposition$d):void{$s=$this->p("SELECT t.user_id_,t.project_id_,t.lock_version,x.cycle_id_ FROM Tasks t JOIN (SELECT cycle_id_ FROM ProjectAutonomyCycleTasks WHERE task_id_=? UNION SELECT autonomy_cycle_id_ FROM NextWorkProposals WHERE spawned_task_id_=?) x ON 1=1 JOIN ProjectAutonomyCycles ac ON ac.id_=x.cycle_id_ AND ac.status='active' WHERE t.id_=? AND t.status='failed' LIMIT 1 FOR UPDATE");$s->bind_param('iii',$c['task_id'],$c['task_id'],$c['task_id']);$this->x($s);$scope=$s->get_result()->fetch_assoc();$s->close();if(!$scope)return;$public=TaskPublicId::generate();$s=$this->p("INSERT INTO TaskReplanRequests(public_id,user_id_,project_id_,task_id_,autonomy_cycle_id_,source_step_id_,trigger_code,source_task_lock_version,public_reason,status) VALUES(?,?,?,?,?,?,?,?,?,'checkpointed') ON DUPLICATE KEY UPDATE id_=LAST_INSERT_ID(id_)");$s->bind_param('siiiiisis',$public,$scope['user_id_'],$scope['project_id_'],$c['task_id'],$scope['cycle_id_'],$c['step_id'],$d->triggerCode,$scope['lock_version'],$d->publicReason);$this->x($s);$s->close();$this->event($c['task_id'],$c['step_id'],$c['execution_id'],'replan_requested','failed','failed','Fallo lógico reservado para evaluación de replanning.');}
 private function event(int$t,int$s,int$e,string$k,string$f,string$to,string$summary):void{$q=$this->p("INSERT INTO TaskEvents(task_id_,step_id_,execution_id_,actor_type,event_key,from_status,to_status,summary) VALUES(?,?,?,'worker',?,?,?,?)");$q->bind_param('iiissss',$t,$s,$e,$k,$f,$to,$summary);$this->x($q);$q->close();}private function p(string$q):mysqli_stmt{$s=$this->db->prepare($q);if(!$s)throw new RuntimeException('database_error');return$s;}private function x(mysqli_stmt$s):void{if(!$s->execute())throw new RuntimeException('database_error');}
}
