<?php
declare(strict_types=1);
final class TaskRepository{
 public function __construct(private mysqli$db){}
 public function create(array$d):array{$q='INSERT INTO Tasks(public_id,user_id_,created_by_user_id_,project_id_,session_id_,origin_message_id_,idempotency_key,origin_type,title,objective,status,priority,max_attempts) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)';$s=$this->p($q);$project=$d['project_id']??null;$msg=$d['origin_message_id']??null;$key=$d['idempotency_key']??null;$s->bind_param('siiiiissssssi',$d['public_id'],$d['user_id'],$d['created_by_user_id'],$project,$d['session_id'],$msg,$key,$d['origin_type'],$d['title'],$d['objective'],$d['status'],$d['priority'],$d['max_attempts']);$this->x($s);$id=(int)$this->db->insert_id;$s->close();return$this->findById($id)??throw new RuntimeException('task_create_failed');}
 public function findById(int$id):?array{return$this->one('SELECT * FROM Tasks WHERE id_=?','i',[$id]);}
 public function findOwnedById(int$id,int$u):?array{return$this->one('SELECT * FROM Tasks WHERE id_=? AND user_id_=?','ii',[$id,$u]);}
 public function findOwnedByPublicId(string$p,int$u):?array{return$this->one('SELECT * FROM Tasks WHERE public_id=? AND user_id_=?','si',[$p,$u]);}
 public function findOwnedByIdempotencyKey(int$u,string$k):?array{return$this->one('SELECT * FROM Tasks WHERE user_id_=? AND idempotency_key=?','is',[$u,$k]);}
 public function assignResult(int$id,int$u,int$messageId,string$summary):void{$s=$this->p('UPDATE Tasks SET result_message_id_=?,result_summary=? WHERE id_=? AND user_id_=?');$s->bind_param('isii',$messageId,$summary,$id,$u);$this->x($s);$s->close();}
 public function sessionScope(int$session,int$u):?array{return$this->one('SELECT id_,project_id_ FROM ChatSessions WHERE id_=? AND user_id_=?','ii',[$session,$u]);}
 public function projectOwned(int$project,int$u):bool{return$this->one("SELECT id_ FROM Projects WHERE id_=? AND user_id_=? AND status<>'deleted'",'ii',[$project,$u])!==null;}
 public function messageOwned(int$msg,int$session,int$u):bool{return$this->one('SELECT id_ FROM ChatMessages WHERE id_=? AND session_id_=? AND user_id_=?','iii',[$msg,$session,$u])!==null;}
 public function listOwned(int$u,array$f,int$limit,int$offset):array{$sql='SELECT * FROM Tasks WHERE user_id_=?';$types='i';$v=[$u];foreach(['status'=>'s','project_id_'=>'i','session_id_'=>'i','priority'=>'s']as$k=>$t)if(array_key_exists($k,$f)){$sql.=" AND {$k}=?";$types.=$t;$v[]=$f[$k];}$sql.=' ORDER BY updated_at DESC,id_ DESC LIMIT ? OFFSET ?';$types.='ii';$v[]=$limit;$v[]=$offset;$s=$this->p($sql);$s->bind_param($types,...$v);$this->x($s);$out=[];$r=$s->get_result();while($row=$r->fetch_assoc())$out[]=$row;$s->close();return$out;}
 public function countOwned(int$u,array$f):int{$sql='SELECT COUNT(*) c FROM Tasks WHERE user_id_=?';$types='i';$v=[$u];foreach(['status'=>'s','project_id_'=>'i','session_id_'=>'i','priority'=>'s']as$k=>$t)if(array_key_exists($k,$f)){$sql.=" AND {$k}=?";$types.=$t;$v[]=$f[$k];}$s=$this->p($sql);$s->bind_param($types,...$v);$this->x($s);$c=(int)$s->get_result()->fetch_assoc()['c'];$s->close();return$c;}
 public function updateStatus(int$id,int$u,string$status,int$lock,array$fields=[]):array{$summary=$fields['result_summary']??null;$code=$fields['error_code']??null;$error=$fields['error_message']??null;$now=gmdate('Y-m-d H:i:s.u');$completed=$status==='completed'?$now:null;$cancelReq=$fields['cancel_requested_at']??null;$cancelled=$status==='cancelled'?$now:null;$s=$this->p("UPDATE Tasks SET status=?,completed_at=COALESCE(?,completed_at),cancel_requested_at=COALESCE(?,cancel_requested_at),cancelled_at=COALESCE(?,cancelled_at),result_summary=?,error_code=?,error_message=?,progress_percent=IF(?='completed',100,progress_percent),lock_version=lock_version+1 WHERE id_=? AND user_id_=? AND lock_version=?");$s->bind_param('ssssssssiii',$status,$completed,$cancelReq,$cancelled,$summary,$code,$error,$status,$id,$u,$lock);$this->x($s);$a=$s->affected_rows;$s->close();if($a!==1)throw new TaskConcurrencyException('concurrency_conflict');return$this->findOwnedById($id,$u)??throw new TaskNotFoundException('not_found');}
 public function retry(int$id,int$u,int$lock):array{$s=$this->p("UPDATE Tasks SET status='ready',attempt_count=attempt_count+1,error_code=NULL,error_message=NULL,completed_at=NULL,lock_version=lock_version+1 WHERE id_=? AND user_id_=? AND lock_version=? AND status='failed' AND attempt_count<max_attempts");$s->bind_param('iii',$id,$u,$lock);$this->x($s);$a=$s->affected_rows;$s->close();if($a!==1)throw new TaskConcurrencyException('retry_conflict');return$this->findOwnedById($id,$u)??throw new TaskNotFoundException('not_found');}
 private function one(string$q,string$t,array$v):?array{$s=$this->p($q.' LIMIT 1');$s->bind_param($t,...$v);$this->x($s);$r=$s->get_result()->fetch_assoc();$s->close();return$r?:null;}private function p(string$q):mysqli_stmt{$s=$this->db->prepare($q);if(!$s)throw new RuntimeException('database_error');return$s;}private function x(mysqli_stmt$s):void{if(!$s->execute())throw new RuntimeException('database_error');}
}
