<?php
declare(strict_types=1);
final class TaskRecurrenceRuleRepository{
 public function __construct(private mysqli$db){}
 public function create(array$d):array{$s=$this->p('INSERT INTO TaskRecurrenceRules(public_id,user_id_,project_id_,session_id_,status,frequency,weekday,local_time,timezone,next_occurrence_at,misfire_policy,task_title,task_objective,task_priority,task_mode) VALUES(?,?,?,?,\'enabled\',?,?,?,?,?,?,?,?,?,?)');$s->bind_param('siiisissssssss',$d['public_id'],$d['user_id'],$d['project_id'],$d['session_id'],$d['frequency'],$d['weekday'],$d['local_time'],$d['timezone'],$d['next_occurrence_at'],$d['misfire_policy'],$d['task_title'],$d['task_objective'],$d['task_priority'],$d['task_mode']);$this->x($s);$id=$this->db->insert_id;$s->close();return$this->findOwnedById((int)$id,(int)$d['user_id'])??throw new RuntimeException('recurrence_rule_create_failed');}
 public function listOwned(int$u,int$limit,int$offset):array{$s=$this->p('SELECT r.*,p.name project_name,s.title session_title FROM TaskRecurrenceRules r LEFT JOIN Projects p ON p.id_=r.project_id_ JOIN ChatSessions s ON s.id_=r.session_id_ WHERE r.user_id_=? ORDER BY r.updated_at DESC,r.id_ DESC LIMIT ? OFFSET ?');$s->bind_param('iii',$u,$limit,$offset);$this->x($s);$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return$rows;}
 public function countOwned(int$u):int{$s=$this->p('SELECT COUNT(*) total FROM TaskRecurrenceRules WHERE user_id_=?');$s->bind_param('i',$u);$this->x($s);$total=(int)$s->get_result()->fetch_assoc()['total'];$s->close();return$total;}
 public function findOwnedByPublicIdWithScope(string$p,int$u):?array{return$this->one('SELECT r.*,pr.name project_name,s.title session_title FROM TaskRecurrenceRules r LEFT JOIN Projects pr ON pr.id_=r.project_id_ JOIN ChatSessions s ON s.id_=r.session_id_ WHERE r.public_id=? AND r.user_id_=?','si',[$p,$u]);}
 public function findOwnedByPublicId(string$p,int$u):?array{return$this->one('SELECT * FROM TaskRecurrenceRules WHERE public_id=? AND user_id_=?','si',[$p,$u]);}
 public function findOwnedById(int$id,int$u):?array{return$this->one('SELECT * FROM TaskRecurrenceRules WHERE id_=? AND user_id_=?','ii',[$id,$u]);}
 public function lockNextDue(array$exclude=[]):?array{$sql="SELECT * FROM TaskRecurrenceRules WHERE status='enabled' AND next_occurrence_at<=UTC_TIMESTAMP(6)";$types='';$values=[];if($exclude!==[]){$sql.=' AND id_ NOT IN ('.implode(',',array_fill(0,count($exclude),'?')).')';$types=str_repeat('i',count($exclude));$values=array_values($exclude);}$sql.=' ORDER BY next_occurrence_at,id_ LIMIT 1 FOR UPDATE SKIP LOCKED';$s=$this->p($sql);if($types!=='')$s->bind_param($types,...$values);$this->x($s);$row=$s->get_result()->fetch_assoc();$s->close();return$row?:null;}
 public function lockOwned(int$id,int$u):?array{$s=$this->p('SELECT * FROM TaskRecurrenceRules WHERE id_=? AND user_id_=? FOR UPDATE');$s->bind_param('ii',$id,$u);$this->x($s);$r=$s->get_result()->fetch_assoc();$s->close();return$r?:null;}
 public function changeStatus(int$id,int$u,string$from,string$to,int$lock,?string$next=null):array{$sql='UPDATE TaskRecurrenceRules SET status=?,next_occurrence_at=COALESCE(?,next_occurrence_at),lock_version=lock_version+1 WHERE id_=? AND user_id_=? AND status=? AND lock_version=?';$s=$this->p($sql);$s->bind_param('ssiisi',$to,$next,$id,$u,$from,$lock);$this->x($s);$n=$s->affected_rows;$s->close();if($n!==1)throw new TaskConcurrencyException('recurrence_rule_conflict');return$this->findOwnedById($id,$u)??throw new TaskNotFoundException('not_found');}
 public function advance(int$id,int$u,string$next,int$lock):array{$s=$this->p("UPDATE TaskRecurrenceRules SET next_occurrence_at=?,lock_version=lock_version+1 WHERE id_=? AND user_id_=? AND status='enabled' AND lock_version=?");$s->bind_param('siii',$next,$id,$u,$lock);$this->x($s);$n=$s->affected_rows;$s->close();if($n!==1)throw new TaskConcurrencyException('recurrence_rule_conflict');return$this->findOwnedById($id,$u)??throw new TaskNotFoundException('not_found');}
 private function one(string$q,string$t,array$v):?array{$s=$this->p($q.' LIMIT 1');$s->bind_param($t,...$v);$this->x($s);$r=$s->get_result()->fetch_assoc();$s->close();return$r?:null;}private function p(string$q):mysqli_stmt{$s=$this->db->prepare($q);if(!$s)throw new RuntimeException('database_error');return$s;}private function x(mysqli_stmt$s):void{if(!$s->execute())throw new RuntimeException('database_error');}
}
