<?php
declare(strict_types=1);
final class TaskReplanCheckpointRepository implements TaskReplanCheckpointStoreInterface{
 public function __construct(private mysqli$db){}
 public function findOwned(int$u,string$public):?array{$s=$this->p("SELECT r.*,t.public_id task_public_id,c.public_id cycle_public_id FROM TaskReplanRequests r JOIN Tasks t ON t.id_=r.task_id_ AND t.user_id_=r.user_id_ JOIN ProjectAutonomyCycles c ON c.id_=r.autonomy_cycle_id_ WHERE r.user_id_=? AND r.public_id=? LIMIT 1");$s->bind_param('is',$u,$public);return$this->one($s);}
 public function safeCheckpoint(int$u,string$public):array{$s=$this->p("SELECT r.*,t.public_id task_public_id,t.status task_status,t.lock_version task_lock,s.status source_step_status,c.public_id cycle_public_id,c.status cycle_status,EXISTS(SELECT 1 FROM TaskExecutions e WHERE e.task_id_=t.id_ AND e.status IN ('queued','running','waiting')) active_execution,EXISTS(SELECT 1 FROM TaskSteps x WHERE x.task_id_=t.id_ AND x.status='running') running_step FROM TaskReplanRequests r JOIN Tasks t ON t.id_=r.task_id_ JOIN TaskSteps s ON s.id_=r.source_step_id_ JOIN ProjectAutonomyCycles c ON c.id_=r.autonomy_cycle_id_ WHERE r.user_id_=? AND r.public_id=? LIMIT 1");$s->bind_param('is',$u,$public);$r=$this->one($s)??throw new TaskNotFoundException('replan_not_found');if($r['status']!=='checkpointed'||$r['task_status']!=='failed'||$r['source_step_status']!=='failed'||(int)$r['active_execution']!==0||(int)$r['running_step']!==0||(string)$r['cycle_status']!=='active')throw new TaskTransitionException('replan_checkpoint_unsafe');return$r;}
 public function transition(int$u,string$public,int$lock,string$to):array{if(!in_array($to,['rejected','failed'],true))throw new TaskValidationException('replan_transition_invalid');$s=$this->p("UPDATE TaskReplanRequests SET status=?,rejected_at=IF(?='rejected',NOW(6),rejected_at),failed_at=IF(?='failed',NOW(6),failed_at),lock_version=lock_version+1 WHERE user_id_=? AND public_id=? AND lock_version=? AND status='checkpointed'");$s->bind_param('sssisi',$to,$to,$to,$u,$public,$lock);$this->x($s);if($s->affected_rows!==1){$s->close();$existing=$this->findOwned($u,$public);if($existing&&$existing['status']===$to)return$existing;throw new TaskConcurrencyException('replan_checkpoint_conflict');}$s->close();return$this->findOwned($u,$public)??throw new TaskNotFoundException('replan_not_found');}
 private function one(mysqli_stmt$s):?array{$this->x($s);$r=$s->get_result()->fetch_assoc();$s->close();return$r?:null;}private function p(string$q):mysqli_stmt{$s=$this->db->prepare($q);if(!$s)throw new RuntimeException('replan_prepare_failed');return$s;}private function x(mysqli_stmt$s):void{if(!$s->execute())throw new RuntimeException('replan_query_failed');}
}
