<?php
declare(strict_types=1);

/** Bounded, owner-scoped and side-effect-free read model for Task Center. */
final class TaskCenterAutonomyReadService
{
    private const TEXT_LIMIT = 800;
    public function __construct(private mysqli $db) {}

    public function taskDetail(int $userId, array $ownedTask): array
    {
        $taskId=(int)$ownedTask['id_'];$projectId=(int)($ownedTask['project_id_']??0);
        if($userId<1||$taskId<1)return $this->emptyDetail();
        $membership=$this->one("SELECT c.public_id cycle_public_id,c.status cycle_status,ct.depth,t.public_id task_public_id,t.parent_task_id_,p.public_id parent_public_id,p.title parent_title FROM Tasks t LEFT JOIN ProjectAutonomyCycleTasks ct ON ct.task_id_=t.id_ AND ct.user_id_=t.user_id_ LEFT JOIN ProjectAutonomyCycles c ON c.id_=ct.cycle_id_ AND c.user_id_=t.user_id_ AND c.project_id_=t.project_id_ LEFT JOIN Tasks p ON p.id_=t.parent_task_id_ AND p.user_id_=t.user_id_ WHERE t.id_=? AND t.user_id_=? LIMIT 1",'ii',[$taskId,$userId]);
        if(!$membership)throw new TaskNotFoundException('not_found');
        // task_id_ is intentionally not part of the Phase 11D schema: source_task_id_ is authoritative.
        $continuations=$this->all("SELECT x.public_id,x.status,x.terminal_status,x.depth,x.decision_type,x.reason_code,LEFT(x.public_reason,800) public_reason,LEFT(x.question,800) question,x.attempt_count,x.answer,x.answered_at,x.started_at,x.finished_at,x.created_at,x.updated_at,c.public_id cycle_public_id,p.public_id proposal_public_id,s.public_id spawned_task_public_id,s.title spawned_task_title FROM PostTaskContinuations x JOIN Tasks source ON source.id_=x.source_task_id_ AND source.user_id_=x.user_id_ AND source.project_id_=x.project_id_ JOIN ProjectAutonomyCycles c ON c.id_=x.autonomy_cycle_id_ AND c.user_id_=x.user_id_ AND c.project_id_=x.project_id_ LEFT JOIN NextWorkProposals p ON p.id_=x.proposal_id_ AND p.user_id_=x.user_id_ LEFT JOIN Tasks s ON s.id_=x.spawned_task_id_ AND s.user_id_=x.user_id_ WHERE x.user_id_=? AND x.source_task_id_=? ORDER BY x.created_at DESC LIMIT 10",'ii',[$userId,$taskId]);
        $proposals=$this->all("SELECT p.public_id,p.status,LEFT(p.public_reason,800) public_reason,LEFT(p.proposed_title,255) proposed_title,LEFT(p.proposed_objective,800) proposed_objective,LEFT(CAST(p.evidence_json AS CHAR),1200) evidence,p.authorization_reason,p.lock_version,p.approved_at,p.rejected_at,p.spawned_at,p.created_at,p.updated_at,c.public_id cycle_public_id,source.public_id source_task_public_id,source.title source_task_title,spawned.public_id spawned_task_public_id,spawned.title spawned_task_title FROM NextWorkProposals p JOIN Tasks source ON source.id_=p.source_task_id_ AND source.user_id_=p.user_id_ AND source.project_id_=p.project_id_ JOIN ProjectAutonomyCycles c ON c.id_=p.autonomy_cycle_id_ AND c.user_id_=p.user_id_ AND c.project_id_=p.project_id_ LEFT JOIN Tasks spawned ON spawned.id_=p.spawned_task_id_ AND spawned.user_id_=p.user_id_ WHERE p.user_id_=? AND (p.source_task_id_=? OR p.spawned_task_id_=?) ORDER BY p.created_at DESC LIMIT 10",'iii',[$userId,$taskId,$taskId]);
        $requests=$this->all("SELECT r.public_id,r.status,r.trigger_code,r.failure_disposition,LEFT(r.public_reason,500) public_reason,r.attempt_count,r.lock_version,r.approved_at,r.rejected_at,r.applied_at,r.failed_at,r.created_at,r.updated_at,s.step_key source_step_key,s.title source_step_title,c.public_id cycle_public_id,v.public_id revision_public_id,v.revision_number,v.status revision_status,v.planner_model,v.created_at revision_created_at,v.approved_at revision_approved_at,v.rejected_at revision_rejected_at,v.applied_at revision_applied_at FROM TaskReplanRequests r JOIN Tasks t ON t.id_=r.task_id_ AND t.user_id_=r.user_id_ AND t.project_id_=r.project_id_ JOIN TaskSteps s ON s.id_=r.source_step_id_ AND s.task_id_=r.task_id_ JOIN ProjectAutonomyCycles c ON c.id_=r.autonomy_cycle_id_ AND c.user_id_=r.user_id_ LEFT JOIN TaskPlanRevisions v ON v.id_=r.revision_id_ AND v.user_id_=r.user_id_ AND v.task_id_=r.task_id_ WHERE r.user_id_=? AND r.task_id_=? ORDER BY r.created_at DESC LIMIT 20",'ii',[$userId,$taskId]);
        $revisions=$this->all("SELECT v.id_,v.public_id,v.revision_number,v.source_revision,v.status,v.planner_model,v.proposed_plan_json,LEFT(v.public_reason,500) public_reason,v.approved_at,v.rejected_at,v.applied_at,v.created_at,v.updated_at FROM TaskPlanRevisions v JOIN Tasks t ON t.id_=v.task_id_ AND t.user_id_=v.user_id_ AND t.project_id_=v.project_id_ WHERE v.user_id_=? AND v.task_id_=? ORDER BY v.revision_number DESC LIMIT 20",'ii',[$userId,$taskId]);
        foreach($revisions as &$revision){$revisionId=(int)$revision['id_'];$proposed=json_decode((string)$revision['proposed_plan_json'],true);unset($revision['id_'],$revision['proposed_plan_json']);$revision['proposed_steps']=array_slice(is_array($proposed['steps']??null)?$proposed['steps']:[],0,64);$revision['steps']=$this->all("SELECT rs.logical_key,rs.position_in_revision,s.step_key,s.title,s.step_type,s.status,s.agent_key,LEFT(COALESCE(s.output_summary,s.error_message,''),1000) output_summary,s.created_at,s.completed_at FROM TaskPlanRevisionSteps rs JOIN TaskPlanRevisions v ON v.id_=rs.revision_id_ JOIN TaskSteps s ON s.id_=rs.step_id_ AND s.task_id_=v.task_id_ WHERE rs.revision_id_=? AND v.user_id_=? AND v.task_id_=? ORDER BY rs.position_in_revision LIMIT 64",'iii',[$revisionId,$userId,$taskId]);}unset($revision);
        $incoming=false;foreach($proposals as $proposal)if(($proposal['spawned_task_public_id']??null)===$ownedTask['public_id']){$incoming=true;break;}
        return ['participates'=>$membership['cycle_public_id']!==null,'cycle'=>$membership['cycle_public_id']===null?null:['public_id'=>$membership['cycle_public_id'],'status'=>$membership['cycle_status']],'root'=>$membership['cycle_public_id']!==null&&(int)$membership['depth']===0,'depth'=>$membership['cycle_public_id']===null?null:(int)$membership['depth'],'generated_from_proposal'=>$incoming,'parent'=>$membership['parent_public_id']===null?null:['public_id'=>$membership['parent_public_id'],'title'=>$membership['parent_title']],'continuations'=>$continuations,'proposals'=>$proposals,'replans'=>$requests,'revisions'=>$revisions];
    }

    public function projectSummary(int $userId, int $projectId): ?array
    {
        if($projectId<1)return null;
        $project=$this->one("SELECT id_,name FROM Projects WHERE id_=? AND user_id_=? AND status<>'deleted' LIMIT 1",'ii',[$projectId,$userId]);
        if(!$project)throw new TaskNotFoundException('not_found');
        $policy=$this->one("SELECT public_id,user_id_,project_id_,mode,status,stop_reason,lock_version,max_tasks_per_cycle,max_decisions_per_cycle,max_descendant_depth,max_replans_per_cycle,max_runtime_seconds,max_input_tokens,max_output_tokens,max_tool_calls,max_write_tool_calls,created_at,updated_at FROM ProjectAutonomyPolicies WHERE project_id_=? AND user_id_=? LIMIT 1",'ii',[$projectId,$userId]);
        if(!$policy){$budgets=[];foreach(['tasks'=>'max_tasks_per_cycle','decisions'=>'max_decisions_per_cycle','replans'=>'max_replans_per_cycle','runtime_seconds'=>'max_runtime_seconds','input_tokens'=>'max_input_tokens','output_tokens'=>'max_output_tokens','tool_calls'=>'max_tool_calls','write_tool_calls'=>'max_write_tool_calls']as $key=>$limit)$budgets[$key]=['used'=>0,'limit'=>AutonomyPolicy::DEFAULTS[$limit],'remaining'=>AutonomyPolicy::DEFAULTS[$limit]];return ['configured'=>false,'mode'=>'disabled','status'=>'active','stop_reason'=>null,'lock_version'=>0,'limits'=>AutonomyPolicy::DEFAULTS,'max_descendant_depth'=>AutonomyPolicy::DEFAULTS['max_descendant_depth'],'cycle'=>null,'budgets'=>$budgets,'cost_enforceable'=>false];}
        $cycle=$this->one("SELECT public_id,status,decisions_consumed,tasks_consumed,replans_consumed,input_tokens_consumed,output_tokens_consumed,tool_calls_consumed,write_tool_calls_consumed,runtime_seconds_consumed,started_at,finished_at,created_at,updated_at FROM ProjectAutonomyCycles WHERE project_id_=? AND user_id_=? ORDER BY (status='active') DESC,created_at DESC LIMIT 1",'ii',[$projectId,$userId]);
        $effective=AutonomyPolicy::fromRow($policy);$map=['tasks'=>['tasks_consumed','max_tasks_per_cycle'],'decisions'=>['decisions_consumed','max_decisions_per_cycle'],'replans'=>['replans_consumed','max_replans_per_cycle'],'runtime_seconds'=>['runtime_seconds_consumed','max_runtime_seconds'],'input_tokens'=>['input_tokens_consumed','max_input_tokens'],'output_tokens'=>['output_tokens_consumed','max_output_tokens'],'tool_calls'=>['tool_calls_consumed','max_tool_calls'],'write_tool_calls'=>['write_tool_calls_consumed','max_write_tool_calls']];$budgets=[];
        foreach($map as$key=>[$usedKey,$limitKey]){$used=(int)($cycle[$usedKey]??0);$limit=$effective->limits[$limitKey];$budgets[$key]=['used'=>$used,'limit'=>$limit,'remaining'=>max(0,$limit-$used)];}
        if($cycle)foreach(array_keys($cycle)as$key)if(str_ends_with($key,'_consumed'))unset($cycle[$key]);
        return ['configured'=>true,'policy_public_id'=>$policy['public_id'],'mode'=>$policy['mode'],'status'=>$policy['status'],'stop_reason'=>$policy['stop_reason'],'lock_version'=>(int)$policy['lock_version'],'limits'=>$effective->limits,'max_descendant_depth'=>$effective->limits['max_descendant_depth'],'cycle'=>$cycle,'budgets'=>$budgets,'cost_enforceable'=>false];
    }

    private function emptyDetail():array{return ['participates'=>false,'cycle'=>null,'root'=>false,'depth'=>null,'generated_from_proposal'=>false,'parent'=>null,'continuations'=>[],'proposals'=>[],'replans'=>[],'revisions'=>[]];}
    private function one(string$sql,string$types,array$values):?array{$rows=$this->query($sql,$types,$values);return$rows[0]??null;}
    private function all(string$sql,string$types,array$values):array{return$this->query($sql,$types,$values);}
    private function query(string$sql,string$types,array$values):array{$s=$this->db->prepare($sql);if(!$s)throw new RuntimeException('autonomy_read_unavailable');if($types!=='')$s->bind_param($types,...$values);if(!$s->execute()){ $s->close();throw new RuntimeException('autonomy_read_failed');}$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return$rows;}
}
