<?php
declare(strict_types=1);
final class TaskOrchestrator{
 public function __construct(private mysqli$db,private TaskRepository$tasks,private TaskEventRepository$events,private ?TaskStateMachine$machine=null){$this->machine??=new TaskStateMachine();}
 public function createTask(int$u,int$session,string$title,string$objective,array$o=[]):array{return$this->tx(function()use($u,$session,$title,$objective,$o){$t=$this->tasks->create(['public_id'=>TaskPublicId::generate(),'user_id'=>$u,'created_by_user_id'=>$u,'project_id'=>$o['project_id']??null,'session_id'=>$session,'origin_message_id'=>$o['origin_message_id']??null,'idempotency_key'=>$o['idempotency_key']??null,'origin_type'=>$o['origin_type']??'manual','title'=>$title,'objective'=>$objective,'status'=>TaskStatus::PENDING,'priority'=>$o['priority']??'normal','max_attempts'=>$o['max_attempts']??3]);$this->events->append(['task_id'=>(int)$t['id_'],'actor_type'=>'user','actor_user_id'=>$u,'event_key'=>'task_created','to_status'=>'pending','summary'=>'Tarea creada.']);return$t;});}
 public function transitionTask(int$id,int$u,string$to,int$lock,string$actor='user',array$fields=[]):array{return$this->tx(function()use($id,$u,$to,$lock,$actor,$fields){$t=$this->tasks->findOwnedById($id,$u)??throw new TaskNotFoundException('not_found');$from=$t['status'];$this->machine->assertTransition($from,$to);$n=$this->tasks->updateStatus($id,$u,$to,$lock,$fields);$this->events->append(['task_id'=>$id,'actor_type'=>$actor,'actor_user_id'=>$actor==='user'?$u:null,'event_key'=>'task_'.$to,'from_status'=>$from,'to_status'=>$to,'summary'=>$fields['event_summary']??'Estado actualizado.']);return$n;});}
 public function requestCancellation(int$id,int$u,int$lock):array{return$this->transitionTask($id,$u,'cancelled',$lock,'user',['cancel_requested_at'=>gmdate('Y-m-d H:i:s.u'),'event_summary'=>'Cancelación solicitada.']);}
 public function retryTask(int$id,int$u,int$lock):array{return$this->tx(function()use($id,$u,$lock){$t=$this->tasks->findOwnedById($id,$u)??throw new TaskNotFoundException('not_found');$this->machine->assertTransition($t['status'],'ready');if((int)$t['attempt_count']>=(int)$t['max_attempts'])throw new TaskTransitionException('attempt_limit');$n=$this->tasks->retry($id,$u,$lock);$this->events->append(['task_id'=>$id,'actor_type'=>'user','actor_user_id'=>$u,'event_key'=>'task_ready','from_status'=>'failed','to_status'=>'ready','summary'=>'Tarea preparada para reintento.','details'=>['attempt_count'=>(int)$n['attempt_count']]]);return$n;});}
 private function tx(callable$f){$this->db->begin_transaction();try{$r=$f();$this->db->commit();return$r;}catch(Throwable$e){$this->db->rollback();throw$e;}}
}
