<?php
declare(strict_types=1);
final class TaskRecurrenceService{
 public function __construct(private mysqli$db,private TaskRepository$tasks,private TaskRecurrenceRuleRepository$rules,private TaskRecurrenceOccurrenceRepository$occurrences,private TaskRecurrenceDefinition$definitions,private TaskRecurrenceCalculator$calculator){}
 public function createRule(int$u,array$d,DateTimeImmutable$now):array{
  $definition=$this->definitions->validate($d);$session=filter_var($d['session_id']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if($session===false)throw new TaskValidationException('session_invalid');$project=isset($d['project_id'])&&$d['project_id']!==''?filter_var($d['project_id'],FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]):null;if($project===false)throw new TaskValidationException('project_invalid');
  $scope=$this->tasks->sessionScope((int)$session,$u);if($scope===null)throw new TaskValidationException('session_invalid');$actual=$scope['project_id_']===null?null:(int)$scope['project_id_'];if($project!==$actual)throw new TaskValidationException('session_project_mismatch');if($project!==null&&!$this->tasks->projectOwned((int)$project,$u))throw new TaskValidationException('project_invalid');
  $title=trim((string)($d['title']??''));$objective=trim((string)($d['objective']??''));if($title===''||mb_strlen($title)>255)throw new TaskValidationException('title_invalid');if($objective===''||mb_strlen($objective)>65535)throw new TaskValidationException('objective_invalid');$priority=(string)($d['priority']??'normal');if(!in_array($priority,['low','normal','high','urgent'],true))throw new TaskValidationException('priority_invalid');$mode=(string)($d['mode']??'supervised');if(!in_array($mode,['automatic','supervised'],true))throw new TaskValidationException('manual_mode_invalid');
  $next=$this->calculator->storage($this->calculator->next($definition,$now));return$this->rules->create(array_merge($definition,['public_id'=>TaskPublicId::generate(),'user_id'=>$u,'project_id'=>$project,'session_id'=>(int)$session,'next_occurrence_at'=>$next,'task_title'=>$title,'task_objective'=>$objective,'task_priority'=>$priority,'task_mode'=>$mode]));
 }
 public function pause(int$u,int$id,int$lock):array{return$this->transaction(fn()=> $this->change($u,$id,$lock,'enabled','paused'));}
 public function resume(int$u,int$id,int$lock,DateTimeImmutable$now):array{return$this->transaction(function()use($u,$id,$lock,$now){$rule=$this->rules->lockOwned($id,$u)??throw new TaskNotFoundException('not_found');if($rule['status']!=='paused'||(int)$rule['lock_version']!==$lock)throw new TaskConcurrencyException('recurrence_rule_conflict');$next=(string)$rule['next_occurrence_at'];$instant=new DateTimeImmutable($next,new DateTimeZone('UTC'));if($instant<=$now)$next=$this->calculator->storage($this->calculator->next($rule,$now));return$this->rules->changeStatus($id,$u,'paused','enabled',$lock,$next);});}
 public function cancel(int$u,int$id,int$lock):array{return$this->transaction(function()use($u,$id,$lock){$rule=$this->rules->lockOwned($id,$u)??throw new TaskNotFoundException('not_found');if(!in_array($rule['status'],['enabled','paused'],true)||(int)$rule['lock_version']!==$lock)throw new TaskConcurrencyException('recurrence_rule_conflict');return$this->rules->changeStatus($id,$u,(string)$rule['status'],'cancelled',$lock);});}
 public function reserve(int$u,int$id,string$logicalAt):array{return$this->transaction(function()use($u,$id,$logicalAt){$rule=$this->rules->lockOwned($id,$u)??throw new TaskNotFoundException('not_found');if($rule['status']!=='enabled')throw new TaskTransitionException('recurrence_rule_not_enabled');if($logicalAt!==(string)$rule['next_occurrence_at'])throw new TaskValidationException('occurrence_not_next');$reservation=$this->occurrences->reserve($id,$logicalAt);$reservation['task_idempotency_key']=TaskRecurrenceOccurrenceRepository::taskIdempotencyKey((string)$rule['public_id'],$logicalAt);return$reservation;});}
 private function change(int$u,int$id,int$lock,string$from,string$to):array{$rule=$this->rules->lockOwned($id,$u)??throw new TaskNotFoundException('not_found');if($rule['status']!==$from||(int)$rule['lock_version']!==$lock)throw new TaskConcurrencyException('recurrence_rule_conflict');return$this->rules->changeStatus($id,$u,$from,$to,$lock);}
 private function transaction(callable$f):mixed{$this->db->begin_transaction();try{$r=$f();$this->db->commit();return$r;}catch(Throwable$e){$this->db->rollback();throw$e;}}
}
