<?php
declare(strict_types=1);
final class TaskApiController{
 public function __construct(private TaskApplicationService$app,private int$userId,private bool$featureEnabled){}
 public function handle(string$method,array$query,array$body,array$headers=[]):TaskApiResponse{
  if($this->userId<=0)return TaskApiResponse::error('unauthorized',401);
  try{$action=(string)($method==='GET'?($query['action']??'list'):($body['action']??''));if($method==='GET'){if($action==='list')return TaskApiResponse::ok($this->app->list($this->userId,$query));if($action==='detail')return TaskApiResponse::ok($this->app->detail($this->userId,(string)($query['task']??'')));throw new TaskNotFoundException('not_found');}
   if($method!=='POST')return TaskApiResponse::error('method_not_allowed',405);if(!$this->featureEnabled)throw new TaskNotFoundException('not_found');CsrfGuard::assertSessionToken((string)($headers['x-csrf-token']??''));if($action==='create')return TaskApiResponse::ok($this->app->create($this->userId,$body),201);if($action==='cancel')return TaskApiResponse::ok($this->app->cancel($this->userId,$body));if($action==='approve')return TaskApiResponse::ok($this->app->approve($this->userId,$body));if($action==='reject')return TaskApiResponse::ok($this->app->reject($this->userId,$body));if($action==='retry')return TaskApiResponse::ok($this->app->retry($this->userId,$body));if($action==='add_dependency')return TaskApiResponse::ok($this->app->addDependency($this->userId,$body),201);if($action==='remove_dependency')return TaskApiResponse::ok($this->app->removeDependency($this->userId,$body));throw new TaskNotFoundException('not_found');
  }catch(TaskValidationException|InvalidArgumentException$e){return TaskApiResponse::error($e->getMessage(),422);}catch(TaskNotFoundException$e){return TaskApiResponse::error('not_found',404);}catch(TaskConcurrencyException|TaskTransitionException$e){return TaskApiResponse::error($e->getMessage(),409);}catch(RuntimeException$e){if($e->getMessage()==='csrf_invalid')return TaskApiResponse::error('csrf_invalid',403);error_log('Task API internal error: '.$e->getMessage());return TaskApiResponse::error('internal_error',500);}catch(Throwable$e){error_log('Task API internal error: '.$e->getMessage());return TaskApiResponse::error('internal_error',500);}
 }
}
