<?php
declare(strict_types=1);
class TaskApplicationService{
 public function __construct(private TaskRepository$tasks,private TaskStepRepository$steps,private TaskDependencyRepository$dependencies,private TaskExecutionRepository$executions,private TaskEventRepository$events,private TaskOrchestrator$orchestrator,private TaskInputValidator$v,private ?TaskDependencyService$dependencyService=null){}
 public function list(int$u,array$q):array{$f=[];if(isset($q['status'])&&$q['status']!=='')$f['status']=$this->v->oneOf($q['status'],TaskStatus::all(),'status_invalid');if(isset($q['priority'])&&$q['priority']!=='')$f['priority']=$this->v->oneOf($q['priority'],['low','normal','high','urgent'],'priority_invalid');foreach(['project_id'=>'project_id_','session_id'=>'session_id_']as$in=>$db)if(isset($q[$in])&&$q[$in]!=='')$f[$db]=$this->v->positiveInt($q,$in);$limit=isset($q['limit'])?(int)$q['limit']:25;$offset=isset($q['offset'])?(int)$q['offset']:0;if($limit<1||$limit>100||$offset<0)throw new TaskValidationException('pagination_invalid');$rows=$this->tasks->listOwned($u,$f,$limit,$offset);return['tasks'=>array_map(fn($r)=>$this->taskDto($r),$rows),'total'=>$this->tasks->countOwned($u,$f),'limit'=>$limit,'offset'=>$offset];}
 public function detail(int$u,string$public):array{$t=$this->owned($u,$this->v->publicId($public));$id=(int)$t['id_'];$stepRows=$this->steps->listOwned($id,$u);return['task'=>$this->taskDto($t),'plan'=>['planned'=>$stepRows!==[],'steps_count'=>count($stepRows)],'steps'=>array_map(fn($x)=>$this->stepDto($x),$stepRows),'dependencies'=>$this->dependencies->listOwned($id,$u),'executions'=>array_map(fn($x)=>$this->executionDto($x),$this->executions->listOwned($id,$u)),'events'=>array_map(fn($x)=>$this->eventDto($x),$this->events->listOwned($id,$u))];}
 public function create(int$u,array$d):array{$title=$this->v->requiredString($d,'title',255);$objective=$this->v->requiredString($d,'objective',65535);$session=$this->v->positiveInt($d,'session_id');$project=$this->v->positiveInt($d,'project_id',true);$message=$this->v->positiveInt($d,'origin_message_id',true);$priority=$this->v->oneOf($d['priority']??'normal',['low','normal','high','urgent'],'priority_invalid');$key=isset($d['idempotency_key'])?trim((string)$d['idempotency_key']):null;if($key==='')$key=null;if($key!==null&&mb_strlen($key)>128)throw new TaskValidationException('idempotency_key_invalid');if($key!==null&&($existing=$this->tasks->findOwnedByIdempotencyKey($u,$key)))return['created'=>false,'task'=>$this->taskDto($existing)];$scope=$this->tasks->sessionScope($session,$u);if(!$scope)throw new TaskValidationException('session_invalid');$actual=$scope['project_id_']===null?null:(int)$scope['project_id_'];if($project!==$actual)throw new TaskValidationException('session_project_mismatch');if($project!==null&&!$this->tasks->projectOwned($project,$u))throw new TaskValidationException('project_invalid');if($message!==null&&!$this->tasks->messageOwned($message,$session,$u))throw new TaskValidationException('origin_message_invalid');try{$t=$this->orchestrator->createTask($u,$session,$title,$objective,['project_id'=>$project,'origin_message_id'=>$message,'idempotency_key'=>$key,'priority'=>$priority,'origin_type'=>'manual']);}catch(RuntimeException$e){if($key!==null&&($existing=$this->tasks->findOwnedByIdempotencyKey($u,$key)))return['created'=>false,'task'=>$this->taskDto($existing)];throw$e;}return['created'=>true,'task'=>$this->taskDto($t)];}
 public function cancel(int$u,array$d):array{$t=$this->owned($u,$this->v->publicId($d['public_id']??''));return['task'=>$this->taskDto($this->orchestrator->requestCancellation((int)$t['id_'],$u,$this->v->lock($d)))];}
 public function approve(int$u,array$d):array{$t=$this->owned($u,$this->v->publicId($d['public_id']??''));return['task'=>$this->taskDto($this->orchestrator->approveChatTask((int)$t['id_'],$u,$this->v->lock($d)))];}
 public function reject(int$u,array$d):array{$t=$this->owned($u,$this->v->publicId($d['public_id']??''));return['task'=>$this->taskDto($this->orchestrator->rejectChatTask((int)$t['id_'],$u,$this->v->lock($d)))];}
 public function addDependency(int$u,array$d):array{if(!$this->dependencyService)throw new RuntimeException('dependency_service_unavailable');$task=$this->v->publicId($d['public_id']??'');$required=$this->v->publicId($d['depends_on_public_id']??'');$this->dependencyService->add($u,$task,$required,(string)($d['condition']??'completed'));return['added'=>true];}
 public function removeDependency(int$u,array$d):array{if(!$this->dependencyService)throw new RuntimeException('dependency_service_unavailable');$this->dependencyService->remove($u,$this->v->publicId($d['public_id']??''),$this->v->publicId($d['depends_on_public_id']??''));return['removed'=>true];}
 public function retry(int$u,array$d):array{$t=$this->owned($u,$this->v->publicId($d['public_id']??''));return['task'=>$this->taskDto($this->orchestrator->retryTask((int)$t['id_'],$u,$this->v->lock($d)))];}
 private function owned(int$u,string$p):array{return$this->tasks->findOwnedByPublicId($p,$u)??throw new TaskNotFoundException('not_found');}
 private function taskDto(array$r):array{return['public_id'=>$r['public_id'],'project_id'=>$r['project_id_']===null?null:(int)$r['project_id_'],'session_id'=>(int)$r['session_id_'],'origin_message_id'=>$r['origin_message_id_']===null?null:(int)$r['origin_message_id_'],'result_message_id'=>$r['result_message_id_']===null?null:(int)$r['result_message_id_'],'origin_type'=>$r['origin_type'],'title'=>$r['title'],'objective'=>$r['objective'],'status'=>$r['status'],'priority'=>$r['priority'],'progress_percent'=>(int)$r['progress_percent'],'max_attempts'=>(int)$r['max_attempts'],'attempt_count'=>(int)$r['attempt_count'],'lock_version'=>(int)$r['lock_version'],'scheduled_at'=>$r['scheduled_at'],'started_at'=>$r['started_at'],'due_at'=>$r['due_at'],'completed_at'=>$r['completed_at'],'cancel_requested_at'=>$r['cancel_requested_at'],'cancelled_at'=>$r['cancelled_at'],'result_summary'=>$r['result_summary'],'error_code'=>$r['error_code'],'error_message'=>$r['error_message'],'created_at'=>$r['created_at'],'updated_at'=>$r['updated_at']];}
 private function stepDto(array$r):array{return array_intersect_key($r,array_flip(['position','step_key','title','description','step_type','status','progress_percent','agent_key','model_id','input_json','checkpoint_json','output_summary','error_message','attempt_count','max_attempts','lock_version','started_at','completed_at','created_at','updated_at']));}
 private function executionDto(array$r):array{return array_intersect_key($r,array_flip(['trace_id','attempt_number','agent_key','model_id','status','started_at','heartbeat_at','finished_at','error_message','created_at']));}
 private function eventDto(array$r):array{return array_intersect_key($r,array_flip(['actor_type','event_key','from_status','to_status','summary','details_json','created_at']));}
}
