<?php
declare(strict_types=1);
final class TaskRepository{
 public function __construct(private mysqli$db){}
 public function create(array$d):array{$q='INSERT INTO Tasks(public_id,user_id_,created_by_user_id_,project_id_,session_id_,origin_message_id_,idempotency_key,origin_type,title,objective,status,priority,max_attempts,scheduled_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)';$s=$this->p($q);$project=$d['project_id']??null;$msg=$d['origin_message_id']??null;$key=$d['idempotency_key']??null;$scheduled=$d['scheduled_at']??null;$s->bind_param('siiiiissssssis',$d['public_id'],$d['user_id'],$d['created_by_user_id'],$project,$d['session_id'],$msg,$key,$d['origin_type'],$d['title'],$d['objective'],$d['status'],$d['priority'],$d['max_attempts'],$scheduled);$this->x($s);$id=(int)$this->db->insert_id;$s->close();return$this->findById($id)??throw new RuntimeException('task_create_failed');}
 public function findById(int$id):?array{return$this->one('SELECT * FROM Tasks WHERE id_=?','i',[$id]);}
 public function findOwnedById(int$id,int$u):?array{return$this->one('SELECT * FROM Tasks WHERE id_=? AND user_id_=?','ii',[$id,$u]);}
 public function lockOwnedForResponse(int$id,int$u):?array{$s=$this->p('SELECT * FROM Tasks WHERE id_=? AND user_id_=? FOR UPDATE');$s->bind_param('ii',$id,$u);$this->x($s);$r=$s->get_result()->fetch_assoc();$s->close();return$r?:null;}
 public function lockOwnedForRetry(int$id,int$u):?array{return$this->lockOwnedForResponse($id,$u);}
 public function findOwnedByPublicId(string$p,int$u):?array{return$this->one("SELECT Tasks.*,current.step_key current_step_key,current.title current_step_title,current.step_type current_step_type,current.status current_step_status,current.agent_key current_step_agent_key,current.model_id current_step_model_id,current.checkpoint_json current_step_checkpoint_json FROM Tasks LEFT JOIN TaskSteps current ON current.id_=Tasks.current_step_id_ AND current.task_id_=Tasks.id_ WHERE Tasks.public_id=? AND Tasks.user_id_=?",'si',[$p,$u]);}
 public function findOwnedByIdempotencyKey(int$u,string$k):?array{return$this->one('SELECT * FROM Tasks WHERE user_id_=? AND idempotency_key=?','is',[$u,$k]);}
 public function setCurrentStep(int$id,int$u,int$step):void{$s=$this->p('UPDATE Tasks SET current_step_id_=? WHERE id_=? AND user_id_=?');$s->bind_param('iii',$step,$id,$u);$this->x($s);$s->close();}
 public function assignResult(int$id,int$u,int$messageId,string$summary):void{$s=$this->p('UPDATE Tasks SET result_message_id_=?,result_summary=? WHERE id_=? AND user_id_=?');$s->bind_param('isii',$messageId,$summary,$id,$u);$this->x($s);$s->close();}
 public function assignResultIfEmpty(int$id,int$u,int$messageId,string$summary):bool{$s=$this->p('UPDATE Tasks SET result_message_id_=?,result_summary=? WHERE id_=? AND user_id_=? AND result_message_id_ IS NULL');$s->bind_param('isii',$messageId,$summary,$id,$u);$this->x($s);$ok=$s->affected_rows===1;$s->close();return$ok;}
 public function sessionScope(int$session,int$u):?array{return$this->one('SELECT id_,project_id_ FROM ChatSessions WHERE id_=? AND user_id_=?','ii',[$session,$u]);}
 public function projectOwned(int$project,int$u):bool{return$this->one("SELECT id_ FROM Projects WHERE id_=? AND user_id_=? AND status<>'deleted'",'ii',[$project,$u])!==null;}
 public function messageOwned(int$msg,int$session,int$u):bool{return$this->one('SELECT id_ FROM ChatMessages WHERE id_=? AND session_id_=? AND user_id_=?','iii',[$msg,$session,$u])!==null;}
 public function approvedChatTurn(string$public,int$u):?array{return$this->one("SELECT t.id_ task_id,t.public_id,t.session_id_,t.status task_status,t.lock_version task_lock,s.id_ step_id,s.status step_status,s.lock_version step_lock,s.input_json,m.content original_text FROM Tasks t JOIN TaskSteps s ON s.task_id_=t.id_ AND s.step_key='respond' JOIN ChatMessages m ON m.id_=t.origin_message_id_ AND m.session_id_=t.session_id_ AND m.user_id_=t.user_id_ WHERE t.public_id=? AND t.user_id_=?",'si',[$public,$u]);}
 public function listOwned(int$u,array$f,int$limit,int$offset):array{[$where,$types,$v]=$this->ownedFilters($u,$f,'Tasks.');$sql="SELECT Tasks.*,current.step_key current_step_key,current.title current_step_title,current.step_type current_step_type,current.status current_step_status,current.agent_key current_step_agent_key,current.model_id current_step_model_id,current.checkpoint_json current_step_checkpoint_json FROM Tasks LEFT JOIN TaskSteps current ON current.id_=Tasks.current_step_id_ AND current.task_id_=Tasks.id_ WHERE {$where} ORDER BY Tasks.updated_at DESC,Tasks.id_ DESC LIMIT ? OFFSET ?";$types.='ii';$v[]=$limit;$v[]=$offset;$s=$this->p($sql);$s->bind_param($types,...$v);$this->x($s);$out=[];$r=$s->get_result();while($row=$r->fetch_assoc())$out[]=$row;$s->close();return$out;}
 public function countOwned(int$u,array$f):int{[$where,$types,$v]=$this->ownedFilters($u,$f);$s=$this->p('SELECT COUNT(*) c FROM Tasks WHERE '.$where);$s->bind_param($types,...$v);$this->x($s);$c=(int)$s->get_result()->fetch_assoc()['c'];$s->close();return$c;}
 public function updateStatus(int$id,int$u,string$status,int$lock,array$fields=[]):array{$summary=$fields['result_summary']??null;$code=$fields['error_code']??null;$error=$fields['error_message']??null;$now=gmdate('Y-m-d H:i:s.u');$completed=$status==='completed'?$now:null;$cancelReq=$fields['cancel_requested_at']??null;$cancelled=$status==='cancelled'?$now:null;$s=$this->p("UPDATE Tasks SET status=?,completed_at=COALESCE(?,completed_at),cancel_requested_at=COALESCE(?,cancel_requested_at),cancelled_at=COALESCE(?,cancelled_at),result_summary=?,error_code=?,error_message=?,progress_percent=IF(?='completed',100,progress_percent),lock_version=lock_version+1 WHERE id_=? AND user_id_=? AND lock_version=?");$s->bind_param('ssssssssiii',$status,$completed,$cancelReq,$cancelled,$summary,$code,$error,$status,$id,$u,$lock);$this->x($s);$a=$s->affected_rows;$s->close();if($a!==1)throw new TaskConcurrencyException('concurrency_conflict');return$this->findOwnedById($id,$u)??throw new TaskNotFoundException('not_found');}
 public function hasExecutions(int$id):bool{$s=$this->p('SELECT 1 FROM TaskExecutions WHERE task_id_=? LIMIT 1');$s->bind_param('i',$id);$this->x($s);$found=$s->get_result()->fetch_assoc()!==null;$s->close();return$found;}
 public function reschedule(int$id,int$u,?string$scheduled,int$lock):array{$s=$this->p("UPDATE Tasks SET scheduled_at=?,lock_version=lock_version+1 WHERE id_=? AND user_id_=? AND lock_version=? AND status IN ('pending','ready','waiting_user') AND NOT EXISTS(SELECT 1 FROM TaskExecutions e WHERE e.task_id_=Tasks.id_)");$s->bind_param('siii',$scheduled,$id,$u,$lock);$this->x($s);$a=$s->affected_rows;$s->close();if($a!==1)throw new TaskConcurrencyException('reschedule_conflict');return$this->findOwnedById($id,$u)??throw new TaskNotFoundException('not_found');}
 public function retry(int$id,int$u,int$lock):array{$s=$this->p("UPDATE Tasks SET status='ready',attempt_count=attempt_count+1,error_code=NULL,error_message=NULL,completed_at=NULL,lock_version=lock_version+1 WHERE id_=? AND user_id_=? AND lock_version=? AND status='failed' AND attempt_count<max_attempts");$s->bind_param('iii',$id,$u,$lock);$this->x($s);$a=$s->affected_rows;$s->close();if($a!==1)throw new TaskConcurrencyException('retry_conflict');return$this->findOwnedById($id,$u)??throw new TaskNotFoundException('not_found');}
 private function ownedFilters(int$u,array$f,string$prefix=''):array{$where=$prefix.'user_id_=?';$types='i';$v=[$u];foreach(['status'=>'s','project_id_'=>'i','session_id_'=>'i','priority'=>'s']as$k=>$t)if(array_key_exists($k,$f)){$where.=" AND {$prefix}{$k}=?";$types.=$t;$v[]=$f[$k];}if(isset($f['q'])){$where.=" AND ({$prefix}title LIKE CONCAT('%',?,'%') OR {$prefix}objective LIKE CONCAT('%',?,'%'))";$types.='ss';$needle=str_replace(['\\','%','_'],['\\\\','\\%','\\_'],(string)$f['q']);$v[]=$needle;$v[]=$needle;}return[$where,$types,$v];}
 private function one(string$q,string$t,array$v):?array{$s=$this->p($q.' LIMIT 1');$s->bind_param($t,...$v);$this->x($s);$r=$s->get_result()->fetch_assoc();$s->close();return$r?:null;}private function p(string$q):mysqli_stmt{$s=$this->db->prepare($q);if(!$s)throw new RuntimeException('database_error');return$s;}private function x(mysqli_stmt$s):void{if(!$s->execute())throw new RuntimeException('database_error');}
}
