<?php
declare(strict_types=1);
final class TaskRecurrenceOccurrenceRepository{
 public function __construct(private mysqli$db){}
 /** The UNIQUE(rule_id_,logical_occurrence_at) constraint is the concurrency authority. */
 public function reserve(int$ruleId,string$logicalAt):array{$s=$this->p("INSERT INTO TaskRecurrenceOccurrences(rule_id_,logical_occurrence_at,status) VALUES(?,?,'reserved')");$s->bind_param('is',$ruleId,$logicalAt);try{if(!$s->execute()){if($s->errno!==1062)throw new RuntimeException('database_error');$s->close();return$this->existingReservation($ruleId,$logicalAt);}}catch(mysqli_sql_exception$e){$s->close();if($e->getCode()!==1062)throw$e;return$this->existingReservation($ruleId,$logicalAt);}$id=$this->db->insert_id;$s->close();return['created'=>true,'occurrence'=>$this->findById((int)$id)];}
 public function claimRetryable(int$limit,string$staleBefore):array{$s=$this->p("SELECT o.*,r.public_id rule_public_id,r.user_id_,r.project_id_,r.session_id_,r.frequency,r.weekday,r.local_time,r.timezone,r.misfire_policy,r.task_title,r.task_objective,r.task_priority,r.task_mode FROM TaskRecurrenceOccurrences o JOIN TaskRecurrenceRules r ON r.id_=o.rule_id_ WHERE o.task_id_ IS NULL AND o.status IN ('reserved','failed') AND o.updated_at<=? ORDER BY o.updated_at,o.id_ LIMIT ? FOR UPDATE SKIP LOCKED");$s->bind_param('si',$staleBefore,$limit);$this->x($s);$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();$out=[];foreach($rows as$row){$s=$this->p("UPDATE TaskRecurrenceOccurrences SET status='reserved',failure_code=NULL,updated_at=UTC_TIMESTAMP(6),lock_version=lock_version+1 WHERE id_=? AND lock_version=? AND task_id_ IS NULL AND status IN ('reserved','failed')");$id=(int)$row['id_'];$lock=(int)$row['lock_version'];$s->bind_param('ii',$id,$lock);$this->x($s);$won=$s->affected_rows===1;$s->close();if(!$won)continue;$row['status']='reserved';$row['failure_code']=null;$row['lock_version']=$lock+1;$row['rule']=['id_'=>(int)$row['rule_id_'],'public_id'=>$row['rule_public_id'],'user_id_'=>(int)$row['user_id_'],'project_id_'=>$row['project_id_'],'session_id_'=>(int)$row['session_id_'],'frequency'=>$row['frequency'],'weekday'=>$row['weekday'],'local_time'=>$row['local_time'],'timezone'=>$row['timezone'],'misfire_policy'=>$row['misfire_policy'],'task_title'=>$row['task_title'],'task_objective'=>$row['task_objective'],'task_priority'=>$row['task_priority'],'task_mode'=>$row['task_mode']];$out[]=['rule'=>$row['rule'],'occurrence'=>$row];}return$out;}
 public function linkTask(int$id,int$taskId,int$lock):array{$s=$this->p("UPDATE TaskRecurrenceOccurrences SET task_id_=?,status='materialized',failure_code=NULL,lock_version=lock_version+1 WHERE id_=? AND lock_version=? AND status IN ('reserved','failed') AND task_id_ IS NULL");$s->bind_param('iii',$taskId,$id,$lock);$this->x($s);$n=$s->affected_rows;$s->close();if($n!==1)throw new TaskConcurrencyException('occurrence_conflict');return$this->findById($id)??throw new TaskNotFoundException('occurrence_not_found');}
 public function fail(int$id,string$code,int$lock):array{return$this->recordFailure($id,$code,$lock);}
 public function recordFailure(int$id,string$code,int$lock):array{$s=$this->p("UPDATE TaskRecurrenceOccurrences SET status='failed',failure_code=?,lock_version=lock_version+1 WHERE id_=? AND lock_version=? AND status IN ('reserved','failed') AND task_id_ IS NULL");$s->bind_param('sii',$code,$id,$lock);$this->x($s);$n=$s->affected_rows;$s->close();if($n!==1)throw new TaskConcurrencyException('occurrence_conflict');return$this->findById($id)??throw new TaskNotFoundException('occurrence_not_found');}
 public function listRecentOwned(int$ruleId,int$u,int$limit):array{$s=$this->p('SELECT o.logical_occurrence_at,o.status,o.failure_code,o.created_at,o.updated_at,t.public_id task_public_id FROM TaskRecurrenceOccurrences o JOIN TaskRecurrenceRules r ON r.id_=o.rule_id_ LEFT JOIN Tasks t ON t.id_=o.task_id_ AND t.user_id_=r.user_id_ WHERE o.rule_id_=? AND r.user_id_=? ORDER BY o.logical_occurrence_at DESC,o.id_ DESC LIMIT ?');$s->bind_param('iii',$ruleId,$u,$limit);$this->x($s);$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return$rows;}
 public function findByIdentity(int$ruleId,string$logicalAt):?array{return$this->one('SELECT * FROM TaskRecurrenceOccurrences WHERE rule_id_=? AND logical_occurrence_at=?','is',[$ruleId,$logicalAt]);}
 public function findById(int$id):?array{return$this->one('SELECT * FROM TaskRecurrenceOccurrences WHERE id_=?','i',[$id]);}
 private function existingReservation(int$ruleId,string$logicalAt):array{$existing=$this->findByIdentity($ruleId,$logicalAt);if($existing===null)throw new RuntimeException('occurrence_reservation_conflict');return['created'=>false,'occurrence'=>$existing];}
 public static function taskIdempotencyKey(string$rulePublicId,string$logicalAt):string{return'recur:'.hash('sha256',$rulePublicId.'|'.$logicalAt);}
 private function one(string$q,string$t,array$v):?array{$s=$this->p($q.' LIMIT 1');$s->bind_param($t,...$v);$this->x($s);$r=$s->get_result()->fetch_assoc();$s->close();return$r?:null;}private function p(string$q):mysqli_stmt{$s=$this->db->prepare($q);if(!$s)throw new RuntimeException('database_error');return$s;}private function x(mysqli_stmt$s):void{if(!$s->execute())throw new RuntimeException('database_error');}
}
