<?php
declare(strict_types=1);
class TaskApplicationService{
 private TaskPublicApprovalPresenter $approvalPresenter;
 public function __construct(private TaskRepository$tasks,private TaskStepRepository$steps,private TaskDependencyRepository$dependencies,private TaskExecutionRepository$executions,private TaskEventRepository$events,private TaskOrchestrator$orchestrator,private TaskInputValidator$v,private ?TaskDependencyService$dependencyService=null,private ?TaskStepApprovalService$stepApproval=null,private ?TaskArtifactRepository$artifacts=null,private ?TaskArtifactResourceResolver$artifactResources=null,private ?TaskToolApprovalDecisionService$toolApproval=null,?TaskPublicApprovalPresenter$approvalPresenter=null){$this->approvalPresenter=$approvalPresenter??new TaskPublicApprovalPresenter();}
 public function list(int$u,array$q):array{$f=[];if(isset($q['status'])&&$q['status']!=='')$f['status']=$this->v->oneOf($q['status'],TaskStatus::all(),'status_invalid');if(isset($q['priority'])&&$q['priority']!=='')$f['priority']=$this->v->oneOf($q['priority'],['low','normal','high','urgent'],'priority_invalid');foreach(['project_id'=>'project_id_','session_id'=>'session_id_']as$in=>$db)if(isset($q[$in])&&$q[$in]!=='')$f[$db]=$this->v->positiveInt($q,$in);if(isset($q['q'])){$search=trim((string)$q['q']);if(mb_strlen($search)>200)throw new TaskValidationException('search_invalid');if($search!=='')$f['q']=$search;}$limit=isset($q['limit'])?(int)$q['limit']:25;$offset=isset($q['offset'])?(int)$q['offset']:0;if($limit<1||$limit>100||$offset<0)throw new TaskValidationException('pagination_invalid');$rows=$this->tasks->listOwned($u,$f,$limit,$offset);return['tasks'=>array_map(fn($r)=>$this->taskDto($r),$rows),'total'=>$this->tasks->countOwned($u,$f),'limit'=>$limit,'offset'=>$offset];}
 public function detail(int$u,string$public):array{$t=$this->owned($u,$this->v->publicId($public));$id=(int)$t['id_'];$stepRows=$this->steps->listOwned($id,$u);$executionRows=$this->executions->listOwned($id,$u);$eventRows=$this->events->listOwned($id,$u,101);$hasEarlier=count($eventRows)>100;if($hasEarlier)$eventRows=array_slice($eventRows,-100);$artifactRows=$this->artifacts?->listByTask($id)??[];$resources=$this->artifactResources?->resolve($artifactRows,$u,$t['project_id_']===null?null:(int)$t['project_id_'])??[];$stepsById=[];foreach($stepRows as$row)$stepsById[(int)$row['id_']]=$row;$executionsById=[];foreach($executionRows as$row)$executionsById[(int)$row['id_']]=$row;return['task'=>$this->taskDto($t),'plan'=>['planned'=>$stepRows!==[],'steps_count'=>count($stepRows)],'steps'=>array_map(fn($x)=>$this->stepDto($x),$stepRows),'dependencies'=>$this->dependencies->listOwned($id,$u),'dependents'=>$this->dependencies->listOwnedDependents($id,$u),'executions'=>array_map(fn($x)=>$this->executionDto($x),$executionRows),'events'=>array_map(fn($x)=>$this->eventDto($x),$eventRows),'history'=>['limit'=>100,'has_earlier'=>$hasEarlier],'artifacts'=>array_map(function($x)use($resources,$stepsById,$executionsById){$execution=$executionsById[(int)$x['execution_id_']]??null;$step=$execution===null?null:($stepsById[(int)$execution['step_id_']]??null);return$this->artifactDto($x,$resources[(string)$x['resource_type']][(int)$x['resource_id']]??null,$execution,$step);},$artifactRows)];}
 public function create(int$u,array$d):array{$title=$this->v->requiredString($d,'title',255);$objective=$this->v->requiredString($d,'objective',65535);$session=$this->v->positiveInt($d,'session_id');$project=$this->v->positiveInt($d,'project_id',true);$message=$this->v->positiveInt($d,'origin_message_id',true);$priority=$this->v->oneOf($d['priority']??'normal',['low','normal','high','urgent'],'priority_invalid');$key=isset($d['idempotency_key'])?trim((string)$d['idempotency_key']):null;if($key==='')$key=null;if($key!==null&&mb_strlen($key)>128)throw new TaskValidationException('idempotency_key_invalid');if($key!==null&&($existing=$this->tasks->findOwnedByIdempotencyKey($u,$key)))return['created'=>false,'task'=>$this->taskDto($existing)];$scope=$this->tasks->sessionScope($session,$u);if(!$scope)throw new TaskValidationException('session_invalid');$actual=$scope['project_id_']===null?null:(int)$scope['project_id_'];if($project!==$actual)throw new TaskValidationException('session_project_mismatch');if($project!==null&&!$this->tasks->projectOwned($project,$u))throw new TaskValidationException('project_invalid');if($message!==null&&!$this->tasks->messageOwned($message,$session,$u))throw new TaskValidationException('origin_message_invalid');try{$t=$this->orchestrator->createTask($u,$session,$title,$objective,['project_id'=>$project,'origin_message_id'=>$message,'idempotency_key'=>$key,'priority'=>$priority,'origin_type'=>'manual']);}catch(RuntimeException$e){if($key!==null&&($existing=$this->tasks->findOwnedByIdempotencyKey($u,$key)))return['created'=>false,'task'=>$this->taskDto($existing)];throw$e;}return['created'=>true,'task'=>$this->taskDto($t)];}
 public function cancel(int$u,array$d):array{$t=$this->owned($u,$this->v->publicId($d['public_id']??''));return['task'=>$this->taskDto($this->orchestrator->requestCancellation((int)$t['id_'],$u,$this->v->lock($d)))];}
 public function approve(int$u,array$d):array{$t=$this->owned($u,$this->v->publicId($d['public_id']??''));$approved=$this->orchestrator->approveChatTask((int)$t['id_'],$u,$this->v->lock($d));$step=$this->steps->findByKey((int)$t['id_'],'respond');$input=is_array($step)?json_decode((string)($step['input_json']??''),true):null;return['task'=>$this->taskDto($approved),'execution_mode'=>is_array($input)&&($input['execution_mode']??'sync')==='async'?'async':'sync'];}
 public function reject(int$u,array$d):array{$t=$this->owned($u,$this->v->publicId($d['public_id']??''));return['task'=>$this->taskDto($this->orchestrator->rejectChatTask((int)$t['id_'],$u,$this->v->lock($d)))];}
 public function approveStep(int$u,array$d):array{if(!$this->stepApproval)throw new RuntimeException('approval_service_unavailable');return$this->stepApproval->decide($u,$this->v->publicId($d['public_id']??''),$this->stepKey($d),$this->v->lock($d),true);}
 public function rejectStep(int$u,array$d):array{if(!$this->stepApproval)throw new RuntimeException('approval_service_unavailable');return$this->stepApproval->decide($u,$this->v->publicId($d['public_id']??''),$this->stepKey($d),$this->v->lock($d),false);}
 public function approveTool(int$u,array$d):array{return$this->decideTool($u,$d,true);}
 public function rejectTool(int$u,array$d):array{return$this->decideTool($u,$d,false);}
 public function addDependency(int$u,array$d):array{if(!$this->dependencyService)throw new RuntimeException('dependency_service_unavailable');$task=$this->v->publicId($d['public_id']??'');$required=$this->v->publicId($d['depends_on_public_id']??'');$this->dependencyService->add($u,$task,$required,(string)($d['condition']??'completed'));return['added'=>true];}
 public function removeDependency(int$u,array$d):array{if(!$this->dependencyService)throw new RuntimeException('dependency_service_unavailable');$this->dependencyService->remove($u,$this->v->publicId($d['public_id']??''),$this->v->publicId($d['depends_on_public_id']??''));return['removed'=>true];}
 public function retry(int$u,array$d):array{$t=$this->owned($u,$this->v->publicId($d['public_id']??''));return['task'=>$this->taskDto($this->orchestrator->retryTask((int)$t['id_'],$u,$this->v->lock($d)))];}
 private function owned(int$u,string$p):array{return$this->tasks->findOwnedByPublicId($p,$u)??throw new TaskNotFoundException('not_found');}
 private function stepKey(array$d):string{$k=trim((string)($d['step_key']??''));if(!preg_match('/^[a-z][a-z0-9_-]{0,63}$/D',$k))throw new TaskValidationException('step_key_invalid');return$k;}
 private function decideTool(int$u,array$d,bool$approved):array{if(!$this->toolApproval)throw new RuntimeException('tool_approval_service_unavailable');$fingerprint=(string)($d['fingerprint']??'');if(preg_match('/^[a-f0-9]{64}$/D',$fingerprint)!==1)throw new TaskValidationException('tool_approval_fingerprint_invalid');return$this->toolApproval->decide($u,$this->v->publicId($d['public_id']??''),$this->stepKey($d),$this->v->lock($d),$fingerprint,$approved);}
 private function taskDto(array$r):array{$dto=['public_id'=>$r['public_id'],'project_id'=>$r['project_id_']===null?null:(int)$r['project_id_'],'session_id'=>(int)$r['session_id_'],'origin_message_id'=>$r['origin_message_id_']===null?null:(int)$r['origin_message_id_'],'result_message_id'=>$r['result_message_id_']===null?null:(int)$r['result_message_id_'],'origin_type'=>$r['origin_type'],'title'=>$r['title'],'objective'=>$r['objective'],'status'=>$r['status'],'priority'=>$r['priority'],'progress_percent'=>(int)$r['progress_percent'],'max_attempts'=>(int)$r['max_attempts'],'attempt_count'=>(int)$r['attempt_count'],'lock_version'=>(int)$r['lock_version'],'scheduled_at'=>$r['scheduled_at'],'started_at'=>$r['started_at'],'due_at'=>$r['due_at'],'completed_at'=>$r['completed_at'],'cancel_requested_at'=>$r['cancel_requested_at'],'cancelled_at'=>$r['cancelled_at'],'result_summary'=>$r['result_summary'],'error_code'=>$r['error_code'],'error_message'=>$r['error_message'],'created_at'=>$r['created_at'],'updated_at'=>$r['updated_at']];$dto['error_message']=$this->safeError($dto['error_message']);$dto['result_summary']=$this->safeSummary($dto['result_summary']);if(array_key_exists('current_step_key',$r))$dto['current_step']=$r['current_step_key']===null?null:['step_key'=>(string)$r['current_step_key'],'title'=>(string)$r['current_step_title'],'step_type'=>(string)$r['current_step_type'],'status'=>(string)$r['current_step_status'],'agent_key'=>$r['current_step_agent_key']===null?null:(string)$r['current_step_agent_key'],'model_id'=>$r['current_step_model_id']===null?null:(string)$r['current_step_model_id'],'wait_until'=>$this->waitUntil((string)$r['current_step_type'],$r['current_step_checkpoint_json']??null)];return$dto;}
 private function stepDto(array$r):array{$dto=array_intersect_key($r,array_flip(['position','step_key','title','description','step_type','status','progress_percent','agent_key','model_id','output_summary','error_message','attempt_count','max_attempts','lock_version','started_at','completed_at','created_at','updated_at']));$dto['error_message']=$this->safeError($dto['error_message']??null);$dto['output_summary']=$this->safeSummary($dto['output_summary']??null);$dto['wait_until']=$this->waitUntil((string)$r['step_type'],$r['checkpoint_json']??null);$dto['approval']=$this->approvalPresenter->present($r);return$dto;}
 private function waitUntil(string$type,mixed$checkpoint):?string{if($type!=='wait'||!is_string($checkpoint)||$checkpoint==='')return null;$decoded=json_decode($checkpoint,true);$value=is_array($decoded)?($decoded['wait_until']??null):null;return is_string($value)&&preg_match('/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|[+-]\d{2}:?\d{2})?$/D',$value)===1?$value:null;}
 private function executionDto(array$r):array{$dto=array_intersect_key($r,array_flip(['trace_id','attempt_number','agent_key','model_id','status','started_at','heartbeat_at','finished_at','created_at','step_key','step_title']));$dto['error_message']=$this->safeError($r['error_message']??null);return$dto;}
 private function eventDto(array$r):array{return array_intersect_key($r,array_flip(['actor_type','event_key','from_status','to_status','summary','created_at','step_key','step_title','execution_attempt','execution_trace_id']));}
 private function artifactDto(array$r,?array$resource=null,?array$execution=null,?array$step=null):array{$type=(string)$r['resource_type'];$public=null;if($resource!==null){if(in_array($type,['project_source','file_s3'],true))$public=['filename'=>(string)$resource['filename']];elseif($type==='source_chunk')$public=['filename'=>(string)$resource['filename'],'name'=>$resource['name']===null?null:(string)$resource['name'],'start_line'=>(int)$resource['start_line'],'end_line'=>(int)$resource['end_line']];elseif($type==='file_version')$public=['filename'=>(string)$resource['filename'],'version'=>(string)$resource['version']];}$dto=['relation'=>(string)$r['relation'],'resource_type'=>$type,'resource'=>$public,'created_at'=>(string)$r['created_at']];if($execution!==null)$dto['execution_attempt']=(int)$execution['attempt_number'];if($step!==null){$dto['step_key']=(string)$step['step_key'];$dto['step_title']=(string)$step['title'];}return$dto;}
 private function safeSummary(mixed$value):?string{if(!is_string($value)||trim($value)==='')return null;$text=trim($value);return mb_strlen($text)>1000?mb_substr($text,0,997).'…':$text;}
 private function safeError(mixed$value):?string{if(!is_string($value)||trim($value)==='')return null;$text=preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/u',' ',trim($value))??'';$text=preg_replace('/\b(password|token|secret|authorization|api[_-]?key)\s*[:=]\s*[^\s,;]+/iu','$1=[oculto]',$text)??'';if(preg_match('/\b(?:SELECT|INSERT|UPDATE|DELETE)\b.+\b(?:FROM|INTO|SET)\b/iu',$text))return'Detalle técnico oculto.';$line=trim(strtok($text,"\n")?:'');return mb_strlen($line)>300?mb_substr($line,0,297).'…':$line;}
}
