<?php
declare(strict_types=1);
final class TaskRecurrenceApplicationService implements TaskRecurrenceAdministration{
 public function __construct(private TaskRecurrenceRuleRepository$rules,private TaskRecurrenceOccurrenceRepository$occurrences,private TaskRecurrenceService$service,private TaskInputValidator$validator){}
 public function recurrenceList(int$u,array$q):array{$limit=isset($q['limit'])?(int)$q['limit']:50;$offset=isset($q['offset'])?(int)$q['offset']:0;if($limit<1||$limit>100||$offset<0)throw new TaskValidationException('pagination_invalid');$rows=$this->rules->listOwned($u,$limit,$offset);return['rules'=>array_map(fn($r)=>$this->ruleDto($r),$rows),'total'=>$this->rules->countOwned($u),'limit'=>$limit,'offset'=>$offset];}
 public function recurrenceDetail(int$u,string$p):array{$rule=$this->owned($u,$this->validator->publicId($p));return['rule'=>$this->ruleDto($rule),'occurrences'=>array_map(fn($r)=>$this->occurrenceDto($r),$this->occurrences->listRecentOwned((int)$rule['id_'],$u,25)),'history'=>['limit'=>25]];}
 public function recurrenceCreate(int$u,array$d):array{unset($d['user_id'],$d['next_occurrence_at'],$d['lock_version']);$created=$this->service->createRule($u,$d,new DateTimeImmutable('now',new DateTimeZone('UTC')));return['rule'=>$this->ruleDto($this->owned($u,(string)$created['public_id']))];}
 public function recurrencePause(int$u,array$d):array{$r=$this->owned($u,$this->validator->publicId($d['public_id']??''));$updated=$this->service->pause($u,(int)$r['id_'],$this->validator->lock($d));return['rule'=>$this->ruleDto($this->owned($u,(string)$updated['public_id']))];}
 public function recurrenceResume(int$u,array$d):array{$r=$this->owned($u,$this->validator->publicId($d['public_id']??''));$updated=$this->service->resume($u,(int)$r['id_'],$this->validator->lock($d),new DateTimeImmutable('now',new DateTimeZone('UTC')));return['rule'=>$this->ruleDto($this->owned($u,(string)$updated['public_id']))];}
 public function recurrenceCancel(int$u,array$d):array{$r=$this->owned($u,$this->validator->publicId($d['public_id']??''));$updated=$this->service->cancel($u,(int)$r['id_'],$this->validator->lock($d));return['rule'=>$this->ruleDto($this->owned($u,(string)$updated['public_id']))];}
 private function owned(int$u,string$p):array{return$this->rules->findOwnedByPublicIdWithScope($p,$u)??throw new TaskNotFoundException('not_found');}
 private function ruleDto(array$r):array{return['public_id'=>(string)$r['public_id'],'status'=>(string)$r['status'],'frequency'=>(string)$r['frequency'],'weekday'=>$r['weekday']===null?null:(int)$r['weekday'],'local_time'=>(string)$r['local_time'],'timezone'=>(string)$r['timezone'],'next_occurrence_at'=>(string)$r['next_occurrence_at'],'misfire_policy'=>(string)$r['misfire_policy'],'task_title'=>(string)$r['task_title'],'task_objective'=>(string)$r['task_objective'],'task_priority'=>(string)$r['task_priority'],'task_mode'=>(string)$r['task_mode'],'project_name'=>$r['project_name']===null?null:(string)$r['project_name'],'session_title'=>(string)$r['session_title'],'lock_version'=>(int)$r['lock_version'],'created_at'=>(string)$r['created_at'],'updated_at'=>(string)$r['updated_at']];}
 private function occurrenceDto(array$r):array{$known=['task_validation_failed','task_materialization_failed'];$failure=in_array((string)($r['failure_code']??''),$known,true)?(string)$r['failure_code']:null;return['logical_occurrence_at'=>(string)$r['logical_occurrence_at'],'status'=>(string)$r['status'],'task_public_id'=>$r['task_public_id']===null?null:(string)$r['task_public_id'],'failure_code'=>$failure,'created_at'=>(string)$r['created_at'],'updated_at'=>(string)$r['updated_at']];}
}
