<?php
header('Content-Type: application/json; charset=utf-8');
if(session_status()===PHP_SESSION_NONE)session_start();
require_once __DIR__.'/app_bootstrap.php';
require_once __DIR__.'/S3Manager.php';
function del_uid():int{foreach(['user_id_','user_id','id_usuario','id_user','id']as$k)if(isset($_SESSION[$k])&&ctype_digit((string)$_SESSION[$k]))return(int)$_SESSION[$k];return 0;}
function del_admin(string$r):bool{return in_array(strtolower(trim($r)),['admin','administrator','administración','soporte','support'],true);}
function del_key(array$f):string{$ruta=rtrim(str_replace('\\','/',trim((string)$f['Ruta'])),'/').'/';$enc=ltrim(str_replace('\\','/',trim((string)$f['Encriptado'])),'/');return strpos($enc,$ruta)===0?$enc:$ruta.$enc;}
function del_cleanup_chat_memory(mysqli$db,int$userId,int$fileId,string$key):array{$ids=[];$s=$db->prepare("SELECT scb.id_ FROM SessionContextBlocks scb JOIN ChatSessions cs ON cs.id_=scb.session_id_ WHERE cs.user_id_=? AND scb.block_type IN ('file','file_chunk') AND (scb.s3_path=? OR CAST(JSON_UNQUOTE(JSON_EXTRACT(scb.source_ids,'$.files3_id')) AS UNSIGNED)=?)");if(!$s)return['blocks'=>0,'jobs'=>0];$s->bind_param('isi',$userId,$key,$fileId);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$ids[]=(int)$x['id_'];$s->close();if(!$ids)return['blocks'=>0,'jobs'=>0];$ph=implode(',',array_fill(0,count($ids),'?'));$types=str_repeat('i',count($ids));$jobs=0;$d=$db->prepare("DELETE FROM EmbeddingJobs WHERE target_type='session_block' AND target_id IN ($ph)");if($d){$d->bind_param($types,...$ids);$d->execute();$jobs=$d->affected_rows;$d->close();}$d=$db->prepare("DELETE FROM SessionContextBlocks WHERE id_ IN ($ph)");$d->bind_param($types,...$ids);$d->execute();$blocks=$d->affected_rows;$d->close();return['blocks'=>$blocks,'jobs'=>$jobs];}
try{
 if(($_SERVER['REQUEST_METHOD']??'')!=='POST')throw new RuntimeException('Método no permitido');$uid=del_uid();if($uid<=0){http_response_code(401);echo json_encode(['ok'=>false,'estado'=>'error','error'=>'Sesión inválida']);exit;}$admin=del_admin((string)($_SESSION['role']??$_SESSION['rol']??''));$ref=null;if(isset($_POST['file_id'])&&ctype_digit((string)$_POST['file_id']))$ref=(int)$_POST['file_id'];elseif(!empty($_POST['archivo']))$ref=trim((string)$_POST['archivo']);if(!$ref)throw new RuntimeException('Falta la referencia del archivo');
 if(is_int($ref)){$sql="SELECT id_,user_id_,Nombre,Ruta,Encriptado FROM FileS3 WHERE id_=?".($admin?'':' AND user_id_=?')." LIMIT 1";$s=$db_connection->prepare($sql);if($admin)$s->bind_param('i',$ref);else$s->bind_param('ii',$ref,$uid);}else{$key=$ref;$base=basename($ref);$sql="SELECT id_,user_id_,Nombre,Ruta,Encriptado FROM FileS3 WHERE ".($admin?'':'user_id_=? AND ')."(Encriptado=? OR Encriptado=? OR CONCAT(TRIM(TRAILING '/' FROM Ruta),'/',Encriptado)=?) LIMIT 1";$s=$db_connection->prepare($sql);if($admin)$s->bind_param('sss',$key,$base,$key);else$s->bind_param('isss',$uid,$key,$base,$key);}if(!$s||!$s->execute())throw new RuntimeException('No se pudo validar el archivo');$file=$s->get_result()->fetch_assoc();$s->close();if(!$file){http_response_code(403);echo json_encode(['ok'=>false,'estado'=>'error','error'=>'No tienes permisos para eliminar este archivo']);exit;}
 $realId=(int)$file['id_'];$owner=(int)$file['user_id_'];$key=del_key($file);$manager=new S3Manager();$result=$manager->deleteFile($realId);
 $db_connection->begin_transaction();try{$cleanup=del_cleanup_chat_memory($db_connection,$owner,$realId,$key);$db_connection->commit();}catch(Throwable$e){$db_connection->rollback();throw new RuntimeException('El archivo se eliminó, pero falló la limpieza de memoria indexada: '.$e->getMessage());}
 echo json_encode(['ok'=>true,'estado'=>'ok','mensaje'=>'Archivo eliminado correctamente; también se retiró su memoria indexada.','data'=>$result,'cleanup'=>$cleanup],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
}catch(Throwable$e){http_response_code(500);echo json_encode(['ok'=>false,'estado'=>'error','mensaje'=>$e->getMessage(),'error'=>$e->getMessage()],JSON_UNESCAPED_UNICODE);}
