<?php
header('Content-Type: application/json; charset=utf-8');
if(session_status()===PHP_SESSION_NONE)session_start();
require_once __DIR__.'/app_bootstrap.php';
require_once __DIR__.'/S3Manager.php';
function save_uid():int{foreach(['user_id_','user_id','id_usuario','id_user','id']as$k)if(isset($_SESSION[$k])&&ctype_digit((string)$_SESSION[$k]))return(int)$_SESSION[$k];return 0;}
function save_find_owned(mysqli$db,int$uid,string$key):?array{$base=basename(str_replace('\\','/',$key));$s=$db->prepare("SELECT id_,Ruta,Encriptado,Nombre FROM FileS3 WHERE user_id_=? AND Found=1 AND (Encriptado=? OR Encriptado=? OR CONCAT(TRIM(TRAILING '/' FROM REPLACE(Ruta,'\\\\','/')),'/',TRIM(LEADING '/' FROM REPLACE(Encriptado,'\\\\','/')))=?) ORDER BY id_ DESC LIMIT 10");if(!$s)return null;$s->bind_param('isss',$uid,$key,$base,$key);$s->execute();$r=$s->get_result();$row=$r->fetch_assoc();$s->close();return$row?:null;}
function save_real_key(array$f):string{$ruta=rtrim(str_replace('\\','/',trim((string)$f['Ruta'])),'/').'/';$enc=ltrim(str_replace('\\','/',trim((string)$f['Encriptado'])),'/');return strpos($enc,$ruta)===0?$enc:$ruta.$enc;}
function save_invalidate_chat_index(mysqli$db,int$fileId,string$key):array{$ids=[];$s=$db->prepare("SELECT id_ FROM SessionContextBlocks WHERE block_type IN ('file','file_chunk') AND (s3_path=? OR CAST(JSON_UNQUOTE(JSON_EXTRACT(source_ids,'$.files3_id')) AS UNSIGNED)=?)");if(!$s)return['invalidated'=>0,'jobs_removed'=>0];$s->bind_param('si',$key,$fileId);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$ids[]=(int)$x['id_'];$s->close();if(!$ids)return['invalidated'=>0,'jobs_removed'=>0];$ph=implode(',',array_fill(0,count($ids),'?'));$types=str_repeat('i',count($ids));$jobs=0;$d=$db->prepare("DELETE FROM EmbeddingJobs WHERE target_type='session_block' AND target_id IN ($ph)");if($d){$d->bind_param($types,...$ids);$d->execute();$jobs=$d->affected_rows;$d->close();}$d=$db->prepare("DELETE FROM SessionContextBlocks WHERE id_ IN ($ph)");$d->bind_param($types,...$ids);$d->execute();$n=$d->affected_rows;$d->close();return['invalidated'=>$n,'jobs_removed'=>$jobs];}
try{
 if(($_SERVER['REQUEST_METHOD']??'')!=='POST')throw new RuntimeException('Método no permitido');$uid=save_uid();if($uid<=0){http_response_code(401);throw new RuntimeException('Sesión inválida');}$requested=trim((string)($_POST['archivo']??''));if($requested==='')throw new RuntimeException('Falta la clave del archivo.');if(!array_key_exists('contenido',$_POST))throw new RuntimeException('Falta contenido.');$file=save_find_owned($db_connection,$uid,$requested);if(!$file){http_response_code(403);throw new RuntimeException('Archivo no encontrado o sin permisos.');}
 $manager=new S3Manager();$result=$manager->updateTextFile((int)$file['id_'],(string)$_POST['contenido']);$key=save_real_key($file);$cleanup=['invalidated'=>0,'jobs_removed'=>0];
 if(strpos($key,'Data/Chat/Uploads/'.$uid.'/')===0){$db_connection->begin_transaction();try{$cleanup=save_invalidate_chat_index($db_connection,(int)$file['id_'],$key);$db_connection->commit();}catch(Throwable$e){$db_connection->rollback();throw new RuntimeException('Archivo guardado, pero no se pudo invalidar su índice anterior: '.$e->getMessage());}}
 echo json_encode(['estado'=>'ok','data'=>$result,'index_cleanup'=>$cleanup,'needs_reindex'=>$cleanup['invalidated']>0,'mensaje'=>$cleanup['invalidated']>0?'Guardado. La indexación anterior fue retirada; vuelve a indexar/crear semántica para usar el contenido nuevo.':'Guardado.'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
}catch(Throwable$e){if(http_response_code()<400)http_response_code(500);echo json_encode(['estado'=>'error','mensaje'=>$e->getMessage()],JSON_UNESCAPED_UNICODE);}
