<?php
declare(strict_types=1);if(PHP_SAPI!=='cli')exit(1);require_once __DIR__.'/../includes/Tasks/bootstrap.php';
final class MemoryPolicyStore implements AutonomyPolicyStoreInterface{
 public ?array$row=null;public function __construct(public int$owner=7,public int$project=9){}
 public function findOwned(int$u,int$p):?array{return$u===$this->owner&&$p===$this->project?$this->row:null;}
 public function createDefault(int$u,int$p,string$id):array{if($u!==$this->owner||$p!==$this->project)throw new TaskNotFoundException('project_not_found');return$this->row=['public_id'=>$id,'user_id_'=>$u,'project_id_'=>$p,'mode'=>'disabled','status'=>'active','stop_reason'=>null,'lock_version'=>0]+array_fill_keys(array_keys(AutonomyPolicy::DEFAULTS),null);}
 public function updateOwned(int$u,int$p,int$l,array$c):array{if($u!==$this->owner||$p!==$this->project||!$this->row)throw new TaskNotFoundException('not_found');if($l!==(int)$this->row['lock_version'])throw new TaskConcurrencyException('autonomy_policy_conflict');$this->row=array_replace($this->row,$c);$this->row['lock_version']++;return$this->row;}
}
final class MemoryBudgetStore implements AutonomyBudgetStoreInterface{
 public ?array$cycle=null;public array$reservations=[];private int$seq=0;
 public function startCycle(int$u,int$p,string$id):array{return$this->cycle??=$this->blank($u,$p,$id);}
 public function findActiveCycle(int$u,int$p):?array{return$this->cycle&&$this->cycle['user_id_']===$u&&$this->cycle['project_id_']===$p?$this->cycle:null;}
 public function reserve(int$u,int$p,string$cycle,string$key,AutonomyBudgetRequest$r,AutonomyPolicy$policy):AutonomyBudgetReservation{if(!$this->cycle||$this->cycle['public_id']!==$cycle||$this->cycle['user_id_']!==$u||$this->cycle['project_id_']!==$p)return new AutonomyBudgetReservation(false,'budget_unavailable',null,false,[],[]);if(isset($this->reservations[$key])){$x=$this->reservations[$key];if($x['values']!==$r->values())throw new TaskConcurrencyException('autonomy_idempotency_conflict');return new AutonomyBudgetReservation($x['status']!=='released',$x['status']==='released'?'reservation_released':'reserved',$x['public'],true,$this->usage(),$this->remaining($policy));}$v=$r->values();if($r->descendantDepth>$policy->limits['max_descendant_depth'])return$this->deny('depth_limit_reached',$policy);$map=['decisions'=>['decisions_consumed','max_decisions_per_cycle','decision_limit_reached'],'tasks'=>['tasks_consumed','max_tasks_per_cycle','task_limit_reached'],'replans'=>['replans_consumed','max_replans_per_cycle','replan_limit_reached'],'input_tokens'=>['input_tokens_consumed','max_input_tokens','input_token_limit_reached'],'output_tokens'=>['output_tokens_consumed','max_output_tokens','output_token_limit_reached'],'tool_calls'=>['tool_calls_consumed','max_tool_calls','tool_limit_reached'],'write_tool_calls'=>['write_tool_calls_consumed','max_write_tool_calls','write_limit_reached'],'runtime_seconds'=>['runtime_seconds_consumed','max_runtime_seconds','runtime_limit_reached']];foreach($map as$k=>[$counter,$limit,$reason])if($this->cycle[$counter]+$v[$k]>$policy->limits[$limit])return$this->deny($reason,$policy);$public='22222222-2222-4222-8222-'.str_pad((string)++$this->seq,12,'0',STR_PAD_LEFT);foreach($map as$k=>[$counter])$this->cycle[$counter]+=$v[$k];$this->reservations[$key]=['public'=>$public,'values'=>$v,'status'=>'reserved'];return new AutonomyBudgetReservation(true,'reserved',$public,false,$this->usage(),$this->remaining($policy));}
 public function consume(int$u,int$p,string$r):array{return$this->transition($r,'consumed',false);}
 public function release(int$u,int$p,string$r):array{return$this->transition($r,'released',true);}
 private function transition(string$public,string$to,bool$refund):array{foreach($this->reservations as&$x)if($x['public']===$public){if($x['status']===$to)return$x;if($x['status']!=='reserved')throw new TaskTransitionException('reservation_not_transitionable');$x['status']=$to;if($refund){$m=['decisions'=>'decisions_consumed','tasks'=>'tasks_consumed','replans'=>'replans_consumed','input_tokens'=>'input_tokens_consumed','output_tokens'=>'output_tokens_consumed','tool_calls'=>'tool_calls_consumed','write_tool_calls'=>'write_tool_calls_consumed','runtime_seconds'=>'runtime_seconds_consumed'];foreach($m as$k=>$c)$this->cycle[$c]-=$x['values'][$k];}return$x;}throw new TaskNotFoundException('reservation_not_found');}
 private function blank(int$u,int$p,string$id):array{return['public_id'=>$id,'user_id_'=>$u,'project_id_'=>$p,'status'=>'active','decisions_consumed'=>0,'tasks_consumed'=>0,'replans_consumed'=>0,'input_tokens_consumed'=>0,'output_tokens_consumed'=>0,'tool_calls_consumed'=>0,'write_tool_calls_consumed'=>0,'runtime_seconds_consumed'=>0];}
 private function usage():array{return array_combine(['decisions','tasks','replans','input_tokens','output_tokens','tool_calls','write_tool_calls','runtime_seconds'],array_map(fn($k)=>$this->cycle[$k.'_consumed'],['decisions','tasks','replans','input_tokens','output_tokens','tool_calls','write_tool_calls','runtime_seconds']));}
 private function remaining(AutonomyPolicy$p):array{$u=$this->usage();$limits=['decisions'=>'max_decisions_per_cycle','tasks'=>'max_tasks_per_cycle','replans'=>'max_replans_per_cycle','input_tokens'=>'max_input_tokens','output_tokens'=>'max_output_tokens','tool_calls'=>'max_tool_calls','write_tool_calls'=>'max_write_tool_calls','runtime_seconds'=>'max_runtime_seconds'];$o=[];foreach($limits as$k=>$l)$o[$k]=max(0,$p->limits[$l]-$u[$k]);return$o;}
 private function deny(string$r,AutonomyPolicy$p):AutonomyBudgetReservation{return new AutonomyBudgetReservation(false,$r,null,false,$this->usage(),$this->remaining($p));}
}
$pass=0;$fail=0;$ok=function(bool$v,string$n)use(&$pass,&$fail){echo($v?'PASS ':'FAIL ').$n."\n";$v?$pass++:$fail++;};$store=new MemoryPolicyStore();$policies=new AutonomyPolicyService($store);$p=$policies->getOrCreate(7,9);$ok($p->mode==='disabled'&&$p->status==='active'&&$p->limits===AutonomyPolicy::DEFAULTS,'default seguro disabled');try{$policies->getOrCreate(8,9);$ok(false,'cross user');}catch(TaskNotFoundException){$ok(true,'cross-user rechazado');}try{$policies->getOrCreate(7,10);$ok(false,'cross project');}catch(TaskNotFoundException){$ok(true,'cross-project rechazado');}
$p=$policies->update(7,9,0,'supervised',['max_tasks_per_cycle'=>99999]);$ok($p->mode==='supervised'&&$p->limits['max_tasks_per_cycle']===50,'supervised y ceiling');$p=$policies->pause(7,9,1);$ok($p->status==='paused','paused');$p=$policies->resume(7,9,2);$ok($p->status==='active','resumed');$p=$policies->stop(7,9,3,'safety_stop');$ok($p->status==='stopped'&&$p->stopReason==='safety_stop','stopped');try{$policies->resume(7,9,4);$ok(false,'resume stopped');}catch(TaskTransitionException){$ok(true,'stopped no resume');}try{$policies->update(7,9,3,'automatic');$ok(false,'stale lock');}catch(TaskConcurrencyException){$ok(true,'lock conflict');}$p=$policies->disable(7,9,4);$ok($p->mode==='disabled','disabled');
// Fresh automatic policy with tiny limits exercises every durable counter.
$store2=new MemoryPolicyStore();$pol2=new AutonomyPolicyService($store2);$pol2->getOrCreate(7,9);$limits=['max_tasks_per_cycle'=>1,'max_decisions_per_cycle'=>1,'max_descendant_depth'=>1,'max_replans_per_cycle'=>1,'max_runtime_seconds'=>1,'max_input_tokens'=>1,'max_output_tokens'=>1,'max_tool_calls'=>1,'max_write_tool_calls'=>1];$auto=$pol2->update(7,9,0,'automatic',$limits);$mem=new MemoryBudgetStore();$budgets=new AutonomyBudgetService($pol2,$mem);$cycle=$budgets->startCycle(7,9);$ok(TaskPublicId::isValid($cycle['public_id']),'cycle durable public identity');$inspection=$budgets->inspect(7,9);$ok(!isset($inspection['cycle']['id_'])&&isset($inspection['cycle']['usage'],$inspection['cycle']['remaining'],$inspection['cycle']['limits']),'inspect seguro para UI futura');
$r=$budgets->reserve(7,9,$cycle['public_id'],'decision-1',new AutonomyBudgetRequest(decisions:1));$ok($r->allowed&&$r->usage['decisions']===1,'reserve decision');$retry=$budgets->reserve(7,9,$cycle['public_id'],'decision-1',new AutonomyBudgetRequest(decisions:1));$ok($retry->allowed&&$retry->idempotent&&$retry->usage['decisions']===1,'retry idempotente no cobra doble');try{$budgets->reserve(7,9,$cycle['public_id'],'decision-1',new AutonomyBudgetRequest(tasks:1));$ok(false,'idempotency mismatch');}catch(TaskConcurrencyException){$ok(true,'misma key payload distinto conflict');}$denied=$budgets->reserve(7,9,$cycle['public_id'],'decision-2',new AutonomyBudgetRequest(decisions:1));$ok(!$denied->allowed&&$denied->reasonCode==='decision_limit_reached'&&$denied->usage['decisions']===1,'decision exhausted sin consumo');$budgets->release(7,9,$r->reservationPublicId);$ok($mem->cycle['decisions_consumed']===0,'release devuelve reserva');$releasedRetry=$budgets->reserve(7,9,$cycle['public_id'],'decision-1',new AutonomyBudgetRequest(decisions:1));$ok(!$releasedRetry->allowed&&$releasedRetry->idempotent&&$mem->cycle['decisions_consumed']===0,'retry released no re-reserva');
$cases=[['task',new AutonomyBudgetRequest(tasks:1),new AutonomyBudgetRequest(tasks:1),'task_limit_reached'],['replan',new AutonomyBudgetRequest(replans:1),new AutonomyBudgetRequest(replans:1),'replan_limit_reached'],['input',new AutonomyBudgetRequest(inputTokens:1),new AutonomyBudgetRequest(inputTokens:1),'input_token_limit_reached'],['output',new AutonomyBudgetRequest(outputTokens:1),new AutonomyBudgetRequest(outputTokens:1),'output_token_limit_reached'],['tool',new AutonomyBudgetRequest(toolCalls:1),new AutonomyBudgetRequest(toolCalls:1),'tool_limit_reached'],['write',new AutonomyBudgetRequest(writeToolCalls:1),new AutonomyBudgetRequest(writeToolCalls:1),'write_limit_reached'],['runtime',new AutonomyBudgetRequest(runtimeSeconds:1),new AutonomyBudgetRequest(runtimeSeconds:1),'runtime_limit_reached']];foreach($cases as[$name,$first,$second,$reason]){$a=$budgets->reserve(7,9,$cycle['public_id'],$name.'-1',$first);$b=$budgets->reserve(7,9,$cycle['public_id'],$name.'-2',$second);$ok($a->allowed&&!$b->allowed&&$b->reasonCode===$reason,$name.' limit atomic');}$depth=$budgets->reserve(7,9,$cycle['public_id'],'depth',new AutonomyBudgetRequest(tasks:1,descendantDepth:2));$ok(!$depth->allowed&&$depth->reasonCode==='depth_limit_reached','depth exhausted');$different=$budgets->reserve(7,9,$cycle['public_id'],'different-key',new AutonomyBudgetRequest(decisions:1));$ok($different->allowed,'different key consumes separately after release');$budgets->consume(7,9,$different->reservationPublicId);$again=$budgets->consume(7,9,$different->reservationPublicId);$ok($again['status']==='consumed','consume idempotente');
// Authorization never spawns; only propose_task can reserve.
$store3=new MemoryPolicyStore();$pol3=new AutonomyPolicyService($store3);$pol3->getOrCreate(7,9);$mem3=new MemoryBudgetStore();$budget3=new AutonomyBudgetService($pol3,$mem3);$auth=new NextWorkAuthorizationService($pol3,$budget3);$stop=new NextWorkDecision('stop','done',[]);$ask=NextWorkDecision::safeAsk();$proposal=new NextWorkDecision('propose_task','next',[],null,'Title','Objective');foreach([$stop,$ask]as$d){$x=$auth->authorize($d,7,9,'none','key',0,'completed');$ok($x->status==='denied'&&$mem3->reservations===[],'non-propose denied sin reserva');}$x=$auth->authorize($proposal,7,9,'none','key',0,'completed');$ok($x->reasonCode==='autonomy_disabled','propose disabled denied');$pol3->update(7,9,0,'supervised');$x=$auth->authorize($proposal,7,9,'none','key',0,'completed');$ok($x->status==='requires_approval'&&$mem3->reservations===[],'supervised requires approval sin reserva');$pol3->pause(7,9,1);$ok($auth->authorize($proposal,7,9,'none','key',0,'completed')->reasonCode==='autonomy_paused','paused denied');$pol3->resume(7,9,2);$pol3->update(7,9,3,'automatic',['max_tasks_per_cycle'=>1]);$cycle3=$budget3->startCycle(7,9);$x=$auth->authorize($proposal,7,9,$cycle3['public_id'],'auth-1',0,'completed');$ok($x->status==='allowed'&&TaskPublicId::isValid($x->reservationPublicId),'automatic budget allowed');$x=$auth->authorize($proposal,7,9,$cycle3['public_id'],'auth-2',0,'completed');$ok($x->status==='denied'&&$x->reasonCode==='task_limit_reached','automatic exhausted denied');$x=$auth->authorize($proposal,7,9,$cycle3['public_id'],'cancelled',0,'cancelled');$ok($x->status==='requires_approval','cancelled no bypass');$x=$auth->authorize($proposal,8,9,$cycle3['public_id'],'foreign',0,'completed');$ok($x->reasonCode==='invalid_scope','invalid scope denied');
$repo=file_get_contents(__DIR__.'/../includes/Tasks/AutonomyBudgetRepository.php');$authSource=file_get_contents(__DIR__.'/../includes/Tasks/NextWorkAuthorizationService.php');$sql=file_get_contents(__DIR__.'/../sql/fase11b_project_autonomy.sql');$ok(str_contains($repo,'begin_transaction')&&str_contains($repo,'FOR UPDATE')&&str_contains($sql,'uq_project_autonomy_reservation_idempotency'),'SQL atomic + UNIQUE idempotency');$ok(!str_contains($authSource,'createTask')&&!str_contains($authSource,'createManualTask')&&!str_contains($authSource,'TaskWorker')&&!str_contains($authSource,'ToolRegistry'),'authorization no crea ni ejecuta');$ok(str_contains($sql,'active_project_id_')&&str_contains($sql,'uq_project_autonomy_cycle_active'),'un ciclo active concurrente por Project');$dump=file_get_contents(__DIR__.'/../../adbbmis1_Cloud.sql');$ok(str_contains($dump,'ProjectAutonomyPolicies')&&str_contains($dump,'ProjectAutonomyCycles')&&str_contains($dump,'ProjectAutonomyReservations'),'schema consolidado 11B');
echo"Resultado: $pass PASS, $fail FAIL.\nSKIP — MySQL real 11B: TASK_TEST_DB_* no configurado.\n";exit($fail?1:0);
