<?php
declare(strict_types=1);
$runner=__DIR__.'/run_external_mysql_certification.php';$runnerSource=(string)file_get_contents($runner);$safety=(string)file_get_contents(__DIR__.'/support/ExternalMysqlTestSafety.php');$manual=(string)file_get_contents(__DIR__.'/manual/fase12b4_schema_inspection.sql');$passed=0;$failed=0;
$check=function(bool$ok,string$label)use(&$passed,&$failed){echo($ok?'PASS ':'FAIL ').$label."\n";$ok?$passed++:$failed++;};
$check(str_contains($runnerSource,"PHP_SAPI !== 'cli'")&&!str_contains($runnerSource,'$_GET')&&!str_contains($runnerSource,'$_POST'),'external certification is CLI-only with no request credentials');
foreach(['TASK_TEST_DB_HOST','TASK_TEST_DB_PORT','TASK_TEST_DB_USER','TASK_TEST_DB_PASSWORD','TASK_TEST_DB_ALLOW_DESTRUCTIVE']as$key)$check(str_contains($runnerSource,$key),'external runner requires '.$key);
$check(str_contains($runnerSource,"getenv('TASK_TEST_DB_ALLOW_DESTRUCTIVE')!=='1'")&&str_contains($runnerSource,'EXTERNAL MYSQL CERTIFICATION = NOT RUNNABLE'),'missing destructive authorization is refused, not skipped');
$required=['migration_runner_mysql_test.php','supported_upgrade_mysql_test.php','schema_clean_install_test.php','mysql_compatibility_contract_test.php','ai_agent_global_scope_contract_test.php','multiuser_owned_boundaries_test.php','migration_runner_static_contract_test.php','sql_migration_executor_test.php','supported_upgrade_static_contract_test.php','global_ai_admin_policy_test.php','multiuser_identity_static_contract_test.php','first_user_bootstrap_test.php','task_center_autonomy_schema_contract_test.php','task_retry_recovery_coherence_test.php','task_model_tool_wiring_test.php','chat_response_persistence_test.php','task_phase11g2_closure_audit_test.php'];
foreach($required as$file)$check(str_contains($runnerSource,"'{$file}'"),'external runner includes '.$file);
$check(str_contains($runnerSource,"preg_match('/\\bSKIP\\b/'")&&str_contains($runnerSource,'$hasFail||$hasSkip?\'FAIL\':\'PASS\''),'mandatory SKIP prevents global PASS');
foreach(['SUPPORTED UPGRADE','CLEAN INSTALL','SCHEMA PARITY','SECOND APPLY','DRIFT','UNKNOWN HISTORY','PARTIAL STATES','NEGATIVE FIXTURES','LOCK CONTENTION']as$gate)$check(str_contains($runnerSource,"'{$gate}'"),'summary exposes '.$gate);
$check(str_contains($runnerSource,'str_contains(strtolower($version),\'mariadb\')')&&str_contains($runnerSource,'version_compare($match[1],\'8.0.16\',\'<\')'),'runner rejects MariaDB and old MySQL');
$check(str_contains($safety,"'michat_test_12b4_'")&&str_contains($safety,'random_bytes(8)')&&str_contains($safety,'in_array($database, $created, true)'),'temporary database names and cleanup have prefix, entropy and in-memory ownership');
foreach(['migration_runner_mysql_test.php','supported_upgrade_mysql_test.php','schema_clean_install_test.php','mysql_compatibility_contract_test.php']as$file){$source=(string)file_get_contents(__DIR__.'/'.$file);$check(str_contains($source,'requireExternalMysqlDestructiveAuthorization()')&&str_contains($source,'assertExternalMysqlDatabaseOwned('),'destructive harness is guarded: '.$file);}
$check(!preg_match('/^\s*(?:CREATE|ALTER|DROP|INSERT|UPDATE|DELETE|CALL)\b/mi',$manual)&&str_contains($manual,'REPLACE_WITH_CLEAN_TEST_SCHEMA')&&str_contains($manual,'REPLACE_WITH_UPGRADE_TEST_SCHEMA'),'phpMyAdmin helper is read-only and requires explicit schemas');
$environment=array_replace($_ENV,['TASK_TEST_DB_HOST'=>'','TASK_TEST_DB_PORT'=>'','TASK_TEST_DB_USER'=>'','TASK_TEST_DB_PASSWORD'=>'','TASK_TEST_DB_ALLOW_DESTRUCTIVE'=>'']);$process=proc_open([PHP_BINARY,$runner],[['pipe','r'],['pipe','w'],['pipe','w']],$pipes,__DIR__,$environment);$output='';$exit=-1;if(is_resource($process)){fclose($pipes[0]);$output=(string)stream_get_contents($pipes[1]).(string)stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($process);}
$check($exit===2&&str_contains($output,'EXTERNAL MYSQL CERTIFICATION = NOT RUNNABLE')&&!str_contains($output,'EXTERNAL MYSQL CERTIFICATION = PASS'),'runner fails closed without credentials');
$check(substr_count($runnerSource,'MigrationRunner')===0&&substr_count($runnerSource,'MigrationCatalog')===0&&substr_count($runnerSource,'SchemaFingerprint')===0,'orchestrator does not duplicate migration or fingerprint implementations');
$check(!preg_match('/(?:password|passwd)\s*=\s*[\'\"][^\'\"]+[\'\"]/i',$runnerSource.$safety),'no hardcoded password value');
echo"Result: {$passed} passed, {$failed} failed\n";exit($failed?1:0);
