<?php
declare(strict_types=1);require_once __DIR__.'/../includes/Tasks/bootstrap.php';
$pass=0;$fail=0;function c11(bool$c,string$m):void{global$pass,$fail;$c?($pass++):($fail++);echo($c?'PASS':'FAIL')." - $m\n";}
final class CPolicyStore implements AutonomyPolicyStoreInterface{public array$row;function __construct(string$m='automatic',string$s='active',int$d=3){$this->row=['user_id_'=>1,'project_id_'=>10,'public_id'=>TaskPublicId::generate(),'mode'=>$m,'status'=>$s,'stop_reason'=>null,'lock_version'=>0,'max_descendant_depth'=>$d];}function findOwned(int$u,int$p):?array{return$u===1&&$p===10?$this->row:null;}function createDefault(int$u,int$p,string$i):array{return$this->row;}function updateOwned(int$u,int$p,int$l,array$c):array{return$this->row=array_merge($this->row,$c);}}
final class CBudgetStore implements AutonomyBudgetStoreInterface{public array$rows=[];public int$reserves=0,$consumes=0,$releases=0;public bool$deny=false;function startCycle(int$u,int$p,string$i):array{return[];}function findActiveCycle(int$u,int$p):?array{return null;}function reserve(int$u,int$p,string$c,string$k,AutonomyBudgetRequest$r,AutonomyPolicy$policy):AutonomyBudgetReservation{if(isset($this->rows[$k]))return$this->rows[$k];$this->reserves++;$reason=$this->deny?'decision_limit_reached':'budget_reserved';return$this->rows[$k]=new AutonomyBudgetReservation(!$this->deny,$reason,$this->deny?null:TaskPublicId::generate(),false,[],[]);}function consume(int$u,int$p,string$r):array{$this->consumes++;return['status'=>'consumed'];}function release(int$u,int$p,string$r):array{$this->releases++;return['status'=>'released'];}}
final class CContinuationStore implements PostTaskContinuationStoreInterface{public array$claims=[],$finished=[],$events=[],$closed=[];public int$discoveries=0,$retries=0,$records=0;function enrollRoot(int$u,int$p,string$t,string$c):array{return['task_public_id'=>$t,'cycle_public_id'=>$c,'depth'=>0];}function answer(int$u,int$p,string$t,string$c,string$a):array{return['public_id'=>$c,'status'=>'pending'];}function discover(int$l):int{$this->discoveries++;return 0;}function claim(string$w,int$l,int$m):?array{if(!$this->claims)return null;$c=array_shift($this->claims);$c['worker_id']=$w;$c['lease_token']='lease';return$c;}function recordEvaluation(array$c,NextWorkEvaluationResult$r):void{$this->records++;}function finish(array$c,string$s,string$d,string$r,string$p,?string$q=null,?string$proposal=null,?string$task=null):void{$this->finished[]=['status'=>$s,'decision'=>$d,'reason'=>$r,'question'=>$q,'proposal'=>$proposal,'task'=>$task];}function retry(array$c,string$r,int$m):void{$this->retries++;}function closeCycle(int$u,int$p,string$c,string$s):void{$this->closed[]=$s;}function event(array$c,string$k,string$s):void{$this->events[]=$k;}}
final class CSource implements NextWorkSnapshotSourceInterface{function __construct(private string$status='completed'){}function load(int$u,int$p,string$t):array{return['project'=>['user_id_'=>$u,'public_id'=>'project','name'=>'P','description'=>'Goal verificable','status'=>'active'],'project_context'=>[],'task'=>['user_id_'=>$u,'project_id_'=>$p,'public_id'=>$t,'title'=>'T','objective'=>'Do','status'=>$this->status,'result_summary'=>'Done','error_summary'=>null],'steps'=>[],'executions'=>[],'events'=>[],'artifacts'=>[],'recent_tasks'=>[]];}}
final class CInference implements SingleTurnInferenceInterface{public int$calls=0;function __construct(private string$decision,private array$usage=['prompt_tokens'=>7,'completion_tokens'=>3]){}function infer(SingleTurnInferenceRequest$r):SingleTurnInferenceResult{$this->calls++;$data=['decision'=>$this->decision,'public_reason'=>'Razón pública.','evidence'=>[]];if($this->decision==='ask_user')$data['question']='¿Continuar?';if($this->decision==='propose_task')$data['proposed_objective']='Crear validación siguiente.';return new SingleTurnInferenceResult(json_encode($data),'m','end_turn',$this->usage);}}
final class CProposalStore implements NextWorkProposalStoreInterface{public array$rows=[];function resolveScope(int$u,int$p,string$t,string$c):array{return['user_id'=>$u,'project_id'=>$p,'source_task_id'=>7,'source_task_public_id'=>$t,'source_status'=>'completed','session_id_'=>4,'cycle_id'=>8,'cycle_public_id'=>$c,'descendant_depth'=>1];}function createOrGet(array$s,string$id,string$k,string$h,NextWorkDecision$d,string$status,string$reason,bool$accounted=false):array{$r=['public_id'=>$id,'user_id_'=>1,'project_id_'=>10,'source_task_public_id'=>'11111111-1111-4111-8111-111111111111','cycle_public_id'=>'cycle','status'=>$status,'public_reason'=>$d->publicReason,'proposed_title'=>null,'proposed_objective'=>$d->proposedObjective,'evidence_json'=>'[]','authorization_reason'=>$reason,'decision_accounted'=>$accounted,'reservation_public_id'=>null,'spawned_task_public_id'=>null,'lock_version'=>0,'approved_at'=>null,'rejected_at'=>null,'spawned_at'=>null];return$this->rows[$id]=$r;}function listApproved(int$l):array{return[];}function findOwned(int$u,string$id,bool$l=false):?array{return$this->rows[$id]??null;}function transition(int$u,string$id,int$l,array$f,string$to,array$x=[]):array{$r=$this->rows[$id];$r=array_merge($r,$x,['status'=>$to,'lock_version'=>$l+1]);if(isset($x['reservation_id_']))$r['reservation_public_id']='reservation';if(isset($x['spawned_task_id_']))$r['spawned_task_public_id']='child';return$this->rows[$id]=$r;}function reservationId(int$u,int$p,string$id):int{return 1;}function taskId(int$u,int$p,string$id):int{return 2;}}
final class CTaskCreator implements TaskAutonomyTaskCreator{public int$creates=0;public array$tasks=[];function createAutonomyTask(int$u,array$d):array{$this->creates++;return['task'=>$this->tasks[$d['idempotency_key']]=['public_id'=>'child']];}function findAutonomyTask(int$u,string$k,int$p,int$parent,string$o):?array{return$this->tasks[$k]??null;}}
function claim(int$depth=0,string$status='completed'):array{return['id_'=>1,'public_id'=>'cont','user_id_'=>1,'project_id_'=>10,'source_task_id_'=>7,'source_task_public_id'=>'11111111-1111-4111-8111-111111111111','cycle_public_id'=>'cycle','terminal_status'=>$status,'depth'=>$depth,'attempt_count'=>1,'decision_json'=>null,'usage_json'=>null];}
function setup(string$decision='stop',string$mode='automatic',string$policyStatus='active',int$depthLimit=3):array{$ps=new CPolicyStore($mode,$policyStatus,$depthLimit);$pol=new AutonomyPolicyService($ps);$bs=new CBudgetStore();$bud=new AutonomyBudgetService($pol,$bs);$inf=new CInference($decision);$cfg=['chat_main'=>['is_active'=>1,'model_id'=>'m','system_instruction'=>'','user_prompt_template'=>'{{snapshot}}','temperature'=>0,'max_tokens_output'=>100,'top_p'=>.9]];$ev=new NextWorkEvaluator(new NextWorkSnapshotBuilder(new CSource()),new NextWorkAgentConfigResolver(mysqli_init(),fn()=>$cfg),$inf,new NextWorkDecisionValidator());$prs=new CProposalStore();$tc=new CTaskCreator();$proposal=new NextWorkProposalService($prs,$pol,$bud,new NextWorkAuthorizationService($pol,$bud),$tc);$store=new CContinuationStore();$svc=new PostTaskContinuationService($store,$pol,$bud,$ev,$proposal,3);return[$svc,$store,$bs,$inf,$tc];}
[$svc,$st,$b,$ai]=setup('stop');$st->claims=[claim()];c11($svc->processTick('w',60)===1,'procesa una continuation');c11($ai->calls===1,'una inferencia');c11($b->reserves===2&&$b->consumes===2,'decision y usage contabilizados');c11($st->finished[0]['status']==='completed'&&$st->finished[0]['reason']==='model_stop','stop terminal');c11($st->closed===['closed'],'stop cierra cycle');
[$svc,$st,$b,$ai]=setup('ask_user');$st->claims=[claim()];$svc->processTick('w',60);c11($st->finished[0]['status']==='waiting_user','ask_user durable');c11($st->finished[0]['question']==='¿Continuar?','pregunta bounded persistida');c11($st->closed===[],'ask_user no cierra cycle');
[$svc,$st,$b,$ai,$tasks]=setup('propose_task','automatic');$st->claims=[claim()];$svc->processTick('w',60);c11($tasks->creates===1,'automatic delega y crea child');c11($st->finished[0]['status']==='completed'&&$st->finished[0]['task']==='child','continuation enlaza child');c11($b->reserves===3,'decision usage y Task tienen reservas separadas');
[$svc,$st,$b,$ai,$tasks]=setup('propose_task','supervised');$st->claims=[claim()];$svc->processTick('w',60);c11($tasks->creates===0,'supervised no crea child inline');c11($st->finished[0]['status']==='waiting_approval','supervised espera approval');
[$svc,$st,$b,$ai]=setup('stop','disabled');$st->claims=[claim()];$svc->processTick('w',60);c11($ai->calls===0,'disabled no llama IA');c11($st->finished[0]['reason']==='autonomy_disabled','disabled reason');
[$svc,$st,$b,$ai]=setup('stop','automatic','paused');$st->claims=[claim()];$svc->processTick('w',60);c11($ai->calls===0,'paused no llama IA');
[$svc,$st,$b,$ai]=setup('stop','automatic','active',1);$st->claims=[claim(1)];$svc->processTick('w',60);c11($ai->calls===0&&$st->finished[0]['reason']==='depth_limit_reached','depth impide inferencia');c11($st->closed===['exhausted'],'depth cierra exhausted');
[$svc,$st,$b,$ai]=setup();$b->deny=true;$st->claims=[claim()];$svc->processTick('w',60);c11($ai->calls===0,'decision agotada no Bedrock');c11($st->finished[0]['reason']==='decision_limit_reached','decision limit tipado');
[$svc,$st]=setup();$st->claims=[claim(),claim(),claim(),claim()];c11($svc->processTick('w',60)===3,'batch bounded por tick');c11(count($st->claims)===1,'fairness deja trabajo para siguiente tick');c11($svc->enrollRoot(1,10,'root','cycle')['depth']===0,'root association explícita');
$worker=file_get_contents(__DIR__.'/../includes/Tasks/TaskWorker.php');$repo=file_get_contents(__DIR__.'/../includes/Tasks/PostTaskContinuationRepository.php');$schema=file_get_contents(__DIR__.'/../sql/fase11d_post_task_continuations.sql');c11(substr_count($worker,'class TaskWorker')===1&&str_contains($worker,'processTick'),'mismo TaskWorker procesa continuation');c11(str_contains($repo,'FOR UPDATE SKIP LOCKED')&&str_contains($repo,'lease_expires_at'),'claim lease recuperable');c11(str_contains($schema,'uq_post_task_continuation_logical'),'dedupe cycle/source durable');c11(str_contains($schema,'ProjectAutonomyCycleTasks'),'root/cycle durable');c11(!str_contains($worker,'while (true)'),'sin loop autónomo');c11(!str_contains(file_get_contents(__DIR__.'/../includes/Tasks/PostTaskContinuationService.php'),'ChatMessages'),'sin ChatMessages');
if(!getenv('TASK_TEST_DB_HOST'))echo"SKIP — MySQL real 11D: TASK_TEST_DB_* no configurado\n";echo"$pass PASS, $fail FAIL\n";exit($fail?1:0);
