<?php
declare(strict_types=1);
$required=['TASK_TEST_DB_HOST','TASK_TEST_DB_PORT','TASK_TEST_DB_USER','TASK_TEST_DB_PASSWORD'];$missing=[];
foreach($required as$key)if(getenv($key)===false||(string)getenv($key)==='')$missing[]=$key;
if($missing){echo'SKIP MYSQL SUPPORTED UPGRADE — missing '.implode(', ',$missing)."\n";exit(0);}
require_once __DIR__.'/support/ExternalMysqlTestSafety.php';
try{requireExternalMysqlDestructiveAuthorization();}catch(RuntimeException$e){fwrite(STDERR,$e->getMessage()."\n");exit(1);}
if(!extension_loaded('mysqli')){fwrite(STDERR,"FAIL mysqli extension unavailable\n");exit(1);}
$root=dirname(__DIR__,2);foreach(['MigrationCatalog','SchemaMigrationRepository','SqlMigrationExecutor','MigrationRunner','SchemaFingerprint']as$class)require_once $root.'/michat/includes/Migrations/'.$class.'.php';
mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);$host=(string)getenv('TASK_TEST_DB_HOST');$port=filter_var(getenv('TASK_TEST_DB_PORT'),FILTER_VALIDATE_INT);$user=(string)getenv('TASK_TEST_DB_USER');$password=(string)getenv('TASK_TEST_DB_PASSWORD');
if($port===false||$port<1||$port>65535){fwrite(STDERR,"FAIL invalid TASK_TEST_DB_PORT\n");exit(1);}
$admin=new mysqli($host,$user,$password,'',(int)$port);$admin->set_charset('utf8mb4');$databases=[];$passed=0;$failed=0;
$check=function(bool$ok,string$label)use(&$passed,&$failed){echo($ok?'PASS ':'FAIL ').$label."\n";$ok?$passed++:$failed++;};$quote=fn(string$v)=>'`'.str_replace('`','``',$v).'`';
$connect=function(string$name)use($host,$port,$user,$password):mysqli{$db=new mysqli($host,$user,$password,$name,(int)$port);$db->set_charset('utf8mb4');return$db;};
$create=function(string$suffix,string$file)use($admin,&$databases,$quote,$connect):mysqli{$name=externalMysqlTemporaryDatabaseName($suffix);$admin->query('CREATE DATABASE '.$quote($name).' CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci');$databases[]=$name;$db=$connect($name);$sql=(string)file_get_contents($file);$db->multi_query($sql);do{if($r=$db->store_result())$r->free();}while($db->more_results()&&$db->next_result());return$db;};
$runner=function(mysqli$db)use(&$root):array{$name=(string)$db->query('SELECT DATABASE() d')->fetch_assoc()['d'];$catalog=new MigrationCatalog();$repository=new SchemaMigrationRepository($db,$name);return[new MigrationRunner($catalog,$repository,new SqlMigrationExecutor($db)),$catalog,$repository];};
$throws=function(callable$fn,string$needle)use($check):void{try{$fn();$check(false,$needle);}catch(Throwable$e){$check(str_contains($e->getMessage(),$needle),$needle);}};
$current=$root.'/adbbmis1_Cloud.sql';$fixture=$root.'/michat/tests/fixtures/post_fase10d.sql';
try{
 $version=(string)$admin->query('SELECT VERSION() v')->fetch_assoc()['v'];$check(version_compare(preg_replace('/[^0-9.].*/','',$version),'8.0.16','>='),'server meets documented MySQL 8.0.16 minimum');
 $clean=$create('clean',$current);[$cleanRunner,$catalog,$cleanRepo]=$runner($clean);$cleanRunner->baseline('current-dump');$cleanHistory=$cleanRepo->fetchHistory();$check(count($cleanHistory)===12&&count(array_filter($cleanHistory,fn($r)=>$r['application_mode']==='clean_baseline'))===12,'clean baseline records 12 clean_baseline rows');
 $upgrade=$create('upgrade',$fixture);[$upgradeRunner,$catalog,$upgradeRepo]=$runner($upgrade);$upgradeRunner->adoptExisting('post-fase10d');$adopted=$upgradeRepo->fetchHistory();$pending=$upgradeRunner->status();$check(count($adopted)===4&&count(array_filter($adopted,fn($r)=>$r['application_mode']==='adopted'))===4&&count(array_filter($pending['rows'],fn($r)=>$r['state']==='PENDING'))===8,'post-Fase10D adoption is 4 adopted and 8 pending');
 $expected=array_slice(array_column($catalog->all(),'migration_id'),4);$applied=$upgradeRunner->apply();$history=$upgradeRepo->fetchHistory();$check($applied===$expected&&count($history)===12&&count(array_filter($history,fn($r)=>$r['application_mode']==='applied'))===8,'supported upgrade applies the exact ordered eight-migration tail');$check($upgradeRunner->status()['global']==='APPLIED','supported upgrade status is APPLIED');
 $historyColumns=array_column($upgrade->query("SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='SchemaMigrations' ORDER BY ORDINAL_POSITION")->fetch_all(MYSQLI_ASSOC),'COLUMN_NAME');$historyPk=array_column($upgrade->query("SELECT COLUMN_NAME FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='SchemaMigrations' AND INDEX_NAME='PRIMARY' ORDER BY SEQ_IN_INDEX")->fetch_all(MYSQLI_ASSOC),'COLUMN_NAME');$modeType=(string)$upgrade->query("SELECT COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='SchemaMigrations' AND COLUMN_NAME='application_mode'")->fetch_assoc()['COLUMN_TYPE'];$check($historyColumns===['migration_id','filename','checksum_sha256','applied_at','execution_ms','application_mode','runner_version']&&$historyPk===['migration_id']&&$modeType==="enum('applied','adopted','clean_baseline')",'SchemaMigrations physical history contract');
 $catalogById=[];foreach($catalog->all()as$m)$catalogById[$m['migration_id']]=$m;$check(array_reduce($history,fn($ok,$row)=>$ok&&isset($catalogById[$row['migration_id']])&&hash_equals($catalogById[$row['migration_id']]['checksum_sha256'],$row['checksum_sha256']),true),'history checksums equal exact catalog file bytes');
 $before=$upgrade->query('SELECT migration_id,filename,checksum_sha256,applied_at,execution_ms,application_mode,runner_version FROM SchemaMigrations ORDER BY migration_id')->fetch_all(MYSQLI_ASSOC);$schemaBefore=(new SchemaFingerprint($upgrade))->capture();$check($upgradeRunner->apply()===[],'second apply executes zero migrations');$after=$upgrade->query('SELECT migration_id,filename,checksum_sha256,applied_at,execution_ms,application_mode,runner_version FROM SchemaMigrations ORDER BY migration_id')->fetch_all(MYSQLI_ASSOC);$check($before===$after&&$schemaBefore===(new SchemaFingerprint($upgrade))->capture(),'second apply preserves history and schema byte-for-byte at fingerprint level');
 $cleanFingerprint=(new SchemaFingerprint($clean))->capture();$upgradeFingerprint=(new SchemaFingerprint($upgrade))->capture();$differences=SchemaFingerprint::differences($cleanFingerprint,$upgradeFingerprint);if($differences)foreach($differences as$difference)echo'DIFF '.$difference."\n";$check($differences===[],'clean install and supported upgrade schema parity');
 foreach([$clean,$upgrade]as$db){$column=$db->query("SELECT COLUMN_TYPE,IS_NULLABLE,COLUMN_DEFAULT FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='UserAIAgentConfigs' AND COLUMN_NAME='scope'")->fetch_assoc();$check($column===['COLUMN_TYPE'=>"enum('global','user')",'IS_NULLABLE'=>'NO','COLUMN_DEFAULT'=>null],'UserAIAgentConfigs scope final contract');$bad=(int)$db->query("SELECT COUNT(*) c FROM UserAIAgentConfigs WHERE NOT ((scope='global' AND user_id_ IS NULL) OR (scope='user' AND user_id_ IS NOT NULL))")->fetch_assoc()['c'];$check($bad===0,'UserAIAgentConfigs owner rows are coherent');}
 $definitions=$catalog->all();$check($definitions[10]['checksum_sha256']==='7df5c57f22ba34169f45ab7b7dee9ecbb94ede8f6f0aa45cc8dcb5e670f53975'&&$definitions[11]['checksum_sha256']!==$definitions[10]['checksum_sha256'],'historical and reconciliation checksums are exact and distinct');
 // History DRIFT and UNKNOWN both block apply.
 $driftDirectory=sys_get_temp_dir().'/michat-migration-drift-'.bin2hex(random_bytes(5));mkdir($driftDirectory,0700,true);foreach($definitions as$m)copy($m['path'],$driftDirectory.'/'.$m['filename']);file_put_contents($driftDirectory.'/fase11b_project_autonomy.sql',"\n-- deliberate drift fixture\n",FILE_APPEND);$driftRunner=new MigrationRunner(new MigrationCatalog($driftDirectory),$upgradeRepo,new SqlMigrationExecutor($upgrade));$check($driftRunner->status()['global']==='DRIFT','modified registered migration bytes produce DRIFT');$throws(fn()=>$driftRunner->apply(),'DRIFT DETECTED');foreach(glob($driftDirectory.'/*')?:[]as$file)unlink($file);rmdir($driftDirectory);
 $upgrade->query("INSERT INTO SchemaMigrations VALUES ('unknown','unknown.sql','".str_repeat('a',64)."',CURRENT_TIMESTAMP(6),0,'applied','test')");$check($upgradeRunner->status()['global']==='UNKNOWN','unknown history is UNKNOWN');$throws(fn()=>$upgradeRunner->apply(),'UNKNOWN HISTORY');$upgrade->query("DELETE FROM SchemaMigrations WHERE migration_id='unknown'");
 // Partial pending structures fail before execution.
 $partial11=$create('partial11',$fixture);[$partialRunner]=$runner($partial11);$partialRunner->adoptExisting('post-fase10d');$partial11->query('CREATE TABLE ProjectAutonomyPolicies(id_ BIGINT UNSIGNED PRIMARY KEY)');$throws(fn()=>$partialRunner->apply(),'PARTIAL/UNKNOWN STATE');
 $partial12=$create('partial12',$fixture);[$partial12Runner,,$partial12Repo]=$runner($partial12);$partial12Runner->adoptExisting('post-fase10d');foreach(array_slice($definitions,4,6)as$m){(new SqlMigrationExecutor($partial12))->executeFile($m['path']);$partial12Repo->insertHistory($m,0,'applied',MigrationRunner::VERSION);}$partial12->query("ALTER TABLE UserAIAgentConfigs ADD COLUMN scope ENUM('global','user') NOT NULL DEFAULT 'user'");$throws(fn()=>$partial12Runner->apply(),'PARTIAL/UNKNOWN STATE');
 // Reconciliation negative/default/no-op/broken rows.
 $reconcile=$root.'/michat/sql/fase12b_4_ai_scope_default_reconciliation.sql';$upgrade->query("DELETE FROM SchemaMigrations WHERE migration_id='fase12b_4_ai_scope_default_reconciliation'");$upgrade->query("ALTER TABLE UserAIAgentConfigs ALTER COLUMN scope SET DEFAULT 'global'");$throws(fn()=>$upgradeRunner->apply(),'unexpected scope default');$upgrade->query('ALTER TABLE UserAIAgentConfigs ALTER COLUMN scope DROP DEFAULT');$check($upgradeRunner->apply()===['fase12b_4_ai_scope_default_reconciliation'],'already reconciled schema records pending reconciliation as structural no-op');
 $upgrade->query("DELETE FROM SchemaMigrations WHERE migration_id='fase12b_4_ai_scope_default_reconciliation'");$upgrade->query("ALTER TABLE UserAIAgentConfigs ALTER COLUMN scope SET DEFAULT 'user'");$upgrade->query('SET check_constraint_checks=OFF');$upgrade->query("UPDATE UserAIAgentConfigs SET scope='user',user_id_=NULL WHERE scope='global' LIMIT 1");$upgrade->query('SET check_constraint_checks=ON');$throws(fn()=>$upgradeRunner->apply(),'incoherent scope rows');$upgrade->query('SET check_constraint_checks=OFF');$upgrade->query("UPDATE UserAIAgentConfigs SET scope='global' WHERE scope='user' AND user_id_ IS NULL");$upgrade->query('SET check_constraint_checks=ON');$upgrade->query('ALTER TABLE UserAIAgentConfigs ALTER COLUMN scope DROP DEFAULT');$upgradeRunner->apply();
 // Advisory lock blocks a second runner without history writes and recovers after release.
 $lockDb=$create('lock',$fixture);[$lockRunner,,$lockRepo]=$runner($lockDb);$lockRepo->acquireLock(10);$lockCount=$lockRepo->historyTableExists()?count($lockRepo->fetchHistory()):0;$second=$connect((string)$lockDb->query('SELECT DATABASE() d')->fetch_assoc()['d']);[$secondRunner]=$runner($second);$check($secondRunner->status()['global']==='LOCKED','contended status is LOCKED');$throws(fn()=>$secondRunner->apply(),'LOCK CONTENTION');$check(($lockRepo->historyTableExists()?count($lockRepo->fetchHistory()):0)===$lockCount,'lock contention writes no history');$lockRepo->releaseLock();$lockRunner->adoptExisting('post-fase10d');$check(count($lockRepo->fetchHistory())===4,'runner recovers after migration lock release');$second->close();
 // Current-dump profile negatives.
 $baselineMutations=['missing_table'=>'DROP TABLE TaskEvents','scope_default'=>"ALTER TABLE UserAIAgentConfigs ALTER COLUMN scope SET DEFAULT 'user'",'wrong_fk'=>'ALTER TABLE UserAIAgentConfigs DROP FOREIGN KEY fk_uac_user','wrong_unique'=>'ALTER TABLE UserAIAgentConfigs DROP INDEX uq_uac_scope_owner_agent','incomplete_fase11'=>'DROP TABLE TaskPlanRevisionSteps'];
 foreach($baselineMutations as$name=>$sql){$db=$create('base_'.$name,$current);[$r]=$runner($db);$db->query($sql);$throws(fn()=>$r->baseline('current-dump'),'PROFILE MISMATCH');$db->close();}
 // post-Fase10D profile negatives.
 $profileMutations=['fase11'=>'CREATE TABLE ProjectAutonomyPolicies(id_ BIGINT UNSIGNED PRIMARY KEY)','scope'=>"ALTER TABLE UserAIAgentConfigs ADD COLUMN scope ENUM('global','user') NOT NULL DEFAULT 'user'",'missing_required'=>'DROP TABLE TaskEvents'];
 foreach($profileMutations as$name=>$sql){$db=$create('profile_'.$name,$fixture);[$r]=$runner($db);$db->query($sql);$throws(fn()=>$r->adoptExisting('post-fase10d'),'PROFILE MISMATCH');$db->close();}
 $historyDb=$create('profile_history',$fixture);[$historyRunner]=$runner($historyDb);$historyRunner->adoptExisting('post-fase10d');$throws(fn()=>$historyRunner->adoptExisting('post-fase10d'),'history is not empty');$historyDb->close();
 $clean->close();$upgrade->close();$partial11->close();$partial12->close();$lockDb->close();
}catch(Throwable$e){$check(false,'supported-upgrade harness: '.$e->getMessage());}
finally{foreach(array_reverse($databases)as$name)try{assertExternalMysqlDatabaseOwned($name,$databases);$admin->query('DROP DATABASE IF EXISTS '.$quote($name));}catch(Throwable$e){$check(false,'cleanup '.$name);}$admin->close();}
echo'MYSQL SUPPORTED UPGRADE: '.($failed?'FAIL':'PASS')."\nResult: {$passed} passed, {$failed} failed\n";exit($failed?1:0);
