<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);require_once $root.'/michat/includes/Migrations/MigrationCatalog.php';require_once $root.'/michat/includes/Migrations/SchemaFingerprint.php';
$passed=0;$failed=0;$check=function(bool$ok,string$label)use(&$passed,&$failed){echo($ok?'PASS ':'FAIL ').$label."\n";$ok?$passed++:$failed++;};
$fixturePath=$root.'/michat/tests/fixtures/post_fase10d.sql';$fixture=(string)file_get_contents($fixturePath);$comparator=(string)file_get_contents($root.'/michat/includes/Migrations/SchemaFingerprint.php');$harness=(string)file_get_contents($root.'/michat/tests/supported_upgrade_mysql_test.php');$catalog=(new MigrationCatalog())->all();
$check(hash('sha256',$fixture)==='2ed04eca14dad78258ef961dc0e8def27411dac9acaa9bebf1f0bd5546ddd867','post-Fase10D fixture is immutable and reproducible');
$check(str_contains($fixture,'e1a96e703af8748b59c4603137b4374c3990e54c')&&!preg_match('/^(?:CREATE DATABASE|USE `)/mi',$fixture),'fixture documents authoritative Fase 10 source and inherits the selected test DB');
foreach(['Tasks','TaskSteps','TaskExecutions','TaskDependencies','TaskEvents','TaskArtifacts','TaskRecurrenceRules','TaskRecurrenceOccurrences','UserAIAgentConfigs']as$table)$check((bool)preg_match('/CREATE TABLE IF NOT EXISTS `'.preg_quote($table,'/').'`/',$fixture),'fixture contains '.$table);
foreach(['ProjectAutonomyPolicies','ProjectAutonomyCycles','NextWorkProposals','ProjectAutonomyCycleTasks','PostTaskContinuations','TaskReplanRequests','TaskPlanRevisions','TaskPlanRevisionSteps']as$table)$check(!str_contains($fixture,'CREATE TABLE IF NOT EXISTS `'.$table.'`'),'fixture excludes Fase 11 table '.$table);
$check(!preg_match('/`scope`\s+enum\(\'global\',\'user\'\)/i',$fixture),'fixture retains legacy UserAIAgentConfigs without GLOBAL/USER scope');
$check(count($catalog)===14&&array_column($catalog,'migration_id')===['fase8_1_task_orchestrator','fase8_6d_3d_toolcalls_code_edit','fase8_7b_task_artifacts','fase10d_task_recurrence','fase11b_project_autonomy','fase11c_next_work_proposals','fase11d_post_task_continuations','fase11e0_replan_checkpoint','fase11e1_versioned_replanning','fase11f2_hitl_controls','fase12b_2c_global_ai_configuration_scope','fase12b_4_ai_scope_default_reconciliation','fase12b_5_mysql_generated_column_compatibility','fase12b_6_system_role_authorization'],'catalog is the exact supported 14-migration chain');
foreach(['TABLE_COLLATION','ORDINAL_POSITION','COLUMN_TYPE','DATA_TYPE','IS_NULLABLE','COLUMN_DEFAULT','EXTRA','GENERATION_EXPRESSION','CHARACTER_SET_NAME','COLLATION_NAME','NON_UNIQUE','SEQ_IN_INDEX','SUB_PART','EXPRESSION','UPDATE_RULE','DELETE_RULE','CHECK_CLAUSE']as$field)$check(str_contains($comparator,$field),'fingerprint captures '.$field);
$check(str_contains($comparator,'clean=%s upgrade=%s')&&str_contains($comparator,"preg_replace('/\\s+/u'")&&!str_contains($comparator,'strtolower')&&!str_contains($comparator,'AUTO_INCREMENT'),'comparator emits readable diffs and normalizes only expression whitespace');
foreach(['clean install and supported upgrade schema parity','second apply executes zero migrations','DRIFT DETECTED','UNKNOWN HISTORY','PARTIAL/UNKNOWN STATE','LOCK CONTENTION','missing_table','scope_default','wrong_fk','wrong_unique','incomplete_fase11','profile_history']as$contract)$check(str_contains($harness,$contract),'MySQL harness covers '.$contract);
$check(str_contains($harness,"'scope_default'=>")&&str_contains($harness,"ALTER TABLE UserAIAgentConfigs ALTER COLUMN scope SET DEFAULT 'user'"),'MySQL harness covers unexpected scope default');
$check(str_contains($harness,"WHERE NOT ((scope='global' AND user_id_ IS NULL) OR (scope='user' AND user_id_ IS NOT NULL))")&&str_contains($harness,'UserAIAgentConfigs owner rows are coherent'),'MySQL harness covers incoherent scope rows');
$check(hash('sha256',(string)file_get_contents($root.'/michat/sql/fase12b_2c_global_ai_configuration_scope.sql'))==='7df5c57f22ba34169f45ab7b7dee9ecbb94ede8f6f0aa45cc8dcb5e670f53975','published 12B.2C checksum remains immutable');
$check($catalog[11]['checksum_sha256']!==$catalog[10]['checksum_sha256']&&$catalog[12]['checksum_sha256']!==$catalog[11]['checksum_sha256']&&$catalog[13]['checksum_sha256']!==$catalog[12]['checksum_sha256'],'12B.4/12B.5/12B.6 own distinct catalog checksums');
echo"Result: {$passed} passed, {$failed} failed\n";exit($failed?1:0);
