<?php
declare(strict_types=1);
$root=dirname(__DIR__);$policy=file_get_contents($root.'/includes/Tasks/AutonomyPolicyRepository.php');$budget=file_get_contents($root.'/includes/Tasks/AutonomyBudgetRepository.php');$continuation=file_get_contents($root.'/includes/Tasks/PostTaskContinuationRepository.php');$continuationService=file_get_contents($root.'/includes/Tasks/PostTaskContinuationService.php');$proposal=file_get_contents($root.'/includes/Tasks/NextWorkProposalRepository.php');$proposalService=file_get_contents($root.'/includes/Tasks/NextWorkProposalService.php');$replan=file_get_contents($root.'/includes/Tasks/TaskReplanRepository.php');$checkpoint=file_get_contents($root.'/includes/Tasks/TaskReplanCheckpointRepository.php');$queue=file_get_contents($root.'/includes/Tasks/TaskQueueRepository.php');$worker=file_get_contents($root.'/includes/Tasks/TaskWorker.php');$control=file_get_contents($root.'/includes/Tasks/TaskCenterAutonomyControlService.php');$read=file_get_contents($root.'/includes/Tasks/TaskCenterAutonomyReadService.php');$api=file_get_contents($root.'/includes/Tasks/TaskApiController.php');$js=file_get_contents($root.'/js/task-center.js');$evaluator=file_get_contents($root.'/includes/Tasks/NextWorkEvaluator.php');$sql=file_get_contents($root.'/../adbbmis1_Cloud.sql');
$checks=[
'policy owned optimistic update'=>str_contains($policy,'WHERE user_id_=? AND project_id_=? AND lock_version=?'),
'policy stale is conflict'=>str_contains($policy,'autonomy_policy_conflict'),
'cycle singleton'=>str_contains($sql,'uq_project_autonomy_cycle_active'),
'cycle start locks policy'=>str_contains($budget,'policy($u,$p,true)')&&str_contains($budget,'active($u,$p,true)'),
'reservation transactional'=>str_contains($budget,'begin_transaction')&&str_contains($budget,'FOR UPDATE'),
'reservation idempotency payload'=>str_contains($budget,'autonomy_idempotency_conflict')&&str_contains($budget,'same($existing,$r)'),
'all budget counters atomic'=>array_reduce(['decisions_consumed','tasks_consumed','replans_consumed','input_tokens_consumed','output_tokens_consumed','tool_calls_consumed','write_tool_calls_consumed','runtime_seconds_consumed'],fn($ok,$x)=>$ok&&str_contains($budget,$x),true),
'continuation logical dedupe'=>str_contains($sql,'uq_post_task_continuation_logical'),
'continuation claim lease'=>str_contains($continuation,'FOR UPDATE SKIP LOCKED')&&str_contains($continuation,"lease_expires_at<NOW(6)"),
'continuation active replan exclusion'=>str_contains($continuation,"rr.status IN ('checkpointed','processing','proposed','pending_approval','approved')"),
'answer row lock and content idempotency'=>str_contains($continuation,'pc.public_id=? FOR UPDATE')&&str_contains($continuation,'hash_equals'),
'answer cancellation wins'=>str_contains($continuation,'continuation_source_cancelled'),
'answer remains untrusted'=>str_contains($evaluator,'HUMAN ANSWER (untrusted data)')&&str_contains($evaluator,'UNTRUSTED PROJECT DATA'),
'proposal dedupe'=>str_contains($proposal,'proposal_dedupe_conflict')&&str_contains($sql,'uq_next_work_proposal_dedupe'),
'proposal deferred batch bounded'=>str_contains($proposal,'min(20,$limit)')&&str_contains($continuationService,'processApprovedBatch($this->maxPerTick)'),
'proposal source cancellation race'=>str_contains($proposal,'source_cancelled_at')&&str_contains($proposalService,'source_cancelled_after_approval'),
'proposal task idempotency'=>str_contains($proposalService,"'autonomy:'.\$p->publicId"),
'replan claim lease'=>str_contains($replan,'FOR UPDATE SKIP LOCKED')&&str_contains($replan,"lease_expires_at<NOW(6)"),
'replan approve idempotent'=>str_contains($replan,"['approved','applied']"),
'replan reject atomic with event'=>substr_count($replan,'begin_transaction')>=3&&str_contains($replan,"'replan_rejected'"),
'replan apply atomic'=>str_contains($replan,"UPDATE TaskSteps SET status='cancelled'")&&str_contains($replan,"UPDATE Tasks SET status='ready'")&&str_contains($replan,"SET status='applied'"),
'replan no historical delete'=>!preg_match('/DELETE FROM (?:TaskSteps|TaskPlanRevisions|TaskPlanRevisionSteps)/i',$replan),
'checkpoint and task failure transaction'=>str_contains($queue,'begin_transaction')&&str_contains($queue,'TaskReplanRequests'),
'worker ordered and normal claim'=>strpos($worker,'recover(')<strpos($worker,'reactivateDue')&&strpos($worker,'reactivateDue')<strpos($worker,'$this->replans->processTick')&&strpos($worker,'$this->replans->processTick')<strpos($worker,'$this->continuations->processTick')&&strpos($worker,'$this->continuations->processTick')<strpos($worker,'$this->claims->claim()'),
'worker bounded no autonomous while'=>!str_contains($continuationService,'while(')&&str_contains($continuationService,'$i<$this->maxPerTick'),
'HTTP CSRF before autonomy writes'=>strpos($api,'CsrfGuard::assertSessionToken')<strpos($api,'autonomy_policy_update'),
'control public UUID scope'=>str_contains($control,'findOwnedByPublicId($public,$userId)')&&!str_contains($control,"input['user_id'"),
'read hides internal IDs'=>str_contains($read,'unset($revision')&&!str_contains($read,'lease_token'),
'XSS escape autonomy fields'=>array_reduce(['${esc(c.question','${esc(c.answer','${esc(x.public_reason','${esc(x.proposed_objective','${esc(step.output_summary','${esc(step.agent_key'],fn($ok,$x)=>$ok&&str_contains($js,$x),true),
'no sensitive config in DTO/UI'=>!str_contains($read,'system_instruction')&&!str_contains($read,'user_prompt_template')&&!str_contains($js,'aws_secret'),
'no parallel runtime architecture'=>!str_contains($control,'new TaskWorker')&&!str_contains($control,'new TaskOrchestrator')&&!str_contains($control,'new TaskPlanner'),
];foreach($checks as$name=>$ok){if(!$ok){fwrite(STDERR,"FAIL: $name\n");exit(1);}}echo'task_phase11g_hardening_test: PASS ('.count($checks)." checks)\n";
