<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit(1);
$passed=0;$failed=0;$ok=function(bool$v,string$n)use(&$passed,&$failed):void{echo($v?'PASS ':'FAIL ').$n."\n";$v?$passed++:$failed++;};
$source=file_get_contents(__DIR__.'/../includes/Tasks/TaskToolApprovalDecisionService.php');$controller=file_get_contents(__DIR__.'/../includes/Tasks/TaskApiController.php');$app=file_get_contents(__DIR__.'/../includes/Tasks/TaskApplicationService.php');
$ok(str_contains($source,'begin_transaction()')&&str_contains($source,'FOR UPDATE')&&str_contains($source,'commit()')&&str_contains($source,'rollback()'),'decisión tiene locks y transacción completa');
$ok(str_contains($source,"'consumed']=false")&&str_contains($source,"waiting_user'")&&str_contains($source,"status='waiting'"),'approve deja autorización no consumida y valida estados');
$ok(str_contains($source,"'tool_approval_'.\$decision")&&str_contains($source,"'user'")&&str_contains($source,'actor_user_id_'),'evento humano explícito');
$ok(!str_contains($source,'ToolRegistry::execute')&&!str_contains($source,'ToolCalls')&&!str_contains($source,'TaskArtifacts'),'decisión no ejecuta Tool ni crea ToolCall/Artifact');
$ok(str_contains($controller,"action==='approve_tool'")&&str_contains($controller,"action==='reject_tool'")&&strpos($controller,'CsrfGuard::assertSessionToken')<strpos($controller,"action==='approve_tool'"),'API publica actions después de CSRF');
$ok(!str_contains($app,"['execution_id']")&&!str_contains($app,"['task_id']")&&str_contains($app,"['fingerprint']"),'Application no acepta IDs internos del cliente');
$required=['TASK_TEST_DB_HOST','TASK_TEST_DB_PORT','TASK_TEST_DB_USER','TASK_TEST_DB_PASSWORD','TASK_TEST_DB_NAME'];foreach($required as$k){if(getenv($k)===false||getenv($k)===''){echo"SKIP — integración MySQL decisión/rollback no ejecutada: TASK_TEST_DB_* no configurado.\nResultado: {$passed} PASS, {$failed} FAIL.\n";exit($failed?1:0);}}
$database=(string)getenv('TASK_TEST_DB_NAME');if(!preg_match('/(^|[_-])(test|testing)([_-]|$)/i',$database)){fwrite(STDERR,"FAIL DB no aislada\n");exit(1);}require_once __DIR__.'/../includes/Tasks/bootstrap.php';mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);$db=new mysqli((string)getenv('TASK_TEST_DB_HOST'),(string)getenv('TASK_TEST_DB_USER'),(string)getenv('TASK_TEST_DB_PASSWORD'),$database,(int)getenv('TASK_TEST_DB_PORT'));$db->set_charset('utf8mb4');
$user=0;$session=0;$tasks=[];$trigger='';$suffix=bin2hex(random_bytes(5));
try{
 $email="decision-{$suffix}@example.test";$curp=strtoupper(substr(hash('sha256',$suffix),0,18));$s=$db->prepare("INSERT INTO Users(firstname,lastname,curp,gender,email,password,role,chat,userstatus) VALUES('Decision','Test',?,'Otro',?,'test','Otros',1,'Activo')");$s->bind_param('ss',$curp,$email);$s->execute();$user=(int)$db->insert_id;$s->close();$title="decision-{$suffix}";$model='test';$s=$db->prepare("INSERT INTO ChatSessions(user_id_,project_id_,title,model_id,provider,status) VALUES(?,NULL,?,?,'test','open')");$s->bind_param('iss',$user,$title,$model);$s->execute();$session=(int)$db->insert_id;$s->close();
 $registry=new ToolRegistry();$registry->register('code_edit',static fn(array$i)=>new ToolExecutionResult('never'),'non_idempotent');$proposalFactory=new TaskToolApprovalProposalFactory(new TaskToolRiskPolicy($registry),new TaskToolApprovalFingerprint());$arguments=['action'=>'write','target_filename'=>'App.php','instruction'=>'private instruction'];
 $fixture=function(string$name)use($db,$user,$session,$title,$proposalFactory,$arguments,&$tasks):array{$public=TaskPublicId::generate();$objective='decision';$s=$db->prepare("INSERT INTO Tasks(public_id,user_id_,created_by_user_id_,project_id_,session_id_,origin_type,title,objective,status,priority,max_attempts) VALUES(?,?,?,NULL,?,'system',?,?,'waiting_user','normal',1)");$s->bind_param('siiiss',$public,$user,$user,$session,$title,$objective);$s->execute();$task=(int)$db->insert_id;$s->close();$key='write_'.$name;$s=$db->prepare("INSERT INTO TaskSteps(task_id_,position,step_key,title,step_type,status,agent_key,lock_version) VALUES(?,1,?,'Write','tool','waiting_user','test',2)");$s->bind_param('is',$task,$key);$s->execute();$step=(int)$db->insert_id;$s->close();$db->query("UPDATE Tasks SET current_step_id_={$step} WHERE id_={$task}");$trace=TaskPublicId::generate();$s=$db->prepare("INSERT INTO TaskExecutions(task_id_,step_id_,trace_id,attempt_number,status,worker_id,lease_token) VALUES(?,?,?,1,'waiting','old-worker',?)");$token=TaskPublicId::generate();$s->bind_param('iiss',$task,$step,$trace,$token);$s->execute();$execution=(int)$db->insert_id;$s->close();$scope=['task_id'=>$task,'step_id'=>$step,'execution_id'=>$execution,'user_id'=>$user,'project_id'=>null,'session_id'=>$session];$proposal=$proposalFactory->create('code_edit',$arguments,$scope);$checkpoint=json_encode(['preserved'=>'yes','tool_approval'=>['format_version'=>1,'identity'=>(new TaskToolApprovalIdentity($execution))->toArray(),'proposal'=>$proposal->toArray()]],JSON_THROW_ON_ERROR);$s=$db->prepare('UPDATE TaskSteps SET checkpoint_json=? WHERE id_=?');$s->bind_param('si',$checkpoint,$step);$s->execute();$s->close();$tasks[]=$task;return compact('public','task','step','key','execution','proposal');};
 $service=new TaskToolApprovalDecisionService($db);$approve=$fixture('approve');$result=$service->decide($user,$approve['public'],$approve['key'],2,$approve['proposal']->fingerprint,true);$ok($result['decision']==='approved'&&$result['task']['status']==='ready'&&$result['step']['status']==='ready','approve devuelve DTO seguro');$t=$db->query("SELECT status,current_step_id_ FROM Tasks WHERE id_={$approve['task']}")->fetch_assoc();$st=$db->query("SELECT status,checkpoint_json FROM TaskSteps WHERE id_={$approve['step']}")->fetch_assoc();$ex=$db->query("SELECT status,finished_at,worker_id,lease_token FROM TaskExecutions WHERE id_={$approve['execution']}")->fetch_assoc();$cp=json_decode($st['checkpoint_json'],true);$ok($t['status']==='ready'&&(int)$t['current_step_id_']===$approve['step']&&$st['status']==='ready'&&$ex['status']==='completed'&&$ex['finished_at']!==null&&$ex['worker_id']===null&&$ex['lease_token']===null,'approve completa Execution y rearma mismo Step/Task');$ok(($cp['tool_approval']['decision']['status']??'')==='approved'&&($cp['tool_approval']['decision']['consumed']??null)===false&&$cp['tool_approval']['decision']['fingerprint']===$approve['proposal']->fingerprint,'approve persiste approved no consumido');$event=$db->query("SELECT * FROM TaskEvents WHERE task_id_={$approve['task']} AND event_key='tool_approval_approved'")->fetch_assoc();$ok($event&&$event['actor_type']==='user'&&(int)$event['actor_user_id_']===$user&&(int)$event['execution_id_']===$approve['execution'],'approve registra actor y referencias');try{$service->decide($user,$approve['public'],$approve['key'],2,$approve['proposal']->fingerprint,true);$ok(false,'doble approve falla');}catch(TaskTransitionException$e){$ok(true,'doble approve produce conflicto');}
 $reject=$fixture('reject');$service->decide($user,$reject['public'],$reject['key'],2,$reject['proposal']->fingerprint,false);$t=$db->query("SELECT status FROM Tasks WHERE id_={$reject['task']}")->fetch_assoc();$st=$db->query("SELECT status FROM TaskSteps WHERE id_={$reject['step']}")->fetch_assoc();$ex=$db->query("SELECT status FROM TaskExecutions WHERE id_={$reject['execution']}")->fetch_assoc();$ok($t['status']==='cancelled'&&$st['status']==='cancelled'&&$ex['status']==='cancelled','reject cancela Execution/Step/Task');$ok((int)$db->query("SELECT COUNT(*) c FROM TaskEvents WHERE task_id_={$reject['task']} AND event_key='tool_approval_rejected'")->fetch_assoc()['c']===1,'reject registra evento');
 $security=$fixture('security');try{$service->decide($user+999,$security['public'],$security['key'],2,$security['proposal']->fingerprint,true);$ok(false,'Task ajena falla');}catch(TaskNotFoundException$e){$ok(true,'ownership fail closed');}try{$service->decide($user,$security['public'],$security['key'],2,str_repeat('b',64),true);$ok(false,'fingerprint incorrecto falla');}catch(TaskConcurrencyException$e){$ok(true,'fingerprint incorrecto conflicto');}try{$service->decide($user,$security['public'],$security['key'],1,$security['proposal']->fingerprint,true);$ok(false,'lock viejo falla');}catch(TaskConcurrencyException$e){$ok(true,'lock viejo conflicto');}
 $rollback=$fixture('rollback');$trigger='fail_decision_'.$suffix;$db->query("CREATE TRIGGER `{$trigger}` BEFORE INSERT ON TaskEvents FOR EACH ROW BEGIN IF NEW.task_id_={$rollback['task']} AND NEW.event_key='tool_approval_approved' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced decision event failure'; END IF; END");try{$service->decide($user,$rollback['public'],$rollback['key'],2,$rollback['proposal']->fingerprint,true);$ok(false,'fallo final propaga');}catch(mysqli_sql_exception$e){$ok(str_contains($e->getMessage(),'forced decision event failure'),'fallo evento simulado');}$db->query("DROP TRIGGER `{$trigger}`");$trigger='';$t=$db->query("SELECT status FROM Tasks WHERE id_={$rollback['task']}")->fetch_assoc();$st=$db->query("SELECT status,checkpoint_json FROM TaskSteps WHERE id_={$rollback['step']}")->fetch_assoc();$ex=$db->query("SELECT status FROM TaskExecutions WHERE id_={$rollback['execution']}")->fetch_assoc();$ok($t['status']==='waiting_user'&&$st['status']==='waiting_user'&&$ex['status']==='waiting'&&!str_contains($st['checkpoint_json'],'decision'),'rollback conserva solicitud pending completa');
}catch(Throwable$e){$failed++;fwrite(STDERR,'FAIL integración decision: '.$e->getMessage()."\n");}finally{try{if($trigger!=='')$db->query("DROP TRIGGER IF EXISTS `{$trigger}`");foreach($tasks as$id){$db->query("UPDATE Tasks SET current_step_id_=NULL WHERE id_={$id}");$db->query("DELETE FROM Tasks WHERE id_={$id}");}if($session)$db->query("DELETE FROM ChatSessions WHERE id_={$session}");if($user)$db->query("DELETE FROM Users WHERE id={$user}");}catch(Throwable$e){$failed++;}$db->close();}
echo"Resultado: {$passed} PASS, {$failed} FAIL.\n";exit($failed?1:0);
