<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/Tasks/bootstrap.php';
$passed=0;$failed=0;$ok=function(bool$v,string$n)use(&$passed,&$failed):void{echo($v?'PASS ':'FAIL ').$n."\n";$v?$passed++:$failed++;};
$calculator=new TaskRecurrenceCalculator();$planner=new TaskRecurrenceMisfirePlanner($calculator);$now=new DateTimeImmutable('2026-01-05 12:00:00',new DateTimeZone('UTC'));$base=['frequency'=>'daily','weekday'=>null,'local_time'=>'10:00:00','timezone'=>'UTC','next_occurrence_at'=>'2026-01-01 10:00:00.000000'];
$skip=$planner->plan($base+['misfire_policy'=>'skip'],$now,3);$ok($skip['slots']===[]&&$skip['next']==='2026-01-06 10:00:00.000000'&&$skip['skipped']===1,'skip avanza directo al primer slot futuro sin filas masivas');
$once=$planner->plan($base+['misfire_policy'=>'run_once'],$now,3);$ok($once['slots']===['2026-01-01 10:00:00.000000']&&$once['next']==='2026-01-06 10:00:00.000000','run_once usa determinísticamente el slot vencido más antiguo');
$catch=$planner->plan($base+['misfire_policy'=>'catch_up'],$now,3);$ok($catch['slots']===['2026-01-01 10:00:00.000000','2026-01-02 10:00:00.000000','2026-01-03 10:00:00.000000'],'catch_up conserva orden lógico');$ok($catch['next']==='2026-01-04 10:00:00.000000','catch_up limitado conserva siguiente slot pendiente');
$future=$planner->plan(array_replace($base,['next_occurrence_at'=>'2026-01-06 10:00:00.000000','misfire_policy'=>'catch_up']),$now,3);$ok($future['slots']===[]&&$future['next']==='2026-01-06 10:00:00.000000','regla futura no genera slots');
$weekly=$planner->plan(['frequency'=>'weekly','weekday'=>1,'local_time'=>'10:00:00','timezone'=>'UTC','next_occurrence_at'=>'2025-12-22 10:00:00.000000','misfire_policy'=>'catch_up'],$now,2);$ok($weekly['slots']===['2025-12-22 10:00:00.000000','2025-12-29 10:00:00.000000']&&$weekly['next']==='2026-01-05 10:00:00.000000','weekly downtime y límite son civiles');
try{$planner->plan($base+['misfire_policy'=>'catch_up'],$now,0);$ok(false,'catch-up limit inválido');}catch(InvalidArgumentException){$ok(true,'catch-up limit inválido rechazado');}
$ruleRepo=file_get_contents(__DIR__.'/../includes/Tasks/TaskRecurrenceRuleRepository.php');$occRepo=file_get_contents(__DIR__.'/../includes/Tasks/TaskRecurrenceOccurrenceRepository.php');$evaluator=file_get_contents(__DIR__.'/../includes/Tasks/TaskRecurrenceEvaluator.php');$worker=file_get_contents(__DIR__.'/../includes/Tasks/TaskWorker.php');$entry=file_get_contents(__DIR__.'/../bin/task_worker.php');$config=file_get_contents(__DIR__.'/../includes/Tasks/TaskWorkerConfig.php');$app=file_get_contents(__DIR__.'/../includes/Tasks/TaskApplicationService.php');
$ok(str_contains($ruleRepo,"status='enabled' AND next_occurrence_at<=UTC_TIMESTAMP(6)"),'query selecciona solo enabled vencidas en UTC');
$ok(str_contains($ruleRepo,'ORDER BY next_occurrence_at,id_ LIMIT 1 FOR UPDATE SKIP LOCKED'),'query due acotada y concurrente');
$ok(str_contains($ruleRepo,'id_ NOT IN')&&str_contains($evaluator,'$processed'),'una regla solo consume su catch-up limit por ciclo');
$ok(str_contains($occRepo,'claimRetryable')&&str_contains($occRepo,"status IN ('reserved','failed')")&&str_contains($occRepo,'updated_at<=?'),'failed y reserved huérfanas tienen recovery por antigüedad');
$ok(str_contains($occRepo,'updated_at=UTC_TIMESTAMP(6)')&&str_contains($occRepo,'lock_version=lock_version+1'),'recovery reclama temporalmente sin lease/schema nuevo');
$ok(str_contains($evaluator,"claimRetryable($"."now)")&&str_contains($evaluator,"$"."now->modify('-'.$"."this->orphanSeconds"),'recovery usa el reloj inyectado');
$ok(str_contains($evaluator,'$this->occurrences->reserve')&&strpos($evaluator,'$this->occurrences->reserve')<strpos($evaluator,'createManualTask'),'occurrence se reserva antes de crear Task');
$ok(str_contains($evaluator,'TaskManualTaskCreator')&&str_contains($evaluator,'createManualTask'),'materialización usa frontera canónica 10C');
$ok(str_contains($app,'implements TaskManualTaskCreator'),'TaskApplicationService satisface frontera explícita');
$ok(str_contains($evaluator,"'title'=>(string)$"."rule['task_title']")&&str_contains($evaluator,"'session_id'=>(int)$"."rule['session_id_']"),'input deriva del blueprint owned');
$ok(str_contains($evaluator,"'idempotency_key'=>TaskRecurrenceOccurrenceRepository::taskIdempotencyKey"),'Task usa idempotency determinista 10D');
$ok(str_contains($evaluator,"'scheduled_at'=>$"."this->iso($"."slot)")&&!str_contains($evaluator,"scheduled_at'=>$"."rule['next_occurrence_at']"),'scheduled_at usa slot lógico, no next de regla');
$ok(str_contains($evaluator,'findOwnedByPublicId')&&str_contains($evaluator,'linkTask'),'Task real se resuelve owned antes del enlace');
$ok(str_contains($occRepo,"status='materialized'")&&str_contains($occRepo,'task_id_=?'),'link deja occurrence materialized');
$ok(str_contains($evaluator,"'task_validation_failed'")&&str_contains($evaluator,"'task_materialization_failed'"),'fallo durable usa códigos públicos controlados');
$ok(str_contains($evaluator,'recordFailure')&&str_contains($occRepo,"status IN ('reserved','failed')"),'retry failed reutiliza la misma occurrence');
$ok(str_contains($ruleRepo,'lock_version=?')&&str_contains($ruleRepo,"status='enabled'"),'avance protege pause/cancel race con status y versión');
$ok(str_contains($worker,'recovery->recover')&&strpos($worker,'recovery->recover')<strpos($worker,'reactivateDue')&&strpos($worker,'reactivateDue')<strpos($worker,'recurrence->evaluate')&&strpos($worker,'recurrence->evaluate')<strpos($worker,'claims->claim'),'orden Worker recovery waits recurrence claim');
$ok(str_contains($worker,'catch(Throwable$e)')&&strpos($worker,'claims->claim')>strpos($worker,'Task recurrence maintenance failed'),'fallo recurrente no impide claim normal');
$ok(str_contains($worker,'recurrenceMetrics')&&str_contains($evaluator,"'rules_checked'")&&str_contains($evaluator,"'occurrences_reserved'")&&str_contains($evaluator,"'tasks_materialized'")&&str_contains($evaluator,"'occurrences_failed'")&&str_contains($evaluator,"'occurrences_skipped'"),'telemetría bounded por ciclo disponible');
foreach(['TASK_WORKER_RECURRENCE_BATCH','TASK_WORKER_RECURRENCE_CATCH_UP_LIMIT','TASK_WORKER_RECURRENCE_RETRY_BATCH','TASK_WORKER_RECURRENCE_ORPHAN_SECONDS']as$key)$ok(str_contains($config,$key),"config server-side {$key}");
$ok(str_contains($entry,'new TaskRecurrenceEvaluator')&&substr_count($entry,'new TaskWorker(')===1,'entrypoint integra evaluador en único Worker');
$ok(!str_contains($entry,'recurrence_worker')&&!str_contains($evaluator,'TaskQueueRepository')&&!str_contains($evaluator,'TaskExecution'),'sin segundo Worker Queue ni ejecución directa');
$ok(str_contains($evaluator,"'mode'=>(string)$"."rule['task_mode']"),'automatic/supervised se delegan sin auto-aprobación');
$ok(!str_contains($evaluator,'approve')&&!str_contains($evaluator,'TaskEventRepository'),'no auto-aprueba ni duplica TaskEvents');
$ok(str_contains($evaluator,'array_sum($this->recurrenceMetrics)')===false&&str_contains($worker,'array_sum($this->recurrenceMetrics)>0'),'materialización cuenta trabajo pero claim siempre se intenta');
echo"Resultado: {$passed} passed, {$failed} failed\n";
$required=['TASK_TEST_DB_HOST','TASK_TEST_DB_PORT','TASK_TEST_DB_USER','TASK_TEST_DB_PASSWORD','TASK_TEST_DB_NAME'];$configured=true;foreach($required as$key)if(getenv($key)===false||getenv($key)==='')$configured=false;if(!$configured)echo"SKIP — MySQL real 10E: TASK_TEST_DB_* no configurado; contratos temporales/Worker estáticos validados.\n";else echo"SKIP — E2E MySQL 10E requiere fixtures Worker/Planner aislados; no se usa una DB no preparada.\n";exit($failed?1:0);
