'use strict';
const assert=require('node:assert/strict');
const context=require('../js/task-operational-context.js');
const now=new Date('2030-01-10T12:00:00Z');
assert.equal(context.dateContext({status:'ready',scheduled_at:null,due_at:null},now).overdue,false);
assert.equal(context.dateContext({status:'ready',scheduled_at:'2030-01-11 00:00:00',due_at:null},now).scheduledFuture,true);
assert.equal(context.dateContext({status:'running',due_at:'2030-01-09 00:00:00'},now).overdue,true);
assert.equal(context.dateContext({status:'completed',due_at:'2030-01-09 00:00:00'},now).overdue,false);
assert.equal(context.situation({status:'waiting_user'}).key,'human');
assert.equal(context.situation({status:'waiting_dependency',current_step:{step_type:'wait'}}).key,'wait');
assert.equal(context.situation({status:'waiting_dependency'}).key,'blocked');
assert.equal(context.situation({status:'waiting_dependency'},[{condition:'completed',depends_on_status:'running'}]).key,'blocked');
assert.equal(context.situation({status:'waiting_dependency'},[{condition:'terminal_any',depends_on_status:'failed'}]).key,'waiting');
assert.equal(context.situation({status:'ready'}).key,'ready');
assert.equal(context.boardColumn('pending'),'pending');
assert.equal(context.boardColumn('ready'),'pending');
assert.equal(context.boardColumn('running'),'running');
assert.equal(context.boardColumn('waiting_user'),'human');
assert.equal(context.boardColumn('waiting_dependency'),'waiting');
assert.equal(context.boardColumn('completed'),'completed');
assert.equal(context.boardColumn('failed'),'stopped');
assert.equal(context.boardColumn('cancelled'),'stopped');
assert.equal(context.boardColumn('future_unknown'),'other');
console.log('PASS Task operational context behavior');
