<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit(1);
$passed=0;$failed=0;$ok=function(bool$v,string$n)use(&$passed,&$failed):void{echo($v?'PASS ':'FAIL ').$n."\n";$v?$passed++:$failed++;};
$source=file_get_contents(__DIR__.'/../includes/Tasks/TaskToolApprovalConsumptionService.php');$controller=file_get_contents(__DIR__.'/../includes/Tasks/TaskApiController.php');$executor=file_get_contents(__DIR__.'/../includes/Tasks/ToolTaskStepExecutor.php');$application=file_get_contents(__DIR__.'/../includes/Tasks/TaskApplicationService.php');
$ok(str_contains($source,'begin_transaction()')&&substr_count($source,'FOR UPDATE')>=2&&str_contains($source,'commit()')&&str_contains($source,'rollback()'),'consumo tiene boundary transaccional y locks');
$ok(str_contains($source,"['consumed']=true")&&str_contains($source,"['consumer_execution_id']=\$executionId")&&str_contains($source,'tool_approval_already_consumed'),'consumo one-shot conserva consumer Execution');
$ok(str_contains($source,'recreateForContinuation(')&&str_contains($source,'hash_equals('),'recrea y compara identidad exacta');
$ok(!preg_match('/UPDATE (?:Tasks|TaskExecutions) SET/',$source)&&!preg_match("/UPDATE TaskSteps SET status/",$source),'consumo no cambia estados');
$ok(!str_contains($source,'ToolRegistry::execute')&&!str_contains($source,'ToolCalls')&&!str_contains($source,'TaskArtifacts')&&!str_contains($source,'Config::getS3'),'consumo no ejecuta Tool ni crea efectos');
$ok(!str_contains($controller,'consume_tool')&&!str_contains($controller,'consume_approval')&&!str_contains($executor,'TaskToolApprovalConsumptionService'),'sin API ni wiring en executor');
$ok(str_contains($application,"unset(\$checkpoint['tool_approval']['identity']")&&str_contains($application,"['consumer_execution_id']"),'detail filtra identidad y consumer Execution internos');
$required=['TASK_TEST_DB_HOST','TASK_TEST_DB_PORT','TASK_TEST_DB_USER','TASK_TEST_DB_PASSWORD','TASK_TEST_DB_NAME'];foreach($required as$k){if(getenv($k)===false||getenv($k)===''){echo"SKIP — integración MySQL consumo/rollback no ejecutada: TASK_TEST_DB_* no configurado.\nResultado: {$passed} PASS, {$failed} FAIL.\n";exit($failed?1:0);}}
$database=(string)getenv('TASK_TEST_DB_NAME');if(!preg_match('/(^|[_-])(test|testing)([_-]|$)/i',$database)){fwrite(STDERR,"FAIL DB no aislada\n");exit(1);}require_once __DIR__.'/../includes/Tasks/bootstrap.php';mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);$db=new mysqli((string)getenv('TASK_TEST_DB_HOST'),(string)getenv('TASK_TEST_DB_USER'),(string)getenv('TASK_TEST_DB_PASSWORD'),$database,(int)getenv('TASK_TEST_DB_PORT'));$db->set_charset('utf8mb4');
$user=0;$session=0;$tasks=[];$trigger='';$suffix=bin2hex(random_bytes(5));
try{
 $email="consume-{$suffix}@example.test";$curp=strtoupper(substr(hash('sha256',$suffix),0,18));$s=$db->prepare("INSERT INTO Users(firstname,lastname,curp,gender,email,password,role,chat,userstatus) VALUES('Consume','Test',?,'Otro',?,'test','Otros',1,'Activo')");$s->bind_param('ss',$curp,$email);$s->execute();$user=(int)$db->insert_id;$s->close();$title="consume-{$suffix}";$model='test';$s=$db->prepare("INSERT INTO ChatSessions(user_id_,project_id_,title,model_id,provider,status) VALUES(?,NULL,?,?,'test','open')");$s->bind_param('iss',$user,$title,$model);$s->execute();$session=(int)$db->insert_id;$s->close();
 $calls=0;$registry=new ToolRegistry();$registry->register('code_edit',static function(array$i)use(&$calls){$calls++;return new ToolExecutionResult('never');},'non_idempotent');$factory=new TaskToolApprovalProposalFactory(new TaskToolRiskPolicy($registry),new TaskToolApprovalFingerprint());$arguments=['action'=>'write','target_filename'=>'App.php','instruction'=>'approved exact instruction'];
 $fixture=function(string$name,string$decision='approved',bool$consumed=false)use($db,$user,$session,$title,$factory,$arguments,&$tasks):array{$public=TaskPublicId::generate();$objective='consume';$s=$db->prepare("INSERT INTO Tasks(public_id,user_id_,created_by_user_id_,project_id_,session_id_,origin_type,title,objective,status,priority,max_attempts) VALUES(?,?,?,NULL,?,'system',?,?,'running','normal',3)");$s->bind_param('siiiss',$public,$user,$user,$session,$title,$objective);$s->execute();$task=(int)$db->insert_id;$s->close();$key='write_'.$name;$s=$db->prepare("INSERT INTO TaskSteps(task_id_,position,step_key,title,step_type,status,agent_key,lock_version) VALUES(?,1,?,'Write','tool','running','test',3)");$s->bind_param('is',$task,$key);$s->execute();$step=(int)$db->insert_id;$s->close();$db->query("UPDATE Tasks SET current_step_id_={$step} WHERE id_={$task}");$traceA=TaskPublicId::generate();$s=$db->prepare("INSERT INTO TaskExecutions(task_id_,step_id_,trace_id,attempt_number,status,finished_at) VALUES(?,?,?,1,'completed',NOW(6))");$s->bind_param('iis',$task,$step,$traceA);$s->execute();$origin=(int)$db->insert_id;$s->close();$traceB=TaskPublicId::generate();$token=TaskPublicId::generate();$s=$db->prepare("INSERT INTO TaskExecutions(task_id_,step_id_,trace_id,attempt_number,status,worker_id,lease_token) VALUES(?,?,?,2,'running','worker-b',?)");$s->bind_param('iiss',$task,$step,$traceB,$token);$s->execute();$consumer=(int)$db->insert_id;$s->close();$originScope=['task_id'=>$task,'step_id'=>$step,'execution_id'=>$origin,'user_id'=>$user,'project_id'=>null,'session_id'=>$session];$proposal=$factory->create('code_edit',$arguments,$originScope);$decisionData=['status'=>$decision,'fingerprint'=>$proposal->fingerprint,'consumed'=>$consumed];if($consumed)$decisionData['consumer_execution_id']=$consumer;$checkpoint=json_encode(['preserved'=>'yes','tool_approval'=>['format_version'=>1,'identity'=>(new TaskToolApprovalIdentity($origin))->toArray(),'proposal'=>$proposal->toArray(),'decision'=>$decisionData]],JSON_THROW_ON_ERROR);$s=$db->prepare('UPDATE TaskSteps SET checkpoint_json=? WHERE id_=?');$s->bind_param('si',$checkpoint,$step);$s->execute();$s->close();$tasks[]=$task;return compact('task','step','key','origin','consumer','proposal');};
 $service=new TaskToolApprovalConsumptionService($db,$factory);$valid=$fixture('valid');$result=$service->consume($valid['consumer'],'code_edit',$arguments);$ok($result['consumed']&&$result['consumer_execution_id']===$valid['consumer']&&$valid['origin']!==$valid['consumer'],'Execution B consume autorización de A');$step=$db->query("SELECT status,checkpoint_json FROM TaskSteps WHERE id_={$valid['step']}")->fetch_assoc();$task=$db->query("SELECT status FROM Tasks WHERE id_={$valid['task']}")->fetch_assoc();$execution=$db->query("SELECT status FROM TaskExecutions WHERE id_={$valid['consumer']}")->fetch_assoc();$cp=json_decode($step['checkpoint_json'],true);$ok($cp['tool_approval']['decision']['consumed']===true&&$cp['tool_approval']['decision']['consumer_execution_id']===$valid['consumer']&&isset($cp['tool_approval']['decision']['consumed_at']),'checkpoint identifica consumo y timestamp');$ok($task['status']==='running'&&$step['status']==='running'&&$execution['status']==='running','consumo no cambia estados');$ok((int)$db->query("SELECT COUNT(*) c FROM TaskEvents WHERE task_id_={$valid['task']} AND execution_id_={$valid['consumer']} AND event_key='tool_approval_consumed'")->fetch_assoc()['c']===1,'evento referencia Execution B');try{$service->consume($valid['consumer'],'code_edit',$arguments);$ok(false,'segundo consumo falla');}catch(TaskConcurrencyException$e){$ok($e->getMessage()==='tool_approval_already_consumed','segundo consumo fail closed');}
 $different=$fixture('different');$changed=$arguments;$changed['instruction'].=' changed';try{$service->consume($different['consumer'],'code_edit',$changed);$ok(false,'argumentos distintos fallan');}catch(TaskConcurrencyException$e){$ok($e->getMessage()==='tool_approval_operation_conflict','argumentos distintos no consumen');}$cp=json_decode($db->query("SELECT checkpoint_json FROM TaskSteps WHERE id_={$different['step']}")->fetch_assoc()['checkpoint_json'],true);$ok($cp['tool_approval']['decision']['consumed']===false,'conflicto conserva consumed false');
 $rejected=$fixture('rejected','rejected');try{$service->consume($rejected['consumer'],'code_edit',$arguments);$ok(false,'decision rechazada falla');}catch(TaskValidationException$e){$ok(true,'decision no approved falla cerrada');}$already=$fixture('already','approved',true);try{$service->consume($already['consumer'],'code_edit',$arguments);$ok(false,'preconsumida falla');}catch(TaskConcurrencyException$e){$ok($e->getMessage()==='tool_approval_already_consumed','preconsumida rechazada');}
 $invalid=$fixture('origin');$cp=json_decode($db->query("SELECT checkpoint_json FROM TaskSteps WHERE id_={$invalid['step']}")->fetch_assoc()['checkpoint_json'],true);$cp['tool_approval']['identity']['proposal_execution_id']=$valid['origin'];$json=json_encode($cp);$s=$db->prepare('UPDATE TaskSteps SET checkpoint_json=? WHERE id_=?');$s->bind_param('si',$json,$invalid['step']);$s->execute();$s->close();try{$service->consume($invalid['consumer'],'code_edit',$arguments);$ok(false,'origin de otra Task falla');}catch(TaskTransitionException$e){$ok($e->getMessage()==='tool_approval_origin_invalid','scope distinto/origin incoherente rechazado');}
 $rollback=$fixture('rollback');$trigger='fail_consume_'.$suffix;$db->query("CREATE TRIGGER `{$trigger}` BEFORE INSERT ON TaskEvents FOR EACH ROW BEGIN IF NEW.task_id_={$rollback['task']} AND NEW.event_key='tool_approval_consumed' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced consume event failure'; END IF; END");try{$service->consume($rollback['consumer'],'code_edit',$arguments);$ok(false,'fallo final propaga');}catch(mysqli_sql_exception$e){$ok(str_contains($e->getMessage(),'forced consume event failure'),'fallo evento simulado');}$db->query("DROP TRIGGER `{$trigger}`");$trigger='';$cp=json_decode($db->query("SELECT checkpoint_json FROM TaskSteps WHERE id_={$rollback['step']}")->fetch_assoc()['checkpoint_json'],true);$events=(int)$db->query("SELECT COUNT(*) c FROM TaskEvents WHERE task_id_={$rollback['task']} AND event_key='tool_approval_consumed'")->fetch_assoc()['c'];$ok($cp['tool_approval']['decision']['consumed']===false&&!isset($cp['tool_approval']['decision']['consumer_execution_id'])&&$events===0,'rollback restaura autorización no consumida');$ok($calls===0,'ningún handler fue ejecutado');
}catch(Throwable$e){$failed++;fwrite(STDERR,'FAIL integración consumo: '.$e->getMessage()."\n");}finally{try{if($trigger!=='')$db->query("DROP TRIGGER IF EXISTS `{$trigger}`");foreach($tasks as$id){$db->query("UPDATE Tasks SET current_step_id_=NULL WHERE id_={$id}");$db->query("DELETE FROM Tasks WHERE id_={$id}");}if($session)$db->query("DELETE FROM ChatSessions WHERE id_={$session}");if($user)$db->query("DELETE FROM Users WHERE id={$user}");}catch(Throwable$e){$failed++;}$db->close();}
echo"Resultado: {$passed} PASS, {$failed} FAIL.\n";exit($failed?1:0);
