<?php
declare(strict_types=1);require_once __DIR__.'/../includes/Tasks/bootstrap.php';$p=0;$f=0;function r0(bool$c,string$m):void{global$p,$f;$c?$p++:$f++;echo($c?'PASS':'FAIL')." - $m\n";}
final class RProgression implements TaskStepProgressionInterface{public ?TaskFailureDisposition$d=null;public int$failed=0;function apply(array$c,TaskStepExecutionResult$r):bool{return true;}function fail(array$c,string$e,?TaskFailureDisposition$d=null):bool{$this->failed++;$this->d=$d;return true;}function cancel(array$c):bool{return true;}}
final class RLease implements TaskLeaseInterface{function heartbeat(array$c):bool{return true;}function assertActive(array$c):void{}}
final class RExec implements TaskStepExecutionInterface{function __construct(private Throwable$e){}function execute(array$c,callable$h,callable$i):TaskStepExecutionResult{throw$this->e;}}
$ctx=['execution_id'=>1];$logical=TaskFailureDisposition::replan('validation_failed','Validación lógica fallida.');$prog=new RProgression();(new TaskExecutionRunner($prog,new RLease(),new RExec(new TaskClassifiedFailureException($logical,'validation_failed'))))->run($ctx);r0($prog->failed===1&&$prog->d?->type===TaskFailureDisposition::REPLAN,'runner preserva disposición lógica');r0($prog->d?->triggerCode==='validation_failed','trigger tipado preservado');$technical=new RProgression();(new TaskExecutionRunner($technical,new RLease(),new RExec(new RuntimeException('network'))))->run($ctx);r0($technical->failed===1&&$technical->d?->type===TaskFailureDisposition::TECHNICAL,'Throwable genérico queda tipado técnico');
try{new TaskFailureDisposition('invented','validation_failed','x');r0(false,'disposición cerrada');}catch(InvalidArgumentException){r0(true,'disposición desconocida rechazada');}try{TaskFailureDisposition::replan('model_prefers_change','x');r0(false,'trigger cerrado');}catch(InvalidArgumentException){r0(true,'trigger no autorizado rechazado');}
final class RStore implements TaskReplanCheckpointStoreInterface{public array$row=['public_id'=>'11111111-1111-4111-8111-111111111111','task_public_id'=>'22222222-2222-4222-8222-222222222222','cycle_public_id'=>'33333333-3333-4333-8333-333333333333','trigger_code'=>'validation_failed','status'=>'checkpointed','source_task_lock_version'=>4,'public_reason'=>'Revisar plan.','lock_version'=>0,'created_at'=>'now'];public bool$safe=true;function findOwned(int$u,string$p):?array{return$u===1?$this->row:null;}function safeCheckpoint(int$u,string$p):array{if(!$this->safe)throw new TaskTransitionException('replan_checkpoint_unsafe');return$this->row;}function transition(int$u,string$p,int$l,string$to):array{if($u!==1||$l!==$this->row['lock_version']||$this->row['status']!=='checkpointed')throw new TaskConcurrencyException('replan_checkpoint_conflict');return$this->row=array_merge($this->row,['status'=>$to,'lock_version'=>$l+1]);}}
$rs=new RStore();$svc=new TaskReplanCheckpointService($rs);$dto=$svc->inspect(1,$rs->row['public_id']);r0($dto->status==='checkpointed'&&$dto->triggerCode==='validation_failed','checkpoint owned inspeccionable');$rej=$svc->reject(1,$dto->publicId,$dto->lockVersion);r0($rej->status==='rejected','reject terminal explícito');try{$svc->reject(2,$dto->publicId,1);r0(false,'foreign reject');}catch(TaskConcurrencyException){r0(true,'foreign reject fail closed');}
$queue=file_get_contents(__DIR__.'/../includes/Tasks/TaskQueueRepository.php');$runner=file_get_contents(__DIR__.'/../includes/Tasks/TaskExecutionRunner.php');$validation=file_get_contents(__DIR__.'/../includes/Tasks/ValidationTaskStepExecutor.php');$continuation=file_get_contents(__DIR__.'/../includes/Tasks/PostTaskContinuationRepository.php');$schema=file_get_contents(__DIR__.'/../sql/fase11e0_replan_checkpoint.sql');$planning=file_get_contents(__DIR__.'/../includes/Tasks/TaskPlanningService.php');
r0(str_contains($queue,'createReplanCheckpoint')&&str_contains($queue,'$this->begin()')&&str_contains($queue,'$this->commit()'),'failure + request comparten transacción');r0(str_contains($queue,"TaskExecutions SET status=?")&&str_contains($queue,"TaskSteps SET status=?")&&str_contains($queue,"Tasks SET status=?"),'checkpoint persiste Execution Step Task');r0(str_contains($queue,"status='failed' LIMIT 1 FOR UPDATE"),'checkpoint bloquea Task failed');r0(str_contains($schema,'uq_task_replan_logical'),'dedupe durable por fallo lógico');r0(str_contains($schema,"'checkpointed','processing','proposed','pending_approval','approved','applied','rejected','failed'"),'state machine durable preparada');r0(str_contains($continuation,'TaskReplanRequests')&&str_contains($continuation,"'checkpointed','processing','proposed','pending_approval','approved'"),'11D inhibido por replan activo');r0(str_contains($validation,'TaskClassifiedFailureException')&&str_contains($validation,"'validation_failed'"),'validation emite trigger server-side');r0(!str_contains($queue,'NextWorkEvaluator')&&!str_contains($queue,'TaskPlanner'),'repository no llama IA/Planner');r0(!preg_match('/DELETE\s+(?:FROM\s+)?TaskSteps/i',$queue),'checkpoint no borra Steps');r0(!str_contains($schema,'plan_json')&&!str_contains($schema,'prompt'),'11E.0 no persiste plan/prompt');r0(!str_contains($runner,'NextWork')&&!str_contains($runner,'TaskPlan'),'runner no mezcla NextWork/Planner');r0(str_contains($planning,'hasExecutions'),'planning inicial permanece intacto');r0(!str_contains(file_get_contents(__DIR__.'/../includes/Tasks/TaskReplanCheckpointService.php'),'approve'),'11E.0 no implementa approval/aplicación');
if(!getenv('TASK_TEST_DB_HOST'))echo"SKIP — MySQL real 11E.0: TASK_TEST_DB_* no configurado\n";echo"$p PASS, $f FAIL\n";exit($f?1:0);
