<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/Tasks/bootstrap.php';
$passed=0;$failed=0;$ok=function(bool$v,string$n)use(&$passed,&$failed):void{echo($v?'PASS ':'FAIL ').$n."\n";$v?$passed++:$failed++;};
$definition=new TaskRecurrenceDefinition();$calculator=new TaskRecurrenceCalculator();
$daily=$definition->validate(['frequency'=>'daily','local_time'=>'10:00:00','timezone'=>'America/Mexico_City','misfire_policy'=>'run_once']);
$ok($daily['timezone']==='America/Mexico_City'&&$daily['weekday']===null,'daily y timezone IANA válidos');
$weekly=$definition->validate(['frequency'=>'weekly','weekday'=>1,'local_time'=>'10:00:00','timezone'=>'Europe/Madrid','misfire_policy'=>'skip']);
$ok($weekly['weekday']===1&&$weekly['misfire_policy']==='skip','weekly ISO weekday válido');
foreach([['frequency'=>'cron','local_time'=>'10:00:00','timezone'=>'UTC'],['frequency'=>'daily','local_time'=>'25:00:00','timezone'=>'UTC'],['frequency'=>'daily','local_time'=>'10:00:00','timezone'=>'UTC+2'],['frequency'=>'weekly','weekday'=>0,'local_time'=>'10:00:00','timezone'=>'UTC'],['frequency'=>'daily','weekday'=>1,'local_time'=>'10:00:00','timezone'=>'UTC'],['frequency'=>'daily','local_time'=>'10:00:00','timezone'=>'UTC','misfire_policy'=>'all']]as$i=>$bad){try{$definition->validate($bad);$ok(false,"definición inválida {$i}");}catch(TaskValidationException){$ok(true,"definición inválida {$i} rechazada");}}
$next=$calculator->next($daily,new DateTimeImmutable('2026-01-10 15:59:59',new DateTimeZone('UTC')));$ok($calculator->storage($next)==='2026-01-10 16:00:00.000000','next occurrence se persiste UTC');
$nextWeekly=$calculator->next($weekly,new DateTimeImmutable('2026-01-11 00:00:00',new DateTimeZone('UTC')));$ok($nextWeekly->format('Y-m-d H:i:s')==='2026-01-12 09:00:00','weekly calcula siguiente lunes civil');
$spring=$definition->validate(['frequency'=>'daily','local_time'=>'02:30:00','timezone'=>'America/New_York']);$springNext=$calculator->next($spring,new DateTimeImmutable('2026-03-08 06:00:00',new DateTimeZone('UTC')));$ok($springNext->format('Y-m-d H:i:s')==='2026-03-08 07:30:00','DST spring-forward normaliza hora inexistente hacia delante conservando minutos');
$fall=$definition->validate(['frequency'=>'daily','local_time'=>'01:30:00','timezone'=>'America/New_York']);$fallNext=$calculator->next($fall,new DateTimeImmutable('2026-11-01 04:00:00',new DateTimeZone('UTC')));$ok($fallNext->format('Y-m-d H:i:s')==='2026-11-01 05:30:00','DST fall-back elige la primera ocurrencia del wall time');
$afterDst=$calculator->next($daily,new DateTimeImmutable('2026-04-10 16:00:00',new DateTimeZone('UTC')));$ok($afterDst->format('Y-m-d H:i:s')==='2026-04-11 16:00:00','daily conserva hora civil tras cambio de offset');
$key1=TaskRecurrenceOccurrenceRepository::taskIdempotencyKey('00000000-0000-4000-8000-000000000001','2026-01-10 16:00:00.000000');$key2=TaskRecurrenceOccurrenceRepository::taskIdempotencyKey('00000000-0000-4000-8000-000000000001','2026-01-10 16:00:00.000000');$ok($key1===$key2&&strlen($key1)<=128&&str_starts_with($key1,'recur:'),'idempotency key determinista y acotada');
$sql=file_get_contents(__DIR__.'/../sql/fase10d_task_recurrence.sql');$dump=file_get_contents(__DIR__.'/../../adbbmis1_Cloud.sql');
foreach(['TaskRecurrenceRules','TaskRecurrenceOccurrences','uq_task_recurrence_occurrence','idx_task_recurrence_rules_due','idx_task_recurrence_rules_owner','fk_task_recurrence_occurrence_task']as$contract)$ok(str_contains($sql,$contract)&&str_contains($dump,$contract),"schema consolidado contiene {$contract}");
$ok(str_contains($sql,"enum('enabled','paused','cancelled')")&&!str_contains($sql,"enum('enabled','paused','cancelled','running"),'estados administrativos mínimos');
$ok(str_contains($sql,"enum('daily','weekly')")&&!str_contains(strtolower($sql),'rrule')&&!str_contains(strtolower($sql),'cron'),'contrato inicial sin cron ni RRULE');
$ok(str_contains($sql,"enum('skip','run_once','catch_up')"),'misfire policy tipada mínima');
$ok(str_contains($sql,'UNIQUE KEY `uq_task_recurrence_occurrence` (`rule_id_`,`logical_occurrence_at`)'),'at-most-one Task por slot respaldado por UNIQUE');
$ok(!preg_match('/execution|artifact|tool_call/i',substr($sql,strpos($sql,'CREATE TABLE IF NOT EXISTS `TaskRecurrenceRules`'),strpos($sql,'CREATE TABLE IF NOT EXISTS `TaskRecurrenceOccurrences`')-strpos($sql,'CREATE TABLE IF NOT EXISTS `TaskRecurrenceRules`'))),'blueprint no guarda Executions Artifacts ni ToolCalls');
$service=file_get_contents(__DIR__.'/../includes/Tasks/TaskRecurrenceService.php');$occurrences=file_get_contents(__DIR__.'/../includes/Tasks/TaskRecurrenceOccurrenceRepository.php');$rules=file_get_contents(__DIR__.'/../includes/Tasks/TaskRecurrenceRuleRepository.php');
$ok(str_contains($service,'sessionScope')&&str_contains($service,'projectOwned')&&str_contains($service,'session_project_mismatch'),'ownership y coherencia de scope server-side');
$ok(str_contains($service,"['enabled','paused']")&&str_contains($service,"'cancelled'"),'cancel admite enabled/paused sin tocar Tasks');
$ok(str_contains($rules,'lock_version=lock_version+1')&&str_contains($rules,'AND lock_version=?'),'optimistic locking gobierna status y next occurrence');
$ok(str_contains($occurrences,"status='materialized'")&&str_contains($occurrences,'task_id_=?'),'occurrence enlaza una única Task sin crearla directamente');
$cancelSlice=substr($service,strpos($service,'public function cancel'),strpos($service,'public function reserve')-strpos($service,'public function cancel'));$ok(!str_contains($cancelSlice,'TaskRepository')&&!str_contains($cancelSlice,'requestCancellation'),'cancel de regla no cancela Tasks materializadas');
$ok(str_contains($service,"'paused','enabled'")&&str_contains($service,'$instant<=$now'),'resume recalcula ocurrencia vencida con reloj inyectado');
$ok(str_contains($service,"recurrence_rule_not_enabled")&&str_contains($service,"occurrence_not_next"),'pausa/cancel y slot incorrecto bloquean reserva');
$ok(str_contains($occurrences,'getCode()!==1062')&&str_contains($occurrences,"'created'=>false"),'duplicado concurrente se recupera como already exists');
$ok(str_contains($occurrences,"status='failed'")&&str_contains($occurrences,"status IN ('reserved','failed')"),'fallo durable permite retry idempotente');
$ok(!str_contains($service,'TaskWorker')&&!str_contains($service,'createManualTask'),'10D no inicia Worker ni materializa automáticamente');
echo"Resultado: {$passed} passed, {$failed} failed\n";
$required=['TASK_TEST_DB_HOST','TASK_TEST_DB_PORT','TASK_TEST_DB_USER','TASK_TEST_DB_PASSWORD','TASK_TEST_DB_NAME'];$configured=true;foreach($required as$k)if(getenv($k)===false||getenv($k)==='')$configured=false;
if(!$configured){echo"SKIP — integración MySQL real 10D: TASK_TEST_DB_* no configurado; schema/contratos estáticos sí validados.\n";exit($failed?1:0);}
$database=(string)getenv('TASK_TEST_DB_NAME');if(!preg_match('/(^|[_-])(test|testing)([_-]|$)/i',$database)){fwrite(STDERR,"FAIL — TASK_TEST_DB_NAME no parece una DB aislada.\n");exit(1);}mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);$db=new mysqli((string)getenv('TASK_TEST_DB_HOST'),(string)getenv('TASK_TEST_DB_USER'),(string)getenv('TASK_TEST_DB_PASSWORD'),$database,(int)getenv('TASK_TEST_DB_PORT'));$db->set_charset('utf8mb4');$db->query("SET time_zone='+00:00'");$db->multi_query($sql);do{if($result=$db->store_result())$result->free();}while($db->more_results()&&$db->next_result());
$scope=$db->query('SELECT s.id_ session_id,s.user_id_,s.project_id_ FROM ChatSessions s ORDER BY s.id_ LIMIT 1')->fetch_assoc();if(!$scope){echo"SKIP — MySQL schema aplicado, pero DB aislada no contiene Session fixture para probar FKs owned.\n";exit($failed?1:0);}
$ruleRepo=new TaskRecurrenceRuleRepository($db);$occRepo=new TaskRecurrenceOccurrenceRepository($db);$taskRepo=new TaskRepository($db);$service=new TaskRecurrenceService($db,$taskRepo,$ruleRepo,$occRepo,$definition,$calculator);$user=(int)$scope['user_id_'];$payload=['session_id'=>(int)$scope['session_id'],'project_id'=>$scope['project_id_'],'frequency'=>'daily','local_time'=>'10:00:00','timezone'=>'UTC','misfire_policy'=>'run_once','title'=>'10D DB fixture','objective'=>'Validar persistencia recurrente','priority'=>'normal','mode'=>'automatic'];$rule=$service->createRule($user,$payload,new DateTimeImmutable('2026-01-01 00:00:00',new DateTimeZone('UTC')));$ok($rule['status']==='enabled'&&$rule['next_occurrence_at']==='2026-01-01 10:00:00.000000','MySQL create rule y next UTC');$ok($ruleRepo->findOwnedById((int)$rule['id_'],$user)!==null&&$ruleRepo->findOwnedById((int)$rule['id_'],$user+999999)===null,'MySQL ownership rule');$reserved=$service->reserve($user,(int)$rule['id_'],(string)$rule['next_occurrence_at']);$duplicate=$service->reserve($user,(int)$rule['id_'],(string)$rule['next_occurrence_at']);$ok($reserved['created']===true&&$duplicate['created']===false&&(int)$reserved['occurrence']['id_']===(int)$duplicate['occurrence']['id_'],'MySQL UNIQUE mismo slot');$other=$occRepo->reserve((int)$rule['id_'],'2026-01-02 10:00:00.000000');$ok($other['created']===true,'MySQL permite slots distintos');$failedOccurrence=$occRepo->fail((int)$reserved['occurrence']['id_'],'task_create_failed',(int)$reserved['occurrence']['lock_version']);$ok($failedOccurrence['status']==='failed'&&$failedOccurrence['task_id_']===null,'MySQL fallo queda durable y retryable');$paused=$service->pause($user,(int)$rule['id_'],(int)$rule['lock_version']);$ok($paused['status']==='paused'&&$paused['next_occurrence_at']===$rule['next_occurrence_at'],'MySQL pause conserva next occurrence');try{$service->pause($user,(int)$rule['id_'],(int)$rule['lock_version']);$ok(false,'MySQL stale lock');}catch(TaskConcurrencyException){$ok(true,'MySQL stale lock rechazado');}$resumed=$service->resume($user,(int)$rule['id_'],(int)$paused['lock_version'],new DateTimeImmutable('2026-01-03 00:00:00',new DateTimeZone('UTC')));$ok($resumed['status']==='enabled'&&$resumed['next_occurrence_at']>'2026-01-03 00:00:00.000000','MySQL resume recalcula slot vencido');$cancelled=$service->cancel($user,(int)$rule['id_'],(int)$resumed['lock_version']);$ok($cancelled['status']==='cancelled','MySQL cancel administrativo');try{$service->reserve($user,(int)$rule['id_'],(string)$cancelled['next_occurrence_at']);$ok(false,'cancelled no reserva');}catch(TaskTransitionException){$ok(true,'MySQL cancelled no reserva futura');}$db->query('DELETE FROM TaskRecurrenceRules WHERE id_='.(int)$rule['id_']);echo"MySQL real 10D: PASS.\nResultado final: {$passed} passed, {$failed} failed\n";exit($failed?1:0);
