<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/Security/CsrfGuard.php';require_once __DIR__.'/../includes/Tasks/bootstrap.php';
final class Phase10FTaskApp extends TaskApplicationService{public function __construct(){}public function list(int$u,array$q):array{return['tasks'=>[],'total'=>0,'limit'=>25,'offset'=>0];}}
final class Phase10FRecurrence implements TaskRecurrenceAdministration{
 public function recurrenceList(int$u,array$q):array{return['rules'=>[['public_id'=>'00000000-0000-4000-8000-000000000001','status'=>'enabled']],'total'=>1,'limit'=>50,'offset'=>0];}
 public function recurrenceDetail(int$u,string$p):array{if($p==='10000000-0000-4000-8000-000000000001')throw new TaskNotFoundException('not_found');return['rule'=>['public_id'=>$p],'occurrences'=>[['logical_occurrence_at'=>'2026-01-01 10:00:00.000000','status'=>'materialized','task_public_id'=>'20000000-0000-4000-8000-000000000001','failure_code'=>null]],'history'=>['limit'=>25]];}
 public function recurrenceCreate(int$u,array$d):array{foreach(['frequency','local_time','timezone','misfire_policy','session_id']as$k)if(($d[$k]??'')==='invalid'||!array_key_exists($k,$d))throw new TaskValidationException('recurrence_'.$k.'_invalid');return['rule'=>['public_id'=>'00000000-0000-4000-8000-000000000001','frequency'=>$d['frequency']]];}
 public function recurrencePause(int$u,array$d):array{return$this->mutate($d,'paused');}public function recurrenceResume(int$u,array$d):array{if(($d['cancelled']??false)===true)throw new TaskConcurrencyException('recurrence_rule_conflict');return$this->mutate($d,'enabled');}public function recurrenceCancel(int$u,array$d):array{return$this->mutate($d,'cancelled');}
 private function mutate(array$d,string$status):array{if(($d['public_id']??'')==='10000000-0000-4000-8000-000000000001')throw new TaskNotFoundException('not_found');if(($d['lock_version']??null)!==2)throw new TaskConcurrencyException('recurrence_rule_conflict');return['rule'=>['public_id'=>$d['public_id'],'status'=>$status,'lock_version'=>3]];}
}
$passed=0;$failed=0;$ok=function(bool$v,string$n)use(&$passed,&$failed):void{echo($v?'PASS ':'FAIL ').$n."\n";$v?$passed++:$failed++;};$_SESSION=['csrf_token'=>'token'];$controller=new TaskApiController(new Phase10FTaskApp(),7,true,new Phase10FRecurrence());$headers=['x-csrf-token'=>'token'];
$ok($controller->handle('GET',['action'=>'recurrence_list'],[])->status===200,'API list owned');$detail=$controller->handle('GET',['action'=>'recurrence_detail','rule'=>'00000000-0000-4000-8000-000000000001'],[]);$ok($detail->status===200&&$detail->body['history']['limit']===25,'API detail bounded');$ok($detail->body['occurrences'][0]['task_public_id']==='20000000-0000-4000-8000-000000000001','API occurrence expone Task public_id');$ok($controller->handle('GET',['action'=>'recurrence_detail','rule'=>'10000000-0000-4000-8000-000000000001'],[])->status===404,'API rule ajena not_found');
$daily=['action'=>'recurrence_create','frequency'=>'daily','local_time'=>'10:00:00','timezone'=>'Europe/Madrid','misfire_policy'=>'run_once','session_id'=>4];$ok($controller->handle('POST',[],$daily,$headers)->status===201,'API create daily');$ok($controller->handle('POST',[],array_replace($daily,['frequency'=>'weekly','weekday'=>1]),$headers)->status===201,'API create weekly');foreach(['frequency','local_time','timezone','misfire_policy']as$field)$ok($controller->handle('POST',[],array_replace($daily,[$field=>'invalid']),$headers)->status===422,"API rechaza {$field} inválido");$ok($controller->handle('POST',[],array_diff_key($daily,['session_id'=>true]),$headers)->status===422,'API exige Session');$ok($controller->handle('POST',[],$daily,[])->status===403,'API create exige CSRF');
foreach(['pause'=>'paused','resume'=>'enabled','cancel'=>'cancelled']as$action=>$status){$response=$controller->handle('POST',[],['action'=>'recurrence_'.$action,'public_id'=>'00000000-0000-4000-8000-000000000001','lock_version'=>2],$headers);$ok($response->status===200&&$response->body['rule']['status']===$status,"API {$action} owned");}
$ok($controller->handle('POST',[],['action'=>'recurrence_pause','public_id'=>'00000000-0000-4000-8000-000000000001','lock_version'=>1],$headers)->status===409,'API stale lock 409');$ok($controller->handle('POST',[],['action'=>'recurrence_resume','public_id'=>'00000000-0000-4000-8000-000000000001','lock_version'=>2,'cancelled'=>true],$headers)->status===409,'API cancelled no resume');$ok($controller->handle('POST',[],['action'=>'recurrence_cancel','public_id'=>'10000000-0000-4000-8000-000000000001','lock_version'=>2],$headers)->status===404,'API mutación ajena not_found');$ok((new TaskApiController(new Phase10FTaskApp(),7,false,new Phase10FRecurrence()))->handle('GET',['action'=>'recurrence_list'],[])->status===404,'feature flag oculta recurrence GET');
$definition=new TaskRecurrenceDefinition();foreach([['frequency'=>'monthly','local_time'=>'10:00:00','timezone'=>'UTC'],['frequency'=>'daily','local_time'=>'25:00:00','timezone'=>'UTC'],['frequency'=>'daily','local_time'=>'10:00:00','timezone'=>'UTC+2'],['frequency'=>'weekly','weekday'=>8,'local_time'=>'10:00:00','timezone'=>'UTC'],['frequency'=>'daily','local_time'=>'10:00:00','timezone'=>'UTC','misfire_policy'=>'invalid']]as$i=>$invalid){try{$definition->validate($invalid);$ok(false,"backend inválido {$i}");}catch(TaskValidationException){$ok(true,"backend rechaza contrato inválido {$i}");}}
$app=file_get_contents(__DIR__.'/../includes/Tasks/TaskRecurrenceApplicationService.php');$rules=file_get_contents(__DIR__.'/../includes/Tasks/TaskRecurrenceRuleRepository.php');$occurrences=file_get_contents(__DIR__.'/../includes/Tasks/TaskRecurrenceOccurrenceRepository.php');$service=file_get_contents(__DIR__.'/../includes/Tasks/TaskRecurrenceService.php');$ok(str_contains($app,'unset($d[\'user_id\'],$d[\'next_occurrence_at\']'),'create ignora autoridad user/next del cliente');$ok(str_contains($app,'$this->service->createRule')&&!str_contains($app,'INSERT INTO'),'create reutiliza service sin SQL');
$ok(str_contains($service,'sessionScope')&&str_contains($service,'projectOwned')&&str_contains($service,'session_project_mismatch'),'service revalida Session Project y mismatch owned');$ok(str_contains($app,'$this->service->pause')&&str_contains($app,'$this->service->resume')&&str_contains($app,'$this->service->cancel'),'mutaciones reutilizan service');$ok(str_contains($rules,'WHERE r.user_id_=?')&&str_contains($occurrences,'r.user_id_=?'),'list/detail aplican ownership SQL');$ok(str_contains($occurrences,'LIMIT ?')&&str_contains($app,"'limit'=>25"),'occurrences bounded a 25');$dto=substr($app,strpos($app,'private function ruleDto'));$ok(!str_contains($dto,"'id_'")&&!str_contains($dto,"'user_id_'")&&!str_contains($dto,"'task_id_'"),'DTO no expone IDs internos');$ok(str_contains($app,"['task_validation_failed','task_materialization_failed']"),'failure_code usa whitelist pública');$cancel=substr($service,strpos($service,'public function cancel'),strpos($service,'public function reserve')-strpos($service,'public function cancel'));$ok(!str_contains($cancel,'Tasks SET')&&!str_contains($cancel,'requestCancellation'),'cancel rule no cancela Tasks existentes');
echo"Resultado: {$passed} passed, {$failed} failed\n";echo"SKIP — MySQL real 10F: TASK_TEST_DB_* no configurado.\n";exit($failed?1:0);
