<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit(1);
$page=file_get_contents(__DIR__.'/../task_center.php');$js=file_get_contents(__DIR__.'/../js/task-center.js');$operational=file_get_contents(__DIR__.'/../js/task-operational-context.js');$css=file_get_contents(__DIR__.'/../css/task-center.css');$chat=file_get_contents(__DIR__.'/../chat.php');$chatJs=file_get_contents(__DIR__.'/../js/chat.js');
$checks=[
 str_contains($page,"['user_id']")&&str_contains($page,'csrf-token'),
 str_contains($js,"credentials:'same-origin'")&&str_contains($js,"'X-CSRF-Token':csrf"),
 str_contains($js,'public_id')&&!str_contains($js,'execution_id')&&!str_contains($js,'checkpoint_json'),
 str_contains($js,'approve_tool')&&str_contains($js,'approve_step')&&str_contains($js,'reject_step'),
 str_contains($js,'resume_tool')&&str_contains($js,'Reanudar')&&!str_contains($js,'execution_id'),
 str_contains($js,'chat_activity_viewer.php')&&str_contains($page,'Trace Explorer'),
 str_contains($css,'@media(max-width:760px)')&&str_contains($chat,'task_center.php'),
 str_contains($page,'name="q"')&&str_contains($page,'name="priority"')&&str_contains($page,'name="project_id"')&&str_contains($page,'name="session_id"'),
 str_contains($js,"pageSize=25")&&str_contains($js,'offset:String')&&str_contains($js,'history.replaceState')&&str_contains($js,'controls.next'),
 str_contains($js,"projects.php?action=list")&&str_contains($js,"chat2_sessions.php")&&str_contains($js,'chat.php?session_id='),
 str_contains($chatJs,"new URLSearchParams(window.location.search).get('session_id')")&&str_contains($chatJs,'sessions.some'),
 str_contains($page,'task-operational-context.js')&&str_contains($page,'task-situation')&&str_contains($page,'task-dates'),
 str_contains($js,'current_step')&&str_contains($js,'scheduled_at')&&str_contains($js,'due_at')&&str_contains($js,'wait_until'),
 str_contains($js,"dependencyAction('add_dependency'")&&str_contains($js,"dependencyAction('remove_dependency'")&&str_contains($js,'depends_on_public_id'),
 str_contains($operational,"task.status==='waiting_user'")&&str_contains($operational,"current?.step_type==='wait'")&&str_contains($operational,'dependencySatisfied'),
 str_contains($page,'id="view-list"')&&str_contains($page,'id="view-board"')&&str_contains($page,'id="board"')&&str_contains($page,'board-card-template'),
 str_contains($js,"view=params.get('view')==='board'")&&str_contains($js,"params.set('view','board')")&&str_contains($js,'Tablero de la página actual:'),
 str_contains($js,'renderBoard(pageTasks)')&&str_contains($js,"node.onclick=()=>detail(task.public_id)")&&substr_count($js,'action=detail')===1,
 str_contains($js,'op.groupBoard(tasks)')&&!preg_match('/(?:set_status|change_status|update_status|UPDATE\\s+Tasks)/i',$js),
 str_contains($js,'controls.previous')&&str_contains($js,'controls.next')&&str_contains($js,'queryString()'),
 str_contains($css,'main.board-view')&&str_contains($css,'overflow-x:auto')&&str_contains($css,'scroll-snap-type'),
 str_contains($js,"new URLSearchParams({action:'list',q:term,limit:'20',offset:'0'})")&&str_contains($js,"params.set('project_id',String(task.project_id))"),
 str_contains($js,'excluded=new Set([task.public_id,...dependencies.map')&&str_contains($js,'dependency-candidate')&&str_contains($js,"b.onclick=()=>detail(b.dataset.relatedTask)"),
 str_contains($js,'d.dependents||[]')&&str_contains($js,'Esta Task depende de')&&str_contains($js,'Tasks que dependen de esta'),
 str_contains($css,'.dependency-candidates')&&str_contains($css,'max-height:190px'),
 str_contains($js,'Historial operativo')&&str_contains($js,'d.history?.has_earlier')&&str_contains($js,"eventLabel[e.event_key]||e.event_key"),
 str_contains($js,'Intentos de ejecución')&&str_contains($js,'Intento ${esc(e.attempt_number)}')&&str_contains($js,'Ver trace ↗'),
 str_contains($js,'Resultado final')&&str_contains($js,'d.final_result')&&str_contains($js,'Ver respuesta completa ↗')&&str_contains($js,'Artifacts (')&&str_contains($js,'a.step_title')&&!str_contains($js,'details_json'),
 str_contains($css,'.timeline-event')&&str_contains($css,'.execution-history')&&str_contains($css,'.artifact-list')&&str_contains($css,'.final-result-card'),
 str_contains($page,'id="task-feedback"')&&str_contains($page,'role="status"')&&str_contains($page,'aria-atomic="true"'),
 str_contains($page,'for="search"')&&str_contains($page,'for="status"')&&str_contains($page,'for="priority"')&&str_contains($page,'for="project"')&&str_contains($page,'for="session"'),
 str_contains($page,'id="detail"')&&str_contains($page,'tabindex="-1"')&&str_contains($page,'aria-busy="false"'),
 str_contains($js,'const busyActions=new Set()')&&str_contains($js,'const sequence=++loadSequence')&&!str_contains($js,'alert('),
 str_contains($js,"announce(success)")&&str_contains($js,"controls.detail.focus")&&str_contains($js,"setAttribute('aria-pressed','true')"),
 str_contains($css,':focus-visible')&&str_contains($css,'@media(max-width:900px)')&&str_contains($css,'@media(max-width:560px)'),
];foreach($checks as$i=>$ok)echo($ok?'PASS ':'FAIL ').'Task Center '.($i+1)."\n";exit(in_array(false,$checks,true)?1:0);
