<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit(1);
require_once __DIR__.'/../includes/Tasks/bootstrap.php';
$passed=0;$failed=0;$ok=function(bool$value,string$name)use(&$passed,&$failed):void{echo($value?'PASS ':'FAIL ').$name."\n";$value?$passed++:$failed++;};
$invalid=function(array$checkpoint,string$name)use($ok):void{try{TaskToolApprovalState::fromCheckpoint(json_encode($checkpoint,JSON_THROW_ON_ERROR));$ok(false,$name);}catch(TaskValidationException$e){$ok($e->getMessage()==='tool_approval_state_invalid',$name);}};
$registry=new ToolRegistry();$calls=0;$registry->register('code_edit',static function(array$input)use(&$calls):ToolExecutionResult{$calls++;return new ToolExecutionResult('not executed');},'non_idempotent');
$proposalFactory=new TaskToolApprovalProposalFactory(new TaskToolRiskPolicy($registry),new TaskToolApprovalFingerprint());
$proposal=$proposalFactory->create('code_edit',['action'=>'write','target_filename'=>'Reader.php','instruction'=>'test'],['task_id'=>1,'step_id'=>2,'execution_id'=>3,'user_id'=>4,'project_id'=>null,'session_id'=>5]);
$approval=['format_version'=>1,'identity'=>(new TaskToolApprovalIdentity(3))->toArray(),'proposal'=>$proposal->toArray()];
$ok(TaskToolApprovalState::fromCheckpoint(null)->status===TaskToolApprovalState::NONE,'checkpoint inexistente clasifica NONE');
$ok(TaskToolApprovalState::fromCheckpoint('{"wait_until":"2030-01-01"}')->status===TaskToolApprovalState::NONE,'otros namespaces clasifican NONE');
$pending=TaskToolApprovalState::fromCheckpoint(json_encode(['tool_approval'=>$approval],JSON_THROW_ON_ERROR));$ok($pending->status===TaskToolApprovalState::PENDING&&$pending->identity?->proposalExecutionId===3&&$pending->proposal?->fingerprint===$proposal->fingerprint,'proposal válida clasifica PENDING');
$approved=$approval;$approved['decision']=['status'=>'approved','fingerprint'=>$proposal->fingerprint,'consumed'=>false];$ok(TaskToolApprovalState::fromCheckpoint(json_encode(['tool_approval'=>$approved],JSON_THROW_ON_ERROR))->status===TaskToolApprovalState::APPROVED,'approved no consumido clasifica APPROVED');
$consumed=$approval;$consumed['decision']=['status'=>'approved','fingerprint'=>$proposal->fingerprint,'consumed'=>true,'consumer_execution_id'=>4,'consumed_at'=>'2026-08-21 12:34:56.000000'];$consumedState=TaskToolApprovalState::fromCheckpoint(json_encode(['tool_approval'=>$consumed],JSON_THROW_ON_ERROR));$ok($consumedState->status===TaskToolApprovalState::CONSUMED&&$consumedState->consumerExecutionId===4,'approved consumido clasifica CONSUMED');
$bad=$approved;$bad['decision']['fingerprint']=str_repeat('b',64);$invalid(['tool_approval'=>$bad],'fingerprints distintos fallan cerrado');
$bad=$approval;$bad['format_version']=2;$invalid(['tool_approval'=>$bad],'format_version inválida falla cerrado');
$bad=$approval;$bad['identity']=['proposal_execution_id'=>0];$invalid(['tool_approval'=>$bad],'identity inválida falla cerrado');
$bad=$approval;$bad['proposal']['fingerprint']='bad';$invalid(['tool_approval'=>$bad],'proposal corrupta falla cerrado');
$bad=$consumed;unset($bad['decision']['consumer_execution_id']);$invalid(['tool_approval'=>$bad],'consumed sin consumer Execution falla cerrado');
$ok($calls===0,'clasificación pura no ejecuta handler');
$readerSource=file_get_contents(__DIR__.'/../includes/Tasks/TaskToolApprovalStateReader.php');$executorSource=file_get_contents(__DIR__.'/../includes/Tasks/ToolTaskStepExecutor.php');
$ok(!preg_match('/\b(?:UPDATE|INSERT|DELETE|FOR UPDATE)\b/i',$readerSource),'reader contiene únicamente SELECT sin FOR UPDATE');
$ok(!str_contains($readerSource,'ToolRegistry')&&!str_contains($readerSource,'pause(')&&!str_contains($readerSource,'consume('),'reader no ejecuta, pausa ni consume Tools');
$ok(str_contains($executorSource,'TaskToolApprovalStateReaderInterface'),'reader está conectado únicamente al gate de Tool Steps explícitos');

$required=['TASK_TEST_DB_HOST','TASK_TEST_DB_PORT','TASK_TEST_DB_USER','TASK_TEST_DB_PASSWORD','TASK_TEST_DB_NAME'];
foreach($required as$key){if(getenv($key)===false||getenv($key)===''){echo"SKIP — integración MySQL del reader no ejecutada: TASK_TEST_DB_* no configurado.\nResultado: {$passed} PASS, {$failed} FAIL.\n";exit($failed?1:0);}}
$database=(string)getenv('TASK_TEST_DB_NAME');if(!preg_match('/(^|[_-])(test|testing)([_-]|$)/i',$database)){fwrite(STDERR,"FAIL — TASK_TEST_DB_NAME no parece una base aislada.\n");exit(1);}
mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);$db=new mysqli((string)getenv('TASK_TEST_DB_HOST'),(string)getenv('TASK_TEST_DB_USER'),(string)getenv('TASK_TEST_DB_PASSWORD'),$database,(int)getenv('TASK_TEST_DB_PORT'));$db->set_charset('utf8mb4');
$user=0;$session=0;$task=0;$step=0;$execution=0;$consumer=0;$broken=0;$suffix=bin2hex(random_bytes(5));
try{
 $email="reader-{$suffix}@example.test";$curp=strtoupper(substr(hash('sha256',$suffix),0,18));$s=$db->prepare("INSERT INTO Users(firstname,lastname,curp,gender,email,password,role,chat,userstatus) VALUES('Reader','Test',?,'Otro',?,'test','Otros',1,'Activo')");$s->bind_param('ss',$curp,$email);$s->execute();$user=(int)$db->insert_id;$s->close();
 $title="reader-{$suffix}";$s=$db->prepare("INSERT INTO ChatSessions(user_id_,project_id_,title,model_id,provider,status) VALUES(?,NULL,?,'test','test','open')");$s->bind_param('is',$user,$title);$s->execute();$session=(int)$db->insert_id;$s->close();
 $public=TaskPublicId::generate();$objective='reader';$s=$db->prepare("INSERT INTO Tasks(public_id,user_id_,created_by_user_id_,project_id_,session_id_,origin_type,title,objective,status,priority,max_attempts) VALUES(?,?,?,NULL,?,'system',?,?,'running','normal',3)");$s->bind_param('siiiss',$public,$user,$user,$session,$title,$objective);$s->execute();$task=(int)$db->insert_id;$s->close();
 $s=$db->prepare("INSERT INTO TaskSteps(task_id_,position,step_key,title,step_type,status,agent_key) VALUES(?,1,'write','Write','tool','running','test')");$s->bind_param('i',$task);$s->execute();$step=(int)$db->insert_id;$s->close();$db->query("UPDATE Tasks SET current_step_id_={$step} WHERE id_={$task}");
 $trace=TaskPublicId::generate();$s=$db->prepare("INSERT INTO TaskExecutions(task_id_,step_id_,trace_id,attempt_number,status) VALUES(?,?,?,1,'running')");$s->bind_param('iis',$task,$step,$trace);$s->execute();$execution=(int)$db->insert_id;$s->close();
 $trace=TaskPublicId::generate();$s=$db->prepare("INSERT INTO TaskExecutions(task_id_,step_id_,trace_id,attempt_number,status) VALUES(?,?,?,2,'running')");$s->bind_param('iis',$task,$step,$trace);$s->execute();$consumer=(int)$db->insert_id;$s->close();
 $scope=['task_id'=>$task,'step_id'=>$step,'execution_id'=>$execution,'user_id'=>$user,'project_id'=>null,'session_id'=>$session];$dbProposal=$proposalFactory->create('code_edit',['action'=>'write','target_filename'=>'Reader.php','instruction'=>'test'],$scope);$dbApproval=['format_version'=>1,'identity'=>(new TaskToolApprovalIdentity($execution))->toArray(),'proposal'=>$dbProposal->toArray()];$json=json_encode(['preserved'=>'yes','tool_approval'=>$dbApproval],JSON_THROW_ON_ERROR);$s=$db->prepare('UPDATE TaskSteps SET checkpoint_json=? WHERE id_=?');$s->bind_param('si',$json,$step);$s->execute();$s->close();
 $reader=new TaskToolApprovalStateReader($db);$before=['task'=>$db->query("SELECT status,lock_version FROM Tasks WHERE id_={$task}")->fetch_assoc(),'step'=>$db->query("SELECT status,lock_version,checkpoint_json FROM TaskSteps WHERE id_={$step}")->fetch_assoc(),'execution'=>$db->query("SELECT status FROM TaskExecutions WHERE id_={$execution}")->fetch_assoc(),'events'=>(int)$db->query("SELECT COUNT(*) c FROM TaskEvents WHERE task_id_={$task}")->fetch_assoc()['c'],'calls'=>(int)$db->query("SELECT COUNT(*) c FROM ToolCalls WHERE session_id_={$session}")->fetch_assoc()['c'],'artifacts'=>(int)$db->query("SELECT COUNT(*) c FROM TaskArtifacts a JOIN TaskExecutions e ON e.id_=a.execution_id_ WHERE e.task_id_={$task}")->fetch_assoc()['c']];
 $ok($reader->read($execution)->status===TaskToolApprovalState::PENDING,'reader MySQL resuelve Execution, Step y Task');$after=['task'=>$db->query("SELECT status,lock_version FROM Tasks WHERE id_={$task}")->fetch_assoc(),'step'=>$db->query("SELECT status,lock_version,checkpoint_json FROM TaskSteps WHERE id_={$step}")->fetch_assoc(),'execution'=>$db->query("SELECT status FROM TaskExecutions WHERE id_={$execution}")->fetch_assoc(),'events'=>(int)$db->query("SELECT COUNT(*) c FROM TaskEvents WHERE task_id_={$task}")->fetch_assoc()['c'],'calls'=>(int)$db->query("SELECT COUNT(*) c FROM ToolCalls WHERE session_id_={$session}")->fetch_assoc()['c'],'artifacts'=>(int)$db->query("SELECT COUNT(*) c FROM TaskArtifacts a JOIN TaskExecutions e ON e.id_=a.execution_id_ WHERE e.task_id_={$task}")->fetch_assoc()['c']];$ok($before===$after,'lectura no modifica checkpoint, estados, eventos, ToolCalls ni Artifacts');
 try{$reader->read(PHP_INT_MAX);$ok(false,'Execution inexistente falla cerrado');}catch(TaskNotFoundException$e){$ok($e->getMessage()==='execution_not_found','Execution inexistente falla cerrado');}
 $db->query('SET FOREIGN_KEY_CHECKS=0');$trace=TaskPublicId::generate();$missing=$step+999999;$s=$db->prepare("INSERT INTO TaskExecutions(task_id_,step_id_,trace_id,attempt_number,status) VALUES(?,?,?,3,'running')");$s->bind_param('iis',$task,$missing,$trace);$s->execute();$broken=(int)$db->insert_id;$s->close();$db->query('SET FOREIGN_KEY_CHECKS=1');try{$reader->read($broken);$ok(false,'relación incoherente falla cerrado');}catch(TaskValidationException$e){$ok($e->getMessage()==='tool_approval_state_invalid','relación incoherente falla cerrado');}
}catch(Throwable$e){$failed++;fwrite(STDERR,'FAIL integración reader: '.$e->getMessage()."\n");}
finally{try{$db->query('SET FOREIGN_KEY_CHECKS=1');if($broken)$db->query("DELETE FROM TaskExecutions WHERE id_={$broken}");if($task){$db->query("UPDATE Tasks SET current_step_id_=NULL WHERE id_={$task}");$db->query("DELETE FROM Tasks WHERE id_={$task}");}if($session)$db->query("DELETE FROM ChatSessions WHERE id_={$session}");if($user)$db->query("DELETE FROM Users WHERE id={$user}");}catch(Throwable$e){$failed++;}$db->close();}
echo"Resultado integración reader: {$passed} PASS, {$failed} FAIL.\n";exit($failed?1:0);
