<?php
declare(strict_types=1);

if(PHP_SAPI!=='cli')exit(1);
$passed=0;$failed=0;$ok=function(bool$value,string$name)use(&$passed,&$failed):void{echo($value?'PASS ':'FAIL ').$name."\n";$value?$passed++:$failed++;};
$serviceSource=file_get_contents(__DIR__.'/../includes/Tasks/TaskToolApprovalPauseService.php');
$ok(str_contains($serviceSource,'begin_transaction()')&&str_contains($serviceSource,'commit()')&&str_contains($serviceSource,'rollback()'),'pausa tiene boundary transaccional completo');
$ok(str_contains($serviceSource,'FOR UPDATE')&&str_contains($serviceSource,'JOIN TaskSteps')&&str_contains($serviceSource,'JOIN Tasks'),'Execution resuelve y bloquea Step/Task server-side');
$ok(str_contains($serviceSource,"status='waiting'")&&str_contains($serviceSource,"status='waiting_user'")&&str_contains($serviceSource,"'tool_approval_requested'"),'persiste los tres estados y evento explícito');
$ok(str_contains($serviceSource,"lease_expires_at=NULL")&&!str_contains($serviceSource,'ToolCalls')&&!str_contains($serviceSource,'TaskArtifacts'),'invalida lease sin ToolCall ni Artifact');
$ok(str_contains($serviceSource,"['tool_approval']")&&str_contains($serviceSource,"'proposal'=>\$proposal->toArray()"),'checkpoint usa namespace y DTO seguro');
$machineSource=file_get_contents(__DIR__.'/../includes/Tasks/TaskExecutionStateMachine.php');
$ok(str_contains($machineSource,"'running' => ['waiting', 'completed', 'failed', 'cancelled']"),'state machine declara running a waiting');

$required=['TASK_TEST_DB_HOST','TASK_TEST_DB_PORT','TASK_TEST_DB_USER','TASK_TEST_DB_PASSWORD','TASK_TEST_DB_NAME'];
foreach($required as$key){if(getenv($key)===false||getenv($key)===''){echo"SKIP — integración MySQL pausa/rollback no ejecutada: TASK_TEST_DB_* no configurado.\n";echo"Resultado: {$passed} PASS, {$failed} FAIL.\n";exit($failed?1:0);}}
$database=(string)getenv('TASK_TEST_DB_NAME');if(!preg_match('/(^|[_-])(test|testing)([_-]|$)/i',$database)){fwrite(STDERR,"FAIL — TASK_TEST_DB_NAME no parece DB aislada.\n");exit(1);}if(!extension_loaded('mysqli')){fwrite(STDERR,"FAIL — mysqli no disponible.\n");exit(1);}
require_once __DIR__.'/../includes/Tasks/bootstrap.php';mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);
$db=new mysqli((string)getenv('TASK_TEST_DB_HOST'),(string)getenv('TASK_TEST_DB_USER'),(string)getenv('TASK_TEST_DB_PASSWORD'),$database,(int)getenv('TASK_TEST_DB_PORT'));$db->set_charset('utf8mb4');
$userId=0;$sessionId=0;$taskId=0;$stepId=0;$executionId=0;$trigger='';$suffix=bin2hex(random_bytes(6));
try{
 foreach(['Users','ChatSessions','Tasks','TaskSteps','TaskExecutions','TaskEvents']as$table){$safe=$db->real_escape_string($table);if($db->query("SHOW TABLES LIKE '{$safe}'")->num_rows!==1)throw new RuntimeException("missing_{$table}");}
 $email="pause-{$suffix}@example.test";$curp=strtoupper(substr(hash('sha256',$suffix),0,18));$stmt=$db->prepare("INSERT INTO Users(firstname,lastname,curp,gender,email,password,role,chat,userstatus) VALUES('Pause','Test',?,'Otro',?,'test','Otros',1,'Activo')");$stmt->bind_param('ss',$curp,$email);$stmt->execute();$userId=(int)$db->insert_id;$stmt->close();
 $title="pause-{$suffix}";$model='test';$stmt=$db->prepare("INSERT INTO ChatSessions(user_id_,project_id_,title,model_id,provider,status) VALUES(?,NULL,?,?,'test','open')");$stmt->bind_param('iss',$userId,$title,$model);$stmt->execute();$sessionId=(int)$db->insert_id;$stmt->close();
 $public=TaskPublicId::generate();$objective='pause integration';$stmt=$db->prepare("INSERT INTO Tasks(public_id,user_id_,created_by_user_id_,project_id_,session_id_,origin_type,title,objective,status,priority,max_attempts) VALUES(?,?,?,NULL,?,'system',?,?,'running','normal',1)");$stmt->bind_param('siiiss',$public,$userId,$userId,$sessionId,$title,$objective);$stmt->execute();$taskId=(int)$db->insert_id;$stmt->close();
 $input=json_encode(['execution_mode'=>'async']);$stmt=$db->prepare("INSERT INTO TaskSteps(task_id_,position,step_key,title,step_type,status,agent_key,input_json,checkpoint_json) VALUES(?,1,'write','Write','tool','running','test',?,JSON_OBJECT('preserved','yes'))");$stmt->bind_param('is',$taskId,$input);$stmt->execute();$stepId=(int)$db->insert_id;$stmt->close();$db->query("UPDATE Tasks SET current_step_id_={$stepId} WHERE id_={$taskId}");
 $trace=TaskPublicId::generate();$stmt=$db->prepare("INSERT INTO TaskExecutions(task_id_,step_id_,trace_id,attempt_number,status,worker_id,lease_token,lease_expires_at) VALUES(?,?,?,1,'running','test-worker',?,DATE_ADD(NOW(6),INTERVAL 60 SECOND))");$token=TaskPublicId::generate();$stmt->bind_param('iiss',$taskId,$stepId,$trace,$token);$stmt->execute();$executionId=(int)$db->insert_id;$stmt->close();
 $registry=new ToolRegistry();$registry->register('code_edit',static fn(array$i)=>new ToolExecutionResult('never'),'non_idempotent');$proposalFactory=new TaskToolApprovalProposalFactory(new TaskToolRiskPolicy($registry),new TaskToolApprovalFingerprint());$scope=['task_id'=>$taskId,'step_id'=>$stepId,'execution_id'=>$executionId,'user_id'=>$userId,'project_id'=>null,'session_id'=>$sessionId];$arguments=['action'=>'write','target_filename'=>'App.php','instruction'=>'private instruction'];$proposal=$proposalFactory->create('code_edit',$arguments,$scope);$service=new TaskToolApprovalPauseService($db,$proposalFactory);
 $result=$service->pause($executionId,$arguments,$proposal);$ok($result['paused']&&!$result['idempotent'],'primera pausa persiste');
 $task=$db->query("SELECT status,current_step_id_ FROM Tasks WHERE id_={$taskId}")->fetch_assoc();$step=$db->query("SELECT status,checkpoint_json,lock_version FROM TaskSteps WHERE id_={$stepId}")->fetch_assoc();$execution=$db->query("SELECT status,lease_expires_at FROM TaskExecutions WHERE id_={$executionId}")->fetch_assoc();
 $ok($task['status']==='waiting_user'&&(int)$task['current_step_id_']===$stepId&&$step['status']==='waiting_user'&&$execution['status']==='waiting'&&$execution['lease_expires_at']===null,'Task/Step/Execution pausan sin avanzar current Step');
 $checkpoint=json_decode($step['checkpoint_json'],true,32,JSON_THROW_ON_ERROR);$encoded=json_encode($checkpoint);$ok(($checkpoint['preserved']??null)==='yes'&&($checkpoint['tool_approval']['proposal']['fingerprint']??null)===$proposal->fingerprint,'checkpoint previo se preserva y proposal queda namespaced');
 $ok(!str_contains($encoded,'private instruction')&&!str_contains($encoded,'arguments')&&!str_contains($encoded,'scope'),'checkpoint no contiene argumentos ni scope');
 $event=$db->query("SELECT task_id_,step_id_,execution_id_,actor_type,event_key,details_json FROM TaskEvents WHERE task_id_={$taskId} AND event_key='tool_approval_requested'")->fetch_assoc();$ok((int)$event['task_id_']===$taskId&&(int)$event['step_id_']===$stepId&&(int)$event['execution_id_']===$executionId&&$event['actor_type']==='agent','evento referencia entidades reales y actor automático');$ok(!str_contains((string)$event['details_json'],'private instruction'),'evento solo contiene metadata segura');
 $lockBefore=(int)$step['lock_version'];$again=$service->pause($executionId,$arguments,$proposal);$events=(int)$db->query("SELECT COUNT(*) c FROM TaskEvents WHERE task_id_={$taskId} AND event_key='tool_approval_requested'")->fetch_assoc()['c'];$lockAfter=(int)$db->query("SELECT lock_version FROM TaskSteps WHERE id_={$stepId}")->fetch_assoc()['lock_version'];$ok($again['idempotent']&&$events===1&&$lockBefore===$lockAfter,'retry idéntico no duplica evento ni cambia lock');
 $differentArgs=$arguments;$differentArgs['instruction']='different';$different=$proposalFactory->create('code_edit',$differentArgs,$scope);try{$service->pause($executionId,$differentArgs,$different);$ok(false,'proposal distinta debe fallar');}catch(TaskConcurrencyException$e){$ok($e->getMessage()==='tool_approval_conflict','proposal distinta no pisa checkpoint');}
 // Reset the fixture and force TaskEvent INSERT to fail after all three updates.
 $db->query("DELETE FROM TaskEvents WHERE task_id_={$taskId}");$db->query("UPDATE TaskExecutions SET status='running',lease_expires_at=DATE_ADD(NOW(6),INTERVAL 60 SECOND) WHERE id_={$executionId}");$db->query("UPDATE TaskSteps SET status='running',checkpoint_json=JSON_OBJECT('preserved','yes') WHERE id_={$stepId}");$db->query("UPDATE Tasks SET status='running' WHERE id_={$taskId}");
 $trigger='fail_pause_event_'.$suffix;$db->query("CREATE TRIGGER `{$trigger}` BEFORE INSERT ON TaskEvents FOR EACH ROW BEGIN IF NEW.event_key='tool_approval_requested' AND NEW.task_id_={$taskId} THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced pause event failure'; END IF; END");
 try{$service->pause($executionId,$arguments,$proposal);$ok(false,'fallo intermedio debe propagar');}catch(mysqli_sql_exception$e){$ok(str_contains($e->getMessage(),'forced pause event failure'),'fallo de evento simulado');}$db->query("DROP TRIGGER `{$trigger}`");$trigger='';
 $task=$db->query("SELECT status FROM Tasks WHERE id_={$taskId}")->fetch_assoc();$step=$db->query("SELECT status,checkpoint_json FROM TaskSteps WHERE id_={$stepId}")->fetch_assoc();$execution=$db->query("SELECT status FROM TaskExecutions WHERE id_={$executionId}")->fetch_assoc();$events=(int)$db->query("SELECT COUNT(*) c FROM TaskEvents WHERE task_id_={$taskId}")->fetch_assoc()['c'];$ok($task['status']==='running'&&$step['status']==='running'&&$execution['status']==='running'&&$events===0&&!str_contains($step['checkpoint_json'],'tool_approval'),'rollback revierte estados, checkpoint y evento');
}catch(Throwable$e){$failed++;fwrite(STDERR,'FAIL integración pausa: '.$e->getMessage()."\n");}
finally{try{if($trigger!=='')$db->query("DROP TRIGGER IF EXISTS `{$trigger}`");if($taskId>0){$db->query("UPDATE Tasks SET current_step_id_=NULL WHERE id_={$taskId}");$db->query("DELETE FROM Tasks WHERE id_={$taskId}");}if($sessionId>0)$db->query("DELETE FROM ChatSessions WHERE id_={$sessionId}");if($userId>0)$db->query("DELETE FROM Users WHERE id={$userId}");}catch(Throwable$e){$failed++;fwrite(STDERR,'FAIL cleanup pausa: '.$e->getMessage()."\n");}$db->close();}
echo"Resultado: {$passed} PASS, {$failed} FAIL.\n";exit($failed?1:0);
