<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit(1);
require_once __DIR__.'/../includes/Tasks/bootstrap.php';

final class ModelGateStates implements TaskToolApprovalStateReaderInterface{public int$calls=0;public function __construct(public TaskToolApprovalState$state){}public function read(int$executionId):TaskToolApprovalState{$this->calls++;return$this->state;}}
final class ModelGateProposals implements TaskToolApprovalProposalFactoryInterface{public int$calls=0;public array$scope=[];public function __construct(private TaskToolApprovalProposalFactory$inner){}public function create(string$key,array$args,array$scope):TaskToolApprovalProposal{$this->calls++;$this->scope=$scope;return$this->inner->create($key,$args,$scope);}}
final class ModelGatePauses implements TaskToolApprovalPauseInterface{public int$calls=0;public function pause(int$id,array$args,TaskToolApprovalProposal$proposal):array{$this->calls++;return['paused'=>true,'idempotent'=>false,'task_id'=>10,'step_id'=>20,'execution_id'=>$id];}}
final class ModelGateConsumptions implements TaskToolApprovalConsumptionInterface
{
    public int$calls=0;public array$order=[];public ?Throwable$error=null;
    public function __construct(private ModelGateStates$states,private array$expected=[]){ }
    public function consume(int$id,string$key,array$args):array{$this->calls++;$this->order[]='consume';if($this->error)throw$this->error;if($this->expected!==[]&&[$key,$args]!==$this->expected)throw new TaskConcurrencyException('tool_approval_operation_conflict');$this->states->state=modelGateState(TaskToolApprovalState::CONSUMED,$id);return['consumed'=>true,'consumer_execution_id'=>$id,'fingerprint'=>str_repeat('a',64)];}
}
final class ModelGateBedrock{public int$calls=0;public array$requests=[];public function __construct(private array$responses){}public function converse(array$params):array{$this->calls++;$this->requests[]=$params;return array_shift($this->responses);}}
final class ModelGateObserver implements ToolExecutionObserverInterface{public int$calls=0;public function observe(array$context,ToolExecutionResult$result):void{$this->calls++;}}

function modelGateState(string$status,int$consumer=99):TaskToolApprovalState{$proposal=new TaskToolApprovalProposal(1,'code_edit','non_idempotent','write_requires_approval','Modificar archivo','App.php',str_repeat('a',64));$approval=['format_version'=>1,'identity'=>(new TaskToolApprovalIdentity(1))->toArray(),'proposal'=>$proposal->toArray()];if($status!==TaskToolApprovalState::PENDING)$approval['decision']=['status'=>'approved','fingerprint'=>$proposal->fingerprint,'consumed'=>$status===TaskToolApprovalState::CONSUMED]+($status===TaskToolApprovalState::CONSUMED?['consumer_execution_id'=>$consumer,'consumed_at'=>'2026-08-21 00:00:00.000000']:[]);return TaskToolApprovalState::fromCheckpoint(json_encode(['tool_approval'=>$approval],JSON_THROW_ON_ERROR));}
function modelGateResponse(array$uses):array{return['stopReason'=>'tool_use','output'=>['message'=>['role'=>'assistant','content'=>array_map(static fn($use)=>['toolUse'=>$use],$uses)]]];}
function modelGateFinal():array{return['stopReason'=>'end_turn','output'=>['message'=>['role'=>'assistant','content'=>[['text'=>'done']]]]];}
function modelGateRequest(int$execution=30):ChatExecutionRequest{return new ChatExecutionRequest(5,6,null,null,'r',null,'prompt',null,'model',0.1,100,0.9,'trace',['task_id'=>10,'step_id'=>20,'execution_id'=>$execution]);}
function modelGate(array$effects,TaskToolApprovalState$state,?ModelGateConsumptions&$consumptions=null,?ModelGateStates&$states=null):TaskChatToolExecutionGate{$tools=new ToolRegistry();foreach($effects as$key=>$effect)$tools->register($key,static fn():ToolExecutionResult=>new ToolExecutionResult('unused'),$effect);$risk=new TaskToolRiskPolicy($tools);$states=new ModelGateStates($state);$proposals=new ModelGateProposals(new TaskToolApprovalProposalFactory($risk,new TaskToolApprovalFingerprint()));$consumptions=new ModelGateConsumptions($states);return new TaskChatToolExecutionGate($risk,$states,$proposals,new ModelGatePauses(),$consumptions);}
function modelGateRuntime(ToolRegistry$tools,TaskChatToolExecutionGate$gate,ModelGateBedrock$bedrock,?ToolExecutionObserverInterface$observer=null):BedrockChatRuntime{return new BedrockChatRuntime(mysqli_init(),$tools,null,$observer,$gate,static fn():array=>['chat_main'=>['is_active'=>1,'model_id'=>'model']],$bedrock);}

$passed=0;$failed=0;$ok=function(bool$value,string$name)use(&$passed,&$failed):void{echo($value?'PASS ':'FAIL ').$name."\n";$value?$passed++:$failed++;};$scope=['task_id'=>10,'step_id'=>20,'execution_id'=>30,'user_id'=>5,'project_id'=>null,'session_id'=>6,'trace_id'=>'trace'];$args=['action'=>'write','target_filename'=>'App.php','instruction'=>'secret'];

$noneStates=new ModelGateStates(TaskToolApprovalState::fromCheckpoint(null));$noneTools=new ToolRegistry();$noneCalls=0;$noneTools->register('code_edit',static function()use(&$noneCalls):ToolExecutionResult{$noneCalls++;return new ToolExecutionResult('unexpected');},'non_idempotent');$noneRisk=new TaskToolRiskPolicy($noneTools);$noneProposals=new ModelGateProposals(new TaskToolApprovalProposalFactory($noneRisk,new TaskToolApprovalFingerprint()));$nonePauses=new ModelGatePauses();$noneConsumes=new ModelGateConsumptions($noneStates);$noneGate=new TaskChatToolExecutionGate($noneRisk,$noneStates,$noneProposals,$nonePauses,$noneConsumes);$noneObserver=new ModelGateObserver();$noneBedrock=new ModelGateBedrock([modelGateResponse([['name'=>'code_edit','toolUseId'=>'w','input'=>$args]])]);$paused=modelGateRuntime($noneTools,$noneGate,$noneBedrock,$noneObserver)->execute(modelGateRequest());
$ok($paused->isPauseAlreadyPersisted()&&$noneProposals->calls===1&&$nonePauses->calls===1&&$noneCalls===0&&$noneObserver->calls===0&&$noneBedrock->calls===1,'write NONE crea proposal/pause y corta Tool, observer, toolResult y Converse');$expectedScope=$scope;unset($expectedScope['trace_id']);$ok($noneProposals->scope===$expectedScope&&!str_contains($paused->controlDecision->safeSummary,'secret'),'proposal usa scope server-side y summary seguro');

$approved=modelGateState(TaskToolApprovalState::APPROVED);$readStates=new ModelGateStates($approved);$readTools=new ToolRegistry();$order=[];foreach(['grep','view']as$key)$readTools->register($key,static function()use(&$order,$key):ToolExecutionResult{$order[]=$key;return new ToolExecutionResult($key);},'read_only');$readTools->register('code_edit',static function()use(&$order):ToolExecutionResult{$order[]='write';return new ToolExecutionResult('written');},'non_idempotent');$readRisk=new TaskToolRiskPolicy($readTools);$readConsumes=new ModelGateConsumptions($readStates,['code_edit',$args]);$readGate=new TaskChatToolExecutionGate($readRisk,$readStates,new ModelGateProposals(new TaskToolApprovalProposalFactory($readRisk,new TaskToolApprovalFingerprint())),new ModelGatePauses(),$readConsumes);$fullBedrock=new ModelGateBedrock([modelGateResponse([['name'=>'grep','toolUseId'=>'r1','input'=>[]],['name'=>'view','toolUseId'=>'r2','input'=>[]],['name'=>'code_edit','toolUseId'=>'w1','input'=>$args]]),modelGateFinal()]);$full=modelGateRuntime($readTools,$readGate,$fullBedrock)->execute(modelGateRequest());
$ok($full->replyText==='done'&&$order===['grep','view','write']&&$readConsumes->calls===1&&$readConsumes->order===['consume'],'APPROVED permite reads, consume write exacta una vez y completa CONSUMED current');

$differentStates=new ModelGateStates($approved);$differentTools=new ToolRegistry();$differentCalls=0;$differentTools->register('code_edit',static function()use(&$differentCalls):ToolExecutionResult{$differentCalls++;return new ToolExecutionResult('unexpected');},'non_idempotent');$differentRisk=new TaskToolRiskPolicy($differentTools);$differentConsume=new ModelGateConsumptions($differentStates,['code_edit',$args]);$differentGate=new TaskChatToolExecutionGate($differentRisk,$differentStates,new ModelGateProposals(new TaskToolApprovalProposalFactory($differentRisk,new TaskToolApprovalFingerprint())),new ModelGatePauses(),$differentConsume);try{$differentGate->beforeExecute('code_edit',$args+['extra'=>'different'],$scope);$ok(false,'operation distinta no permite');}catch(TaskValidationException$e){$ok($e->getMessage()==='tool_approval_operation_conflict'&&$differentCalls===0,'operation conflict falla cerrado sin handler');}

foreach([[TaskToolApprovalState::PENDING,'tool_approval_pending_conflict'],[TaskToolApprovalState::CONSUMED,'tool_approval_already_consumed']]as[$status,$error]){$gate=modelGate(['code_edit'=>'non_idempotent'],modelGateState($status),$consumes);try{$gate->beforeExecute('code_edit',$args,$scope);$ok(false,$status.' no permite write');}catch(TaskValidationException$e){$ok($e->getMessage()===$error&&$consumes->calls===0,$status.' falla sin pause/consume/toolResult');}}

$noneCompletion=modelGate(['view'=>'read_only'],TaskToolApprovalState::fromCheckpoint(null));$noneCompletion->assertCompletionAllowed($scope);$ok(true,'completion NONE permitida');foreach([[TaskToolApprovalState::PENDING,99,'tool_approval_completion_pending'],[TaskToolApprovalState::APPROVED,99,'tool_approval_completion_unconsumed'],[TaskToolApprovalState::CONSUMED,31,'tool_approval_completion_consumer_conflict']]as[$status,$consumer,$error]){$gate=modelGate(['view'=>'read_only'],modelGateState($status,$consumer));try{$gate->assertCompletionAllowed($scope);$ok(false,'completion incompatible no permitida');}catch(TaskValidationException$e){$ok($e->getMessage()===$error,$error.' falla cerrado');}}$current=modelGate(['view'=>'read_only'],modelGateState(TaskToolApprovalState::CONSUMED,30));$current->assertCompletionAllowed($scope);$ok(true,'completion CONSUMED por Execution actual permitida');
$approvedFinalGate=modelGate(['view'=>'read_only'],modelGateState(TaskToolApprovalState::APPROVED));$approvedFinalBedrock=new ModelGateBedrock([modelGateFinal()]);try{modelGateRuntime(new ToolRegistry(),$approvedFinalGate,$approvedFinalBedrock)->execute(modelGateRequest());$ok(false,'Bedrock no completa approval sin consumir');}catch(TaskValidationException$e){$ok($e->getMessage()==='tool_approval_completion_unconsumed'&&$approvedFinalBedrock->calls===1,'Bedrock ejecuta completion guard exactamente antes del resultado final');}

$secondStates=new ModelGateStates(modelGateState(TaskToolApprovalState::APPROVED));$secondTools=new ToolRegistry();$secondTools->register('code_edit',static fn():ToolExecutionResult=>new ToolExecutionResult('ok'),'non_idempotent');$secondRisk=new TaskToolRiskPolicy($secondTools);$secondConsume=new ModelGateConsumptions($secondStates);$secondGate=new TaskChatToolExecutionGate($secondRisk,$secondStates,new ModelGateProposals(new TaskToolApprovalProposalFactory($secondRisk,new TaskToolApprovalFingerprint())),new ModelGatePauses(),$secondConsume);$secondGate->beforeExecute('code_edit',$args,$scope);try{$secondGate->beforeExecute('code_edit',$args,$scope);$ok(false,'segundo write no permitido');}catch(TaskValidationException$e){$ok($e->getMessage()==='tool_approval_already_consumed'&&$secondConsume->calls===1,'segundo write falla por CONSUMED sin segundo consume');}

$normalTools=new ToolRegistry();$normalBedrock=new ModelGateBedrock([modelGateFinal()]);$normal=(new BedrockChatRuntime(mysqli_init(),$normalTools,null,null,null,static fn():array=>['chat_main'=>['is_active'=>1,'model_id'=>'model']],$normalBedrock))->execute(modelGateRequest());$ok($normal->replyText==='done'&&$normalBedrock->calls===1,'Chat sin gate conserva completion normal');
$factory=file_get_contents(__DIR__.'/../includes/Tasks/TaskStepExecutionServiceFactory.php');$ok(str_contains($factory,'new TaskChatToolExecutionGate')&&str_contains($factory,'$tools,$modelGate,$cancellations'),'gate Model Task está activo únicamente desde composición Task');
echo"SKIP — integración MySQL full reexecution no ejecutada: matriz cubierta con contratos/fakes; TASK_TEST_DB_* no usada por este test.\nResultado: $passed PASS, $failed FAIL.\n";exit($failed?1:0);
