<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit(1);
require_once __DIR__.'/../includes/Tasks/bootstrap.php';

final class GateTestArtifacts extends TaskArtifactRepository{public array$records=[];public function __construct(){}public function record(int$e,?int$c,string$r,string$t,int$i):array{$this->records[]=[$e,$c,$r,$t,$i];return['id_'=>count($this->records)];}}
final class GateTestStates implements TaskToolApprovalStateReaderInterface{public ?Throwable$error=null;public function __construct(public TaskToolApprovalState$state){}public int$calls=0;public function read(int$e):TaskToolApprovalState{$this->calls++;if($this->error)throw$this->error;return$this->state;}}
final class GateTestProposals implements TaskToolApprovalProposalFactoryInterface{public int$calls=0;public array$lastScope=[];public function __construct(private TaskToolApprovalProposalFactory$inner){}public function create(string$k,array$a,array$s):TaskToolApprovalProposal{$this->calls++;$this->lastScope=$s;return$this->inner->create($k,$a,$s);}}
final class GateTestPauses implements TaskToolApprovalPauseInterface{public int$calls=0;public function pause(int$e,array$a,TaskToolApprovalProposal$p):array{$this->calls++;return['paused'=>true,'idempotent'=>false,'task_id'=>2,'step_id'=>3,'execution_id'=>$e];}}
final class GateTestConsumptions implements TaskToolApprovalConsumptionInterface{public int$calls=0;public array$order=[];public ?Throwable$error=null;public function consume(int$e,string$k,array$a):array{$this->calls++;$this->order[]='consume';if($this->error)throw$this->error;return['consumed'=>true,'consumer_execution_id'=>$e,'fingerprint'=>str_repeat('a',64)];}}
final class GateTestHandler{public int$calls=0;public function __construct(private?array&$order=null){}public function run(array$i):ToolExecutionResult{$this->calls++;if(is_array($this->order))$this->order[]='execute';return new ToolExecutionResult('done',[],[],true,'ok',91);}}
final class GateRunnerProgression implements TaskStepProgressionInterface{public int$applied=0,$failed=0;public function apply(array$c,TaskStepExecutionResult$r):bool{$this->applied++;return true;}public function fail(array$c,string$e):bool{$this->failed++;return true;}public function cancel(array$c):bool{return true;}}
final class GateRunnerLeases implements TaskLeaseInterface{public int$beats=0;public function heartbeat(array$c):bool{$this->beats++;return true;}public function assertActive(array$c):void{}}
final class GateRunnerSteps implements TaskStepExecutionInterface{public function __construct(private ToolTaskStepExecutor$executor){}public function execute(array$c,callable$h,callable$x):TaskStepExecutionResult{return$this->executor->execute($c,$h,$x);}}

$passed=0;$failed=0;$ok=function(bool$v,string$n)use(&$passed,&$failed):void{echo($v?'PASS ':'FAIL ').$n."\n";$v?$passed++:$failed++;};
$none=TaskToolApprovalState::fromCheckpoint(null);$state=function(string$status):TaskToolApprovalState{$proposal=new TaskToolApprovalProposal(1,'code_edit','non_idempotent','write_requires_approval','Modificar archivo','Gate.php',str_repeat('a',64));$approval=['format_version'=>1,'identity'=>(new TaskToolApprovalIdentity(1))->toArray(),'proposal'=>$proposal->toArray()];if($status!==TaskToolApprovalState::PENDING)$approval['decision']=['status'=>'approved','fingerprint'=>$proposal->fingerprint,'consumed'=>$status===TaskToolApprovalState::CONSUMED]+($status===TaskToolApprovalState::CONSUMED?['consumer_execution_id'=>2,'consumed_at'=>'2026-08-21 00:00:00.000000']:[]);return TaskToolApprovalState::fromCheckpoint(json_encode(['tool_approval'=>$approval],JSON_THROW_ON_ERROR));};
$base=['execution_id'=>4,'task_id'=>2,'step_id'=>3,'user_id'=>5,'session_id'=>6,'project_id'=>null,'trace_id'=>'trace','step_type'=>'tool'];$arguments=['action'=>'write','target_filename'=>'Gate.php','instruction'=>'secret instruction'];
$make=function(string$effect,TaskToolApprovalState$current,?GateTestConsumptions$consumptions=null,?array&$handlerOrder=null):array{$tools=new ToolRegistry();$handler=new GateTestHandler($handlerOrder);$tools->register($effect==='read_only'?'view':'code_edit',[$handler,'run'],$effect);$risk=new TaskToolRiskPolicy($tools);$inner=new TaskToolApprovalProposalFactory($risk,new TaskToolApprovalFingerprint());$states=new GateTestStates($current);$proposals=new GateTestProposals($inner);$pauses=new GateTestPauses();$consumptions??=new GateTestConsumptions();$artifacts=new GateTestArtifacts();$executor=new ToolTaskStepExecutor($tools,$artifacts,$risk,$states,$proposals,$pauses,$consumptions);return[$executor,$states,$proposals,$pauses,$consumptions,$artifacts,$handler];};

[$read,$readStates,$readProposals,$readPauses,$readConsumes,$readArtifacts,$readHandler]=$make('read_only',$none);$readResult=$read->execute($base+['input'=>['tool_key'=>'view','arguments'=>[]]],static function():void{},static fn():bool=>false);$ok($readResult->status==='completed'&&$readHandler->calls===1&&$readPauses->calls===0&&$readConsumes->calls===0,'read_only NONE ejecuta sin pause ni consume');
[$readConflict,,,,,,$readConflictHandler]=$make('read_only',$state(TaskToolApprovalState::PENDING));try{$readConflict->execute($base+['input'=>['tool_key'=>'view']],static function():void{},static fn():bool=>false);$ok(false,'read con HITL no ejecuta');}catch(TaskValidationException$e){$ok($e->getMessage()==='tool_approval_read_state_conflict'&&$readConflictHandler->calls===0,'read con HITL incompatible falla cerrado');}
[$writeNone,$noneStates,$noneProposals,$nonePauses,$noneConsumes,$noneArtifacts,$noneHandler]=$make('non_idempotent',$none);$paused=$writeNone->execute($base+['input'=>['tool_key'=>'code_edit','arguments'=>$arguments]],static function():void{},static fn():bool=>false);$ok($paused->isDurablePauseAlreadyPersisted()&&$noneProposals->calls===1&&$nonePauses->calls===1&&$noneConsumes->calls===0&&$noneHandler->calls===0&&$noneArtifacts->records===[],'write NONE crea proposal, pausa y no ejecuta');$ok($noneProposals->lastScope===['task_id'=>2,'step_id'=>3,'execution_id'=>4,'user_id'=>5,'project_id'=>null,'session_id'=>6]&&!str_contains($paused->summary,'secret'),'scope server-side y summary seguro');
$runnerProgression=new GateRunnerProgression();$runnerLeases=new GateRunnerLeases();$ok((new TaskExecutionRunner($runnerProgression,$runnerLeases,new GateRunnerSteps($writeNone)))->run($base+['input'=>['tool_key'=>'code_edit','arguments'=>$arguments]])&&$runnerLeases->beats===2&&$runnerProgression->applied===0,'write NONE integrado omite heartbeat posterior del Runner y progression');
[$pendingExecutor,,$pendingProposals,$pendingPauses,$pendingConsumes,,$pendingHandler]=$make('non_idempotent',$state(TaskToolApprovalState::PENDING));try{$pendingExecutor->execute($base+['input'=>['tool_key'=>'code_edit','arguments'=>$arguments]],static function():void{},static fn():bool=>false);$ok(false,'PENDING no ejecuta');}catch(TaskValidationException$e){$ok($e->getMessage()==='tool_approval_pending_conflict'&&$pendingHandler->calls===0&&$pendingPauses->calls===0&&$pendingConsumes->calls===0,'PENDING falla cerrado sin duplicar pausa');}
$order=[];$approvedConsumption=new GateTestConsumptions();$approvedConsumption->order=&$order;[$approvedExecutor,,,,$approvedConsumption,$approvedArtifacts,$approvedHandler]=$make('non_idempotent',$state(TaskToolApprovalState::APPROVED),$approvedConsumption,$order);$approvedResult=$approvedExecutor->execute($base+['input'=>['tool_key'=>'code_edit','arguments'=>$arguments]],static function():void{},static fn():bool=>false);$ok($approvedResult->status==='completed'&&$approvedHandler->calls===1&&$approvedConsumption->calls===1&&$order===['consume','execute'],'APPROVED consume antes de execute exactamente una vez');
try{$approvedExecutor->execute(['execution_id'=>4,'step_type'=>'tool','input'=>['tool_key'=>'code_edit','arguments'=>$arguments]],static function():void{},static fn():bool=>false);$ok(false,'write sin scope no ejecuta');}catch(TaskValidationException$e){$ok($e->getMessage()==='tool_approval_scope_invalid'&&$approvedHandler->calls===1,'write exige scope Task server-side completo');}
[$consumedExecutor,,,$consumedPauses,$consumedService,$consumedArtifacts,$consumedHandler]=$make('non_idempotent',$state(TaskToolApprovalState::CONSUMED));try{$consumedExecutor->execute($base+['input'=>['tool_key'=>'code_edit','arguments'=>$arguments]],static function():void{},static fn():bool=>false);$ok(false,'CONSUMED no ejecuta');}catch(TaskValidationException$e){$ok($e->getMessage()==='tool_approval_already_consumed'&&$consumedHandler->calls===0&&$consumedService->calls===0&&$consumedArtifacts->records===[],'CONSUMED falla cerrado sin consume, ToolCall ni Artifact');}
$conflictConsumption=new GateTestConsumptions();$conflictConsumption->error=new TaskConcurrencyException('tool_approval_operation_conflict');[$conflictExecutor,,,,,,$conflictHandler]=$make('non_idempotent',$state(TaskToolApprovalState::APPROVED),$conflictConsumption);$conflictProgression=new GateRunnerProgression();$ok(!(new TaskExecutionRunner($conflictProgression,new GateRunnerLeases(),new GateRunnerSteps($conflictExecutor)))->run($base+['input'=>['tool_key'=>'code_edit','arguments'=>$arguments]])&&$conflictProgression->failed===1&&$conflictHandler->calls===0,'operation conflict se traduce a failure normal y no deja ejecución silenciosa');
$pendingProgression=new GateRunnerProgression();$consumedProgression=new GateRunnerProgression();$ok(!(new TaskExecutionRunner($pendingProgression,new GateRunnerLeases(),new GateRunnerSteps($pendingExecutor)))->run($base+['input'=>['tool_key'=>'code_edit','arguments'=>$arguments]])&&$pendingProgression->failed===1&&!(new TaskExecutionRunner($consumedProgression,new GateRunnerLeases(),new GateRunnerSteps($consumedExecutor)))->run($base+['input'=>['tool_key'=>'code_edit','arguments'=>$arguments]])&&$consumedProgression->failed===1,'PENDING y CONSUMED alcanzan failure normal del Runner');
$invalidState=new GateTestStates($none);$invalidState->error=new TaskValidationException('tool_approval_state_invalid');$invalidTools=new ToolRegistry();$invalidTools->register('code_edit',static fn(array$i):ToolExecutionResult=>new ToolExecutionResult('unexpected'),'non_idempotent');$invalidRisk=new TaskToolRiskPolicy($invalidTools);$invalidProposalFactory=new TaskToolApprovalProposalFactory($invalidRisk,new TaskToolApprovalFingerprint());$invalidExecutor=new ToolTaskStepExecutor($invalidTools,new GateTestArtifacts(),$invalidRisk,$invalidState,new GateTestProposals($invalidProposalFactory),new GateTestPauses(),new GateTestConsumptions());$invalidProgression=new GateRunnerProgression();$ok(!(new TaskExecutionRunner($invalidProgression,new GateRunnerLeases(),new GateRunnerSteps($invalidExecutor)))->run($base+['input'=>['tool_key'=>'code_edit','arguments'=>$arguments]])&&$invalidProgression->failed===1,'checkpoint inválido alcanza failure normal del Runner');
$technicalConsumption=new GateTestConsumptions();$technicalConsumption->error=new TaskConcurrencyException('tool_approval_consumption_conflict');[$technicalExecutor]=$make('non_idempotent',$state(TaskToolApprovalState::APPROVED),$technicalConsumption);$technicalProgression=new GateRunnerProgression();$ok(!(new TaskExecutionRunner($technicalProgression,new GateRunnerLeases(),new GateRunnerSteps($technicalExecutor)))->run($base+['input'=>['tool_key'=>'code_edit','arguments'=>$arguments]])&&$technicalProgression->failed===0,'carrera técnica conserva semántica concurrency del Runner');
$handlerFailureOrder=[];$handlerFailureConsumption=new GateTestConsumptions();$handlerFailureConsumption->order=&$handlerFailureOrder;[$handlerFailureExecutor]=$make('non_idempotent',$state(TaskToolApprovalState::APPROVED),$handlerFailureConsumption,$handlerFailureOrder);$failingTools=new ToolRegistry();$failingTools->register('code_edit',static function():ToolExecutionResult{throw new RuntimeException('handler_failed');},'non_idempotent');$failingRisk=new TaskToolRiskPolicy($failingTools);$handlerFailureExecutor=new ToolTaskStepExecutor($failingTools,new GateTestArtifacts(),$failingRisk,new GateTestStates($state(TaskToolApprovalState::APPROVED)),new GateTestProposals(new TaskToolApprovalProposalFactory($failingRisk,new TaskToolApprovalFingerprint())),new GateTestPauses(),$handlerFailureConsumption);$failureProgression=new GateRunnerProgression();$ok(!(new TaskExecutionRunner($failureProgression,new GateRunnerLeases(),new GateRunnerSteps($handlerFailureExecutor)))->run($base+['input'=>['tool_key'=>'code_edit','arguments'=>$arguments]])&&$handlerFailureConsumption->calls===1&&$failureProgression->failed===1,'handler error después de consume sigue failure normal sin reset');
$factorySource=file_get_contents(__DIR__.'/../includes/Tasks/TaskStepExecutionServiceFactory.php');$ok(str_contains($factorySource,'new TaskToolRiskPolicy($tools)')&&str_contains($factorySource,'new ToolTaskStepExecutor($tools'),'factory comparte un único ToolRegistry entre Policy y executor');
$modelSource=file_get_contents(__DIR__.'/../includes/Tasks/ModelTaskStepExecutor.php');$bedrockSource=file_get_contents(__DIR__.'/../includes/Chat/BedrockChatRuntime.php');$ok(!str_contains($modelSource,'TaskToolApproval')&&!str_contains($bedrockSource,'TaskToolApprovalStateReader'),'Model y Bedrock permanecen fuera del gate');

$required=['TASK_TEST_DB_HOST','TASK_TEST_DB_PORT','TASK_TEST_DB_USER','TASK_TEST_DB_PASSWORD','TASK_TEST_DB_NAME'];foreach($required as$key)if(getenv($key)===false||getenv($key)===''){echo"SKIP — integración MySQL del gate no ejecutada: TASK_TEST_DB_* no configurado.\nResultado: {$passed} PASS, {$failed} FAIL.\n";exit($failed?1:0);}
$database=(string)getenv('TASK_TEST_DB_NAME');if(!preg_match('/(^|[_-])(test|testing)([_-]|$)/i',$database)){fwrite(STDERR,"FAIL DB no aislada\n");exit(1);}mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);$db=new mysqli((string)getenv('TASK_TEST_DB_HOST'),(string)getenv('TASK_TEST_DB_USER'),(string)getenv('TASK_TEST_DB_PASSWORD'),$database,(int)getenv('TASK_TEST_DB_PORT'));$db->set_charset('utf8mb4');
$user=0;$session=0;$task=0;$step=0;$executionA=0;$executionB=0;$suffix=bin2hex(random_bytes(5));
try{
 $email="gate-{$suffix}@example.test";$curp=strtoupper(substr(hash('sha256',$suffix),0,18));$s=$db->prepare("INSERT INTO Users(firstname,lastname,curp,gender,email,password,role,chat,userstatus) VALUES('Gate','Test',?,'Otro',?,'test','Otros',1,'Activo')");$s->bind_param('ss',$curp,$email);$s->execute();$user=(int)$db->insert_id;$s->close();$title="gate-{$suffix}";$s=$db->prepare("INSERT INTO ChatSessions(user_id_,project_id_,title,model_id,provider,status) VALUES(?,NULL,?,'test','test','open')");$s->bind_param('is',$user,$title);$s->execute();$session=(int)$db->insert_id;$s->close();
 $public=TaskPublicId::generate();$objective='gate integration';$s=$db->prepare("INSERT INTO Tasks(public_id,user_id_,created_by_user_id_,project_id_,session_id_,origin_type,title,objective,status,priority,max_attempts) VALUES(?,?,?,NULL,?,'system',?,?,'running','normal',3)");$s->bind_param('siiiss',$public,$user,$user,$session,$title,$objective);$s->execute();$task=(int)$db->insert_id;$s->close();$input=json_encode(['tool_key'=>'code_edit','arguments'=>$arguments],JSON_THROW_ON_ERROR);$s=$db->prepare("INSERT INTO TaskSteps(task_id_,position,step_key,title,step_type,status,agent_key,input_json) VALUES(?,1,'write','Write','tool','running','test',?)");$s->bind_param('is',$task,$input);$s->execute();$step=(int)$db->insert_id;$s->close();$db->query("UPDATE Tasks SET current_step_id_={$step} WHERE id_={$task}");
 $worker='gate-a';$token=TaskPublicId::generate();$trace=TaskPublicId::generate();$s=$db->prepare("INSERT INTO TaskExecutions(task_id_,step_id_,trace_id,attempt_number,status,worker_id,lease_token,lease_expires_at) VALUES(?,?,?,1,'running',?,?,DATE_ADD(NOW(6),INTERVAL 120 SECOND))");$s->bind_param('iisss',$task,$step,$trace,$worker,$token);$s->execute();$executionA=(int)$db->insert_id;$s->close();
 $physicalCalls=0;$toolsDb=new ToolRegistry(new ToolCallRepository($db));$toolsDb->register('code_edit',static function(array$i)use(&$physicalCalls):ToolExecutionResult{$physicalCalls++;return new ToolExecutionResult('written');},'non_idempotent');$riskDb=new TaskToolRiskPolicy($toolsDb);$proposalsDb=new TaskToolApprovalProposalFactory($riskDb,new TaskToolApprovalFingerprint());$executorDb=new ToolTaskStepExecutor($toolsDb,new TaskArtifactRepository($db),$riskDb,new TaskToolApprovalStateReader($db),$proposalsDb,new TaskToolApprovalPauseService($db,$proposalsDb),new TaskToolApprovalConsumptionService($db,$proposalsDb));$stepsDb=new TaskStepExecutorRegistry();$stepsDb->register('tool',$executorDb);$queue=new TaskQueueRepository($db);$runner=new TaskExecutionRunner(new TaskStepProgressionService($queue),new TaskLeaseService($queue,120),new TaskStepExecutionService($stepsDb));$context=['execution_id'=>$executionA,'task_id'=>$task,'step_id'=>$step,'user_id'=>$user,'session_id'=>$session,'project_id'=>null,'trace_id'=>$trace,'worker_id'=>$worker,'lease_token'=>$token,'step_type'=>'tool','input'=>['tool_key'=>'code_edit','arguments'=>$arguments]];
 $ok($runner->run($context)&&$physicalCalls===0,'integración NONE pausa sin ejecutar handler');$taskRow=$db->query("SELECT status,current_step_id_ FROM Tasks WHERE id_={$task}")->fetch_assoc();$stepRow=$db->query("SELECT status,lock_version,checkpoint_json FROM TaskSteps WHERE id_={$step}")->fetch_assoc();$executionRow=$db->query("SELECT status FROM TaskExecutions WHERE id_={$executionA}")->fetch_assoc();$requested=(int)$db->query("SELECT COUNT(*) c FROM TaskEvents WHERE task_id_={$task} AND event_key='tool_approval_requested'")->fetch_assoc()['c'];$callsBefore=(int)$db->query("SELECT COUNT(*) c FROM ToolCalls WHERE session_id_={$session}")->fetch_assoc()['c'];$ok($taskRow['status']==='waiting_user'&&$stepRow['status']==='waiting_user'&&$executionRow['status']==='waiting'&&$requested===1&&$callsBefore===0,'integración pausa persiste estados/evento sin ToolCall');
 $checkpoint=json_decode($stepRow['checkpoint_json'],true,32,JSON_THROW_ON_ERROR);$fingerprint=$checkpoint['tool_approval']['proposal']['fingerprint'];(new TaskToolApprovalDecisionService($db))->decide($user,$public,'write',(int)$stepRow['lock_version'],$fingerprint,true);
 $worker='gate-b';$token=TaskPublicId::generate();$trace=TaskPublicId::generate();$s=$db->prepare("INSERT INTO TaskExecutions(task_id_,step_id_,trace_id,attempt_number,status,worker_id,lease_token,lease_expires_at) VALUES(?,?,?,2,'running',?,?,DATE_ADD(NOW(6),INTERVAL 120 SECOND))");$s->bind_param('iisss',$task,$step,$trace,$worker,$token);$s->execute();$executionB=(int)$db->insert_id;$s->close();$db->query("UPDATE Tasks SET status='running' WHERE id_={$task} AND status='ready'");$db->query("UPDATE TaskSteps SET status='running',lock_version=lock_version+1 WHERE id_={$step} AND status='ready'");$context['execution_id']=$executionB;$context['trace_id']=$trace;$context['worker_id']=$worker;$context['lease_token']=$token;
 $ok($runner->run($context)&&$physicalCalls===1,'integración APPROVED consume y ejecuta exactamente una vez');$taskRow=$db->query("SELECT status FROM Tasks WHERE id_={$task}")->fetch_assoc();$executionRow=$db->query("SELECT status FROM TaskExecutions WHERE id_={$executionB}")->fetch_assoc();$checkpoint=json_decode($db->query("SELECT checkpoint_json FROM TaskSteps WHERE id_={$step}")->fetch_assoc()['checkpoint_json'],true);$consumedEvents=(int)$db->query("SELECT COUNT(*) c FROM TaskEvents WHERE task_id_={$task} AND event_key='tool_approval_consumed'")->fetch_assoc()['c'];$callsAfter=(int)$db->query("SELECT COUNT(*) c FROM ToolCalls WHERE session_id_={$session}")->fetch_assoc()['c'];$artifacts=(int)$db->query("SELECT COUNT(*) c FROM TaskArtifacts a JOIN TaskExecutions e ON e.id_=a.execution_id_ WHERE e.task_id_={$task}")->fetch_assoc()['c'];$ok($taskRow['status']==='completed'&&$executionRow['status']==='completed'&&$checkpoint['tool_approval']['decision']['consumed']===true&&$consumedEvents===1&&$callsAfter===1&&$artifacts===0,'integración completa con consumo/evento/ToolCall y artifacts exactos');
}catch(Throwable$e){$failed++;fwrite(STDERR,'FAIL integración gate: '.$e->getMessage()."\n");}finally{try{if($task){$db->query("UPDATE Tasks SET current_step_id_=NULL WHERE id_={$task}");$db->query("DELETE FROM Tasks WHERE id_={$task}");}if($session)$db->query("DELETE FROM ToolCalls WHERE session_id_={$session}");if($session)$db->query("DELETE FROM ChatSessions WHERE id_={$session}");if($user)$db->query("DELETE FROM Users WHERE id={$user}");}catch(Throwable$e){$failed++;}$db->close();}
echo"Resultado integración gate: {$passed} PASS, {$failed} FAIL.\n";exit($failed?1:0);
