'use strict';
const fs=require('fs'),path=require('path');
const js=fs.readFileSync(path.join(__dirname,'../js/task-center.js'),'utf8');
const page=fs.readFileSync(path.join(__dirname,'../task_center.php'),'utf8');
const css=fs.readFileSync(path.join(__dirname,'../css/task-center.css'),'utf8');
let passed=0,failed=0;const ok=(v,n)=>{console.log(`${v?'PASS':'FAIL'} ${n}`);v?passed++:failed++};
ok(js.includes('id="schedule-form"')&&js.includes('id="scheduled-at"'),'editor está en el detalle compartido');
ok(js.includes('type="datetime-local"')&&js.includes('localInputToIso')&&js.includes('toISOString()'),'fecha local se convierte a ISO con zona');
ok(js.includes("action:'reschedule'")&&js.includes('lock_version:task.lock_version'),'save usa API explícita y lock_version');
ok(js.includes("save(null)")&&js.includes('Quitar programación'),'un-schedule explícito');
ok(js.includes('busyActions.has(key)')&&js.includes("feedback.textContent='Guardando programación…'"),'doble submit y loading protegidos');
ok(js.includes('await detail(task.public_id)'),'éxito y conflicto recargan detalle autoritativo');
ok(js.includes('reschedule_conflict')&&js.includes('task_not_reschedulable')&&js.includes('scheduled_at_invalid'),'errores stale estado e input son públicos');
ok(js.includes("['pending','ready','waiting_user'].includes(t.status)&&d.executions.length===0"),'UI refleja matriz editable backend');
ok(js.includes('Programada para:')&&js.includes('Vence:'),'scheduled_at y due_at permanecen separados');
ok(js.includes("esc(toLocalInput(t.scheduled_at))")&&js.includes("esc(formatDate(t.scheduled_at))"),'valor y texto dinámicos se escapan');
ok(css.includes('.schedule-form')&&css.includes('@media(max-width:760px)'),'editor responsive');
ok(js.includes('renderBoard(tasks)')&&js.includes('async function load()')&&js.includes('function filters()'),'Lista Tablero y filtros permanecen');
ok(page.includes('id="detail"')&&page.includes('js/task-center.js'),'se conserva Task Center oficial');
console.log(`Resultado: ${passed} passed, ${failed} failed`);process.exit(failed?1:0);
