-- READ-ONLY phpMyAdmin inspection. Replace both literal schema placeholders first.
-- This does not execute MigrationRunner and is not a full Fase 12B.4 certification.
SET @clean_schema = 'REPLACE_WITH_CLEAN_TEST_SCHEMA';
SET @upgrade_schema = 'REPLACE_WITH_UPGRADE_TEST_SCHEMA';

SELECT TABLE_SCHEMA,TABLE_NAME,ENGINE,TABLE_COLLATION
FROM information_schema.TABLES
WHERE TABLE_SCHEMA IN (@clean_schema,@upgrade_schema) AND TABLE_TYPE='BASE TABLE'
ORDER BY TABLE_NAME,TABLE_SCHEMA;

SELECT TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,ORDINAL_POSITION,COLUMN_TYPE,DATA_TYPE,
       IS_NULLABLE,COLUMN_DEFAULT,EXTRA,GENERATION_EXPRESSION,CHARACTER_SET_NAME,COLLATION_NAME
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA IN (@clean_schema,@upgrade_schema)
ORDER BY TABLE_NAME,ORDINAL_POSITION,TABLE_SCHEMA;

SELECT TABLE_SCHEMA,TABLE_NAME,INDEX_NAME,NON_UNIQUE,SEQ_IN_INDEX,COLUMN_NAME,
       COLLATION,SUB_PART,INDEX_TYPE,EXPRESSION
FROM information_schema.STATISTICS
WHERE TABLE_SCHEMA IN (@clean_schema,@upgrade_schema)
ORDER BY TABLE_NAME,INDEX_NAME,SEQ_IN_INDEX,TABLE_SCHEMA;

SELECT k.CONSTRAINT_SCHEMA AS TABLE_SCHEMA,k.TABLE_NAME,k.CONSTRAINT_NAME,k.ORDINAL_POSITION,
       k.COLUMN_NAME,k.REFERENCED_TABLE_NAME,k.REFERENCED_COLUMN_NAME,r.UPDATE_RULE,r.DELETE_RULE
FROM information_schema.KEY_COLUMN_USAGE k
JOIN information_schema.REFERENTIAL_CONSTRAINTS r
  ON r.CONSTRAINT_SCHEMA=k.CONSTRAINT_SCHEMA AND r.TABLE_NAME=k.TABLE_NAME
 AND r.CONSTRAINT_NAME=k.CONSTRAINT_NAME
WHERE k.CONSTRAINT_SCHEMA IN (@clean_schema,@upgrade_schema)
ORDER BY k.TABLE_NAME,k.CONSTRAINT_NAME,k.ORDINAL_POSITION,k.CONSTRAINT_SCHEMA;

SELECT t.CONSTRAINT_SCHEMA AS TABLE_SCHEMA,t.TABLE_NAME,t.CONSTRAINT_NAME,c.CHECK_CLAUSE
FROM information_schema.TABLE_CONSTRAINTS t
JOIN information_schema.CHECK_CONSTRAINTS c
  ON c.CONSTRAINT_SCHEMA=t.CONSTRAINT_SCHEMA AND c.CONSTRAINT_NAME=t.CONSTRAINT_NAME
WHERE t.CONSTRAINT_SCHEMA IN (@clean_schema,@upgrade_schema) AND t.CONSTRAINT_TYPE='CHECK'
ORDER BY t.TABLE_NAME,t.CONSTRAINT_NAME,t.CONSTRAINT_SCHEMA;

SELECT TABLE_SCHEMA,COLUMN_TYPE,IS_NULLABLE,COLUMN_DEFAULT
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA IN (@clean_schema,@upgrade_schema)
  AND TABLE_NAME='UserAIAgentConfigs' AND COLUMN_NAME='scope'
ORDER BY TABLE_SCHEMA;
