-- Fase 11E.0: disposición tipada y checkpoint durable; no genera ni aplica planes.
CREATE TABLE IF NOT EXISTS `TaskReplanRequests` (
 `id_` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
 `public_id` char(36) NOT NULL,
 `user_id_` int NOT NULL,
 `project_id_` int NOT NULL,
 `task_id_` bigint UNSIGNED NOT NULL,
 `autonomy_cycle_id_` bigint UNSIGNED NOT NULL,
 `source_step_id_` bigint UNSIGNED NOT NULL,
 `trigger_code` enum('validation_failed','dependency_invalidated','plan_no_longer_executable','explicit_replan_request') NOT NULL,
 `failure_disposition` enum('logical_replan_candidate') NOT NULL DEFAULT 'logical_replan_candidate',
 `status` enum('checkpointed','processing','proposed','pending_approval','approved','applied','rejected','failed') NOT NULL DEFAULT 'checkpointed',
 `source_task_lock_version` int UNSIGNED NOT NULL,
 `public_reason` varchar(500) NOT NULL,
 `attempt_count` tinyint UNSIGNED NOT NULL DEFAULT 0,
 `worker_id` varchar(128) DEFAULT NULL,
 `lease_token` char(36) DEFAULT NULL,
 `lease_expires_at` datetime(6) DEFAULT NULL,
 `lock_version` int UNSIGNED NOT NULL DEFAULT 0,
 `rejected_at` datetime(6) DEFAULT NULL,
 `failed_at` datetime(6) DEFAULT NULL,
 `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 PRIMARY KEY (`id_`),
 UNIQUE KEY `uq_task_replan_public` (`public_id`),
 UNIQUE KEY `uq_task_replan_logical` (`task_id_`,`source_step_id_`,`trigger_code`,`source_task_lock_version`),
 KEY `idx_task_replan_active` (`task_id_`,`status`,`updated_at`),
 KEY `idx_task_replan_owner` (`user_id_`,`project_id_`,`status`),
 CONSTRAINT `fk_task_replan_user` FOREIGN KEY (`user_id_`) REFERENCES `Users` (`id`) ON DELETE RESTRICT,
 CONSTRAINT `fk_task_replan_project` FOREIGN KEY (`project_id_`) REFERENCES `Projects` (`id_`) ON DELETE CASCADE,
 CONSTRAINT `fk_task_replan_task` FOREIGN KEY (`task_id_`) REFERENCES `Tasks` (`id_`) ON DELETE CASCADE,
 CONSTRAINT `fk_task_replan_cycle` FOREIGN KEY (`autonomy_cycle_id_`) REFERENCES `ProjectAutonomyCycles` (`id_`) ON DELETE CASCADE,
 CONSTRAINT `fk_task_replan_step` FOREIGN KEY (`source_step_id_`) REFERENCES `TaskSteps` (`id_`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
