-- Fase 11B: policy de autonomía por Project, ciclos durables y reservas idempotentes.
CREATE TABLE IF NOT EXISTS `ProjectAutonomyPolicies` (
  `id_` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `user_id_` int NOT NULL,
  `project_id_` int NOT NULL,
  `mode` enum('disabled','supervised','automatic') NOT NULL DEFAULT 'disabled',
  `status` enum('active','paused','stopped') NOT NULL DEFAULT 'active',
  `stop_reason` varchar(80) DEFAULT NULL,
  `max_tasks_per_cycle` int UNSIGNED DEFAULT NULL,
  `max_decisions_per_cycle` int UNSIGNED DEFAULT NULL,
  `max_descendant_depth` int UNSIGNED DEFAULT NULL,
  `max_replans_per_cycle` int UNSIGNED DEFAULT NULL,
  `max_runtime_seconds` int UNSIGNED DEFAULT NULL,
  `max_input_tokens` int UNSIGNED DEFAULT NULL,
  `max_output_tokens` int UNSIGNED DEFAULT NULL,
  `max_tool_calls` int UNSIGNED DEFAULT NULL,
  `max_write_tool_calls` int UNSIGNED DEFAULT NULL,
  `lock_version` int UNSIGNED NOT NULL DEFAULT 0,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id_`),
  UNIQUE KEY `uq_project_autonomy_policy_public` (`public_id`),
  UNIQUE KEY `uq_project_autonomy_policy_project` (`project_id_`),
  KEY `idx_project_autonomy_policy_owner` (`user_id_`,`status`),
  CONSTRAINT `fk_project_autonomy_policy_user` FOREIGN KEY (`user_id_`) REFERENCES `Users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_project_autonomy_policy_project` FOREIGN KEY (`project_id_`) REFERENCES `Projects` (`id_`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ProjectAutonomyCycles` (
  `id_` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `policy_id_` bigint UNSIGNED NOT NULL,
  `user_id_` int NOT NULL,
  `project_id_` int NOT NULL,
  `status` enum('active','exhausted','closed','stopped') NOT NULL DEFAULT 'active',
  `active_project_id_` int GENERATED ALWAYS AS (IF(`status`='active',`project_id_`,NULL)) STORED,
  `decisions_consumed` int UNSIGNED NOT NULL DEFAULT 0,
  `tasks_consumed` int UNSIGNED NOT NULL DEFAULT 0,
  `replans_consumed` int UNSIGNED NOT NULL DEFAULT 0,
  `input_tokens_consumed` bigint UNSIGNED NOT NULL DEFAULT 0,
  `output_tokens_consumed` bigint UNSIGNED NOT NULL DEFAULT 0,
  `tool_calls_consumed` int UNSIGNED NOT NULL DEFAULT 0,
  `write_tool_calls_consumed` int UNSIGNED NOT NULL DEFAULT 0,
  `runtime_seconds_consumed` int UNSIGNED NOT NULL DEFAULT 0,
  `lock_version` int UNSIGNED NOT NULL DEFAULT 0,
  `started_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `finished_at` datetime(6) DEFAULT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id_`),
  UNIQUE KEY `uq_project_autonomy_cycle_public` (`public_id`),
  UNIQUE KEY `uq_project_autonomy_cycle_active` (`active_project_id_`),
  KEY `idx_project_autonomy_cycle_owner` (`user_id_`,`project_id_`,`status`),
  CONSTRAINT `fk_project_autonomy_cycle_policy` FOREIGN KEY (`policy_id_`) REFERENCES `ProjectAutonomyPolicies` (`id_`) ON DELETE CASCADE,
  CONSTRAINT `fk_project_autonomy_cycle_user` FOREIGN KEY (`user_id_`) REFERENCES `Users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_project_autonomy_cycle_project` FOREIGN KEY (`project_id_`) REFERENCES `Projects` (`id_`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `ProjectAutonomyReservations` (
  `id_` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `cycle_id_` bigint UNSIGNED NOT NULL,
  `user_id_` int NOT NULL,
  `project_id_` int NOT NULL,
  `idempotency_key` varchar(128) NOT NULL,
  `status` enum('reserved','consumed','released') NOT NULL DEFAULT 'reserved',
  `decisions` int UNSIGNED NOT NULL DEFAULT 0,
  `tasks` int UNSIGNED NOT NULL DEFAULT 0,
  `replans` int UNSIGNED NOT NULL DEFAULT 0,
  `input_tokens` bigint UNSIGNED NOT NULL DEFAULT 0,
  `output_tokens` bigint UNSIGNED NOT NULL DEFAULT 0,
  `tool_calls` int UNSIGNED NOT NULL DEFAULT 0,
  `write_tool_calls` int UNSIGNED NOT NULL DEFAULT 0,
  `runtime_seconds` int UNSIGNED NOT NULL DEFAULT 0,
  `descendant_depth` int UNSIGNED NOT NULL DEFAULT 0,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `consumed_at` datetime(6) DEFAULT NULL,
  `released_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id_`),
  UNIQUE KEY `uq_project_autonomy_reservation_public` (`public_id`),
  UNIQUE KEY `uq_project_autonomy_reservation_idempotency` (`cycle_id_`,`idempotency_key`),
  KEY `idx_project_autonomy_reservation_owner` (`user_id_`,`project_id_`,`status`),
  CONSTRAINT `fk_project_autonomy_reservation_cycle` FOREIGN KEY (`cycle_id_`) REFERENCES `ProjectAutonomyCycles` (`id_`) ON DELETE CASCADE,
  CONSTRAINT `fk_project_autonomy_reservation_user` FOREIGN KEY (`user_id_`) REFERENCES `Users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_project_autonomy_reservation_project` FOREIGN KEY (`project_id_`) REFERENCES `Projects` (`id_`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
