CREATE TABLE IF NOT EXISTS `Tasks` (
 `id_` bigint UNSIGNED NOT NULL AUTO_INCREMENT, `public_id` char(36) NOT NULL, `user_id_` int NOT NULL, `created_by_user_id_` int NOT NULL, `project_id_` int DEFAULT NULL, `session_id_` int NOT NULL, `origin_message_id_` int DEFAULT NULL, `result_message_id_` int DEFAULT NULL, `parent_task_id_` bigint UNSIGNED DEFAULT NULL, `idempotency_key` varchar(128) DEFAULT NULL,
 `origin_type` enum('chat','manual','retry','system') NOT NULL DEFAULT 'manual', `title` varchar(255) NOT NULL, `objective` text NOT NULL, `status` enum('pending','ready','running','waiting_user','waiting_dependency','completed','failed','cancelled') NOT NULL DEFAULT 'pending', `priority` enum('low','normal','high','urgent') NOT NULL DEFAULT 'normal', `progress_percent` tinyint UNSIGNED NOT NULL DEFAULT 0, `current_step_id_` bigint UNSIGNED DEFAULT NULL, `max_attempts` smallint UNSIGNED NOT NULL DEFAULT 1, `attempt_count` smallint UNSIGNED NOT NULL DEFAULT 0,
 `scheduled_at` datetime(6) DEFAULT NULL, `started_at` datetime(6) DEFAULT NULL, `due_at` datetime(6) DEFAULT NULL, `completed_at` datetime(6) DEFAULT NULL, `cancel_requested_at` datetime(6) DEFAULT NULL, `cancelled_at` datetime(6) DEFAULT NULL, `last_heartbeat_at` datetime(6) DEFAULT NULL, `result_summary` mediumtext, `error_code` varchar(80) DEFAULT NULL, `error_message` text, `lock_version` int UNSIGNED NOT NULL DEFAULT 0, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 PRIMARY KEY (`id_`), UNIQUE KEY `uq_tasks_public_id` (`public_id`), UNIQUE KEY `uq_tasks_user_idempotency` (`user_id_`,`idempotency_key`), KEY `idx_tasks_user_status` (`user_id_`,`status`,`updated_at`), KEY `idx_tasks_project_status` (`project_id_`,`status`,`priority`), KEY `idx_tasks_session` (`session_id_`,`updated_at`), KEY `idx_tasks_origin_message` (`origin_message_id_`), KEY `idx_tasks_result_message` (`result_message_id_`), KEY `idx_tasks_parent` (`parent_task_id_`), KEY `idx_tasks_queue` (`status`,`scheduled_at`,`priority`), KEY `idx_tasks_heartbeat` (`status`,`last_heartbeat_at`), KEY `idx_tasks_current_step` (`current_step_id_`),
 CONSTRAINT `fk_tasks_user` FOREIGN KEY (`user_id_`) REFERENCES `Users` (`id`) ON DELETE RESTRICT, CONSTRAINT `fk_tasks_creator` FOREIGN KEY (`created_by_user_id_`) REFERENCES `Users` (`id`) ON DELETE RESTRICT, CONSTRAINT `fk_tasks_project` FOREIGN KEY (`project_id_`) REFERENCES `Projects` (`id_`) ON DELETE SET NULL, CONSTRAINT `fk_tasks_session` FOREIGN KEY (`session_id_`) REFERENCES `ChatSessions` (`id_`) ON DELETE RESTRICT, CONSTRAINT `fk_tasks_origin_message` FOREIGN KEY (`origin_message_id_`) REFERENCES `ChatMessages` (`id_`) ON DELETE SET NULL, CONSTRAINT `fk_tasks_result_message` FOREIGN KEY (`result_message_id_`) REFERENCES `ChatMessages` (`id_`) ON DELETE SET NULL, CONSTRAINT `fk_tasks_parent` FOREIGN KEY (`parent_task_id_`) REFERENCES `Tasks` (`id_`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `TaskSteps` (
 `id_` bigint UNSIGNED NOT NULL AUTO_INCREMENT, `task_id_` bigint UNSIGNED NOT NULL, `position` smallint UNSIGNED NOT NULL, `step_key` varchar(80) NOT NULL, `title` varchar(255) NOT NULL, `description` text, `step_type` enum('plan','model','tool','approval','wait','validation','finalize') NOT NULL, `status` enum('pending','ready','running','waiting_user','waiting_dependency','completed','failed','cancelled','skipped') NOT NULL DEFAULT 'pending', `progress_percent` tinyint UNSIGNED NOT NULL DEFAULT 0, `agent_key` varchar(80) DEFAULT NULL, `model_id` varchar(255) DEFAULT NULL, `input_json` json DEFAULT NULL, `checkpoint_json` json DEFAULT NULL, `output_summary` mediumtext, `error_message` text, `attempt_count` smallint UNSIGNED NOT NULL DEFAULT 0, `max_attempts` smallint UNSIGNED NOT NULL DEFAULT 1, `lock_version` int UNSIGNED NOT NULL DEFAULT 0, `started_at` datetime(6) DEFAULT NULL, `completed_at` datetime(6) DEFAULT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 PRIMARY KEY (`id_`), UNIQUE KEY `uq_task_steps_key` (`task_id_`,`step_key`), UNIQUE KEY `uq_task_steps_position` (`task_id_`,`position`), KEY `idx_task_steps_status` (`task_id_`,`status`,`position`), CONSTRAINT `fk_task_steps_task` FOREIGN KEY (`task_id_`) REFERENCES `Tasks` (`id_`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `TaskExecutions` (
 `id_` bigint UNSIGNED NOT NULL AUTO_INCREMENT, `task_id_` bigint UNSIGNED NOT NULL, `step_id_` bigint UNSIGNED DEFAULT NULL, `trace_id` char(36) DEFAULT NULL, `attempt_number` smallint UNSIGNED NOT NULL, `agent_key` varchar(80) DEFAULT NULL, `model_id` varchar(255) DEFAULT NULL, `status` enum('queued','running','waiting','completed','failed','cancelled','abandoned') NOT NULL DEFAULT 'queued', `worker_id` varchar(120) DEFAULT NULL, `lease_token` char(36) DEFAULT NULL, `lease_expires_at` datetime(6) DEFAULT NULL, `started_at` datetime(6) DEFAULT NULL, `heartbeat_at` datetime(6) DEFAULT NULL, `finished_at` datetime(6) DEFAULT NULL, `error_message` text, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 PRIMARY KEY (`id_`), UNIQUE KEY `uq_task_executions_trace` (`trace_id`), UNIQUE KEY `uq_task_executions_attempt` (`step_id_`,`attempt_number`), KEY `idx_task_executions_task` (`task_id_`), KEY `idx_task_executions_status` (`status`), KEY `idx_task_executions_lease` (`lease_expires_at`), CONSTRAINT `fk_task_executions_task` FOREIGN KEY (`task_id_`) REFERENCES `Tasks` (`id_`) ON DELETE CASCADE, CONSTRAINT `fk_task_executions_step` FOREIGN KEY (`step_id_`) REFERENCES `TaskSteps` (`id_`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `TaskDependencies` (
 `id_` bigint UNSIGNED NOT NULL AUTO_INCREMENT, `task_id_` bigint UNSIGNED NOT NULL, `depends_on_task_id_` bigint UNSIGNED NOT NULL, `condition` enum('completed','terminal_success','terminal_any') NOT NULL DEFAULT 'completed', `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id_`), UNIQUE KEY `uq_task_dependency` (`task_id_`,`depends_on_task_id_`), KEY `idx_task_dependencies_reverse` (`depends_on_task_id_`,`task_id_`), CONSTRAINT `fk_task_dependencies_task` FOREIGN KEY (`task_id_`) REFERENCES `Tasks` (`id_`) ON DELETE CASCADE, CONSTRAINT `fk_task_dependencies_required` FOREIGN KEY (`depends_on_task_id_`) REFERENCES `Tasks` (`id_`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `TaskEvents` (
 `id_` bigint UNSIGNED NOT NULL AUTO_INCREMENT, `task_id_` bigint UNSIGNED NOT NULL, `step_id_` bigint UNSIGNED DEFAULT NULL, `execution_id_` bigint UNSIGNED DEFAULT NULL, `actor_type` enum('user','worker','system','agent') NOT NULL, `actor_user_id_` int DEFAULT NULL, `event_key` varchar(80) NOT NULL, `from_status` varchar(32) DEFAULT NULL, `to_status` varchar(32) DEFAULT NULL, `summary` varchar(255) NOT NULL, `details_json` json DEFAULT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id_`), KEY `idx_task_events_task` (`task_id_`,`id_`), KEY `idx_task_events_step` (`step_id_`,`id_`), KEY `idx_task_events_execution` (`execution_id_`,`id_`), CONSTRAINT `fk_task_events_task` FOREIGN KEY (`task_id_`) REFERENCES `Tasks` (`id_`) ON DELETE CASCADE, CONSTRAINT `fk_task_events_step` FOREIGN KEY (`step_id_`) REFERENCES `TaskSteps` (`id_`) ON DELETE SET NULL, CONSTRAINT `fk_task_events_execution` FOREIGN KEY (`execution_id_`) REFERENCES `TaskExecutions` (`id_`) ON DELETE SET NULL, CONSTRAINT `fk_task_events_actor_user` FOREIGN KEY (`actor_user_id_`) REFERENCES `Users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
SET @fk_exists=(SELECT COUNT(*) FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND CONSTRAINT_NAME='fk_tasks_current_step');
SET @fk_sql=IF(@fk_exists=0,'ALTER TABLE Tasks ADD CONSTRAINT fk_tasks_current_step FOREIGN KEY (current_step_id_) REFERENCES TaskSteps(id_) ON DELETE SET NULL','SELECT 1'); PREPARE s FROM @fk_sql; EXECUTE s; DEALLOCATE PREPARE s;
