-- Fase 11C: propuestas Next-Work durables, approval propio y lineage auditable.
CREATE TABLE IF NOT EXISTS `NextWorkProposals` (
  `id_` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `user_id_` int NOT NULL,
  `project_id_` int NOT NULL,
  `source_task_id_` bigint UNSIGNED NOT NULL,
  `autonomy_cycle_id_` bigint UNSIGNED NOT NULL,
  `reservation_id_` bigint UNSIGNED DEFAULT NULL,
  `spawned_task_id_` bigint UNSIGNED DEFAULT NULL,
  `status` enum('pending_approval','authorized','spawning','spawned','rejected','failed') NOT NULL,
  `dedupe_key` char(64) NOT NULL,
  `payload_hash` char(64) NOT NULL,
  `public_reason` varchar(800) NOT NULL,
  `proposed_title` varchar(255) DEFAULT NULL,
  `proposed_objective` text NOT NULL,
  `evidence_json` json NOT NULL,
  `authorization_reason` varchar(80) NOT NULL,
  `lock_version` int UNSIGNED NOT NULL DEFAULT 0,
  `approved_at` datetime(6) DEFAULT NULL,
  `rejected_at` datetime(6) DEFAULT NULL,
  `spawned_at` datetime(6) DEFAULT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id_`),
  UNIQUE KEY `uq_next_work_proposal_public` (`public_id`),
  UNIQUE KEY `uq_next_work_proposal_dedupe` (`autonomy_cycle_id_`,`dedupe_key`),
  UNIQUE KEY `uq_next_work_proposal_reservation` (`reservation_id_`),
  UNIQUE KEY `uq_next_work_proposal_spawned_task` (`spawned_task_id_`),
  KEY `idx_next_work_proposal_owner_status` (`user_id_`,`project_id_`,`status`,`updated_at`),
  KEY `idx_next_work_proposal_source` (`source_task_id_`,`created_at`),
  CONSTRAINT `fk_next_work_proposal_user` FOREIGN KEY (`user_id_`) REFERENCES `Users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_next_work_proposal_project` FOREIGN KEY (`project_id_`) REFERENCES `Projects` (`id_`) ON DELETE CASCADE,
  CONSTRAINT `fk_next_work_proposal_source` FOREIGN KEY (`source_task_id_`) REFERENCES `Tasks` (`id_`) ON DELETE RESTRICT,
  CONSTRAINT `fk_next_work_proposal_cycle` FOREIGN KEY (`autonomy_cycle_id_`) REFERENCES `ProjectAutonomyCycles` (`id_`) ON DELETE RESTRICT,
  CONSTRAINT `fk_next_work_proposal_reservation` FOREIGN KEY (`reservation_id_`) REFERENCES `ProjectAutonomyReservations` (`id_`) ON DELETE SET NULL,
  CONSTRAINT `fk_next_work_proposal_spawned_task` FOREIGN KEY (`spawned_task_id_`) REFERENCES `Tasks` (`id_`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
